### YamlMime:PowershellCmdlet
summary: |-
  Gets information about the specified application.
module: Az.Batch
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Batch.Models.PSApplication" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-AzBatchApplicationPackage
  href: ./Get-AzBatchApplicationPackage.yml
- text: New-AzBatchApplication
  href: ./New-AzBatchApplication.yml
- text: New-AzBatchApplicationPackage
  href: ./New-AzBatchApplicationPackage.yml
- text: Remove-AzBatchApplication
  href: ./Remove-AzBatchApplication.yml
- text: Remove-AzBatchApplicationPackage
  href: ./Remove-AzBatchApplicationPackage.yml
- text: Set-AzBatchApplication
  href: ./Set-AzBatchApplication.yml
syntaxes:
- >-
  Get-AzBatchApplication [-AccountName] <String> [-ResourceGroupName] <String> [[-ApplicationId] <String>]

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
examples:
- title: 'Example 1: Display the applications in a Batch account'
  code: |-
    PS C:\>Get-AzBatchApplication -AccountName "ContosoBatch" -ResourceGroupName "ContosoBatchGroup"
    ApplicationId AllowUpdates DisplayName

    ------------- ------------ ----------------------------

    litware       False        Litware Advanced Reticulator
  description: |-
    This command displays all applications in the ContosoBatch account.
  summary: ""
parameters:
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: AccountName
  isRequired: true
  description: |+
    Specifies the name of the Batch account that contains the application.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: ApplicationId
  description: |+
    Specifies the ID of the application.

  defaultValue: None
  pipelineInput: true
  position: "2"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: ResourceGroupName
  isRequired: true
  description: |+
    Specifies the name of the resource group that contains the Batch account.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  parameterValueGroup: ""
uid: Az.Batch.Get-AzBatchApplication
name: Get-AzBatchApplication
description: |-
  The **Get-AzBatchApplication** cmdlet gets information about an application in an Azure Batch account.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Batch.dll-Help.xml
  Module Name: Az.Batch
  ms.assetid: CF8B8E94-3C6C-4D68-B55B-956393890946
  online version: https://docs.microsoft.com/en-us/powershell/module/az.batch/get-azbatchapplication
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Batch/Batch/help/Get-AzBatchApplication.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Batch/Batch/help/Get-AzBatchApplication.md
