### YamlMime:PowershellCmdlet
summary: |-
  Updates settings for the specified application.
module: Az.Batch
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="System.Nullable`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="" data-throw-if-not-resolved="False" /><span>[</span><xref href="System.Boolean, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e" data-throw-if-not-resolved="False" /><span>]</span><span>]</span>
  description: ""
outputs:
- name: <xref href="System.Void" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-AzBatchApplication
  href: ./Get-AzBatchApplication.yml
- text: Get-AzBatchApplicationPackage
  href: ./Get-AzBatchApplicationPackage.yml
- text: New-AzBatchApplication
  href: ./New-AzBatchApplication.yml
- text: New-AzBatchApplicationPackage
  href: ./New-AzBatchApplicationPackage.yml
- text: Remove-AzBatchApplication
  href: ./Remove-AzBatchApplication.yml
- text: Remove-AzBatchApplicationPackage
  href: ./Remove-AzBatchApplicationPackage.yml
syntaxes:
- >-
  Set-AzBatchApplication [-AccountName] <String> [-ResourceGroupName] <String> [-ApplicationId] <String>

   [[-DisplayName] <String>] [[-DefaultVersion] <String>] [[-AllowUpdates] <Boolean>]

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
examples:
- title: 'Example 1: Update an application in a Batch account'
  code: |-
    PS C:\>Set-AzBatchApplication -AccountName "ContosoBatch" -ResourceGroupName "ContosoBatchGroup" -ApplicationId "Litware" -AllowUpdates $False
  description: |-
    This command changes whether the Llitware application in the ContosoBatch account allows updates.
    The command does not change the default version or display name of the application.
  summary: ""
parameters:
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: AccountName
  isRequired: true
  description: |+
    Specifies the name of the Batch account for which this cmdlet modifies an application.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Nullable`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="System.Boolean" data-throw-if-not-resolved="False" /><span>]</span>
  name: AllowUpdates
  description: |+
    Specifies whether packages within the application can be overwritten using the same version string.

  defaultValue: None
  pipelineInput: true
  position: "5"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: ApplicationId
  isRequired: true
  description: |+
    Specifies the ID of the application.

  defaultValue: None
  pipelineInput: true
  position: "2"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: DefaultVersion
  description: |+
    Specifies which package to use if a client requests the application but does not specify a version.

  defaultValue: None
  pipelineInput: true
  position: "4"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: DisplayName
  description: |+
    Specifies the display name for the application.

  defaultValue: None
  pipelineInput: true
  position: "3"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: ResourceGroupName
  isRequired: true
  description: |+
    Specifies the name of the resource group that contains the Batch account.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  parameterValueGroup: ""
uid: Az.Batch.Set-AzBatchApplication
name: Set-AzBatchApplication
description: |-
  The **Set-AzBatchApplication** cmdlet modifies settings for the specified Azure Batch application.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Batch.dll-Help.xml
  Module Name: Az.Batch
  ms.assetid: DCA1FD7A-54AF-48B1-A245-BFA9C43ACA9B
  online version: https://docs.microsoft.com/en-us/powershell/module/az.batch/set-azbatchapplication
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Batch/Batch/help/Set-AzBatchApplication.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Batch/Batch/help/Set-AzBatchApplication.md
