### YamlMime:PowershellCmdlet
summary: |-
  Get Service Fabric application details.
module: Az.ServiceFabric
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.ServiceFabric.Models.PSApplication" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Get-AzServiceFabricApplication [-ResourceGroupName] <String> [-ClusterName] <String>

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
- >-
  Get-AzServiceFabricApplication [-ResourceGroupName] <String> [-ClusterName] <String> [-Name] <String>

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
- >-
  Get-AzServiceFabricApplication -ResourceId <String> [-DefaultProfile <IAzureContextContainer>]

   [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    PS C:\> $resourceGroupName = "testRG"
    PS C:\> $clusterName = "testCluster"
    PS C:\> $appName = "testApp"
    PS C:\> Get-AzServiceFabricApplication -ResourceGroupName $resourceGroupName -ClusterName $clusterName -Name $appName
  description: |-
    This example gets the application resource details for the application "testApp".
  summary: ""
- title: Example 2
  code: |-
    PS C:\> $resourceGroupName = "testRG"
    PS C:\> $clusterName = "testCluster"
    PS C:\> Get-AzServiceFabricApplication -ResourceGroupName $resourceGroupName -ClusterName $clusterName
  description: |-
    This example gets a list of the applications under the cluster "testCluster".
  summary: ""
parameters:
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: ClusterName
  isRequired: true
  description: |+
    Specify the name of the cluster.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with Azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    Specify the name of the application.

  defaultValue: None
  pipelineInput: true
  position: "2"
  aliases: ApplicationName
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: ResourceGroupName
  isRequired: true
  description: |+
    Specify the name of the resource group.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: ResourceId
  isRequired: true
  description: |+
    Arm ResourceId of the application.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Az.ServiceFabric.Get-AzServiceFabricApplication
name: Get-AzServiceFabricApplication
description: |-
  This cmdlet gets the application details in the specified resource group and cluster.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.ServiceFabric.dll-Help.xml
  Module Name: Az.ServiceFabric
  online version: https://docs.microsoft.com/en-us/powershell/module/az.servicefabric/get-azservicefabricapplication
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/ServiceFabric/ServiceFabric/help/Get-AzServiceFabricApplication.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/ServiceFabric/ServiceFabric/help/Get-AzServiceFabricApplication.md
