### YamlMime:PowershellCmdlet
summary: |-
  Gets the list of all VpnServerConfigurations that are associated with this VirtualWan.
module: Az.Network
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: |-
    Microsoft.Azure.Commands.Network.Models.PSVirtualWan
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSVpnServerConfigurationsResponse" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Get-AzVirtualWanVpnServerConfiguration [-Name <String>] -ResourceGroupName <String>

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
- >-
  Get-AzVirtualWanVpnServerConfiguration [-Name <String>] -ResourceGroupName <String>

   -VirtualWanObject <PSVirtualWan> [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
- >-
  Get-AzVirtualWanVpnServerConfiguration [-Name <String>] -ResourceGroupName <String> -ResourceId <String>

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    PS C:\> Get-AzVirtualWanVpnServerConfiguration -Name WestUsVirtualWan -ResourceGroupName P2SCortexGATesting

    VpnServerConfigurationResourceIds : [
                                          "/subscriptions/b1f1deed-af60-4bab-9223-65d340462e24/resourceGroups/P2SCortexGATesting/providers/Microsoft.Network/vpnServerConfigurations/WestUsConfig"                           ]
  description: ""
  summary: ""
parameters:
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with Azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  description: |+
    The resource name.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ResourceName
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: ResourceGroupName
  isRequired: true
  description: |+
    The resource group name.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: ResourceId
  isRequired: true
  description: |+
    The Azure resource ID for the virtual wan.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: VirtualWanId
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSVirtualWan" data-throw-if-not-resolved="False" />
  name: VirtualWanObject
  isRequired: true
  description: |+
    The virtual wan object.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: VirtualWan
  parameterValueGroup: ""
uid: Az.Network.Get-AzVirtualWanVpnServerConfiguration
name: Get-AzVirtualWanVpnServerConfiguration
description: |-
  The **Get-AzVirtualWanVpnServerConfiguration** cmdlet will return the list of all VpnServerConfigurations that are associated with this VirtualWan. i.e. All the VpnServerConfigurations which are attached to any P2SVpnGateways under VirutalHubs of this VirtualWan.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  Module Name: Az.Network
  online version: https://docs.microsoft.com/en-us/powershell/module/az.network/get-azvirtualwanvpnserverconfiguration
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Get-AzVirtualWanVpnServerConfiguration.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Get-AzVirtualWanVpnServerConfiguration.md
