### YamlMime:PowershellCmdlet
summary: |-
  Gets a probe configuration for a load balancer.
module: Az.Network
notes: ""
inputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSLoadBalancer" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSProbe" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Add-AzLoadBalancerProbeConfig
  href: ./Add-AzLoadBalancerProbeConfig.yml
- text: Get-AzLoadBalancer
  href: ./Get-AzLoadBalancer.yml
- text: New-AzLoadBalancerProbeConfig
  href: ./New-AzLoadBalancerProbeConfig.yml
- text: Remove-AzLoadBalancerProbeConfig
  href: ./Remove-AzLoadBalancerProbeConfig.yml
- text: Set-AzLoadBalancerProbeConfig
  href: ./Set-AzLoadBalancerProbeConfig.yml
syntaxes:
- >-
  Get-AzLoadBalancerProbeConfig -LoadBalancer <PSLoadBalancer> [-Name <String>]

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
examples:
- title: 'Example 1: Get the probe configuration of a load balancer'
  code: |-
    PS C:\>$slb = Get-AzLoadBalancer -Name "MyLoadBalancer" -ResourceGroupName "MyResourceGroup"
    PS C:\> Get-AzLoadBalancerProbeConfig -Name "MyProbe" -LoadBalancer $slb
  description: |-
    The first command gets the load balancer named MyLoadBalancer, and then stores it in the variable $slb.
    The second command gets the associated probe configuration named MyProbe from the load balancer in $slb.
  summary: ""
parameters:
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSLoadBalancer" data-throw-if-not-resolved="False" />
  name: LoadBalancer
  isRequired: true
  description: |+
    Specifies the load balancer that is associated with the probe configuration to get.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  description: |+
    Specifies the name of the probe configuration to get.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Az.Network.Get-AzLoadBalancerProbeConfig
name: Get-AzLoadBalancerProbeConfig
description: |-
  The **Get-AzLoadBalancerProbeConfig** cmdlet gets one or more probe configurations for a load balancer.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  Module Name: Az.Network
  ms.assetid: 278228EB-0126-4F27-A30F-51DC498C65FE
  online version: https://docs.microsoft.com/en-us/powershell/module/az.network/get-azloadbalancerprobeconfig
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Get-AzLoadBalancerProbeConfig.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Get-AzLoadBalancerProbeConfig.md
