### YamlMime:PowershellCmdlet
summary: |-
  Gets an SSL certificate for an application gateway.
module: Az.Network
notes: ""
inputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationGateway" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationGatewaySslCertificate" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Add-AzApplicationGatewaySslCertificate
  href: ./Add-AzApplicationGatewaySslCertificate.yml
- text: New-AzApplicationGatewaySslCertificate
  href: ./New-AzApplicationGatewaySslCertificate.yml
- text: Remove-AzApplicationGatewaySslCertificate
  href: ./Remove-AzApplicationGatewaySslCertificate.yml
- text: Set-AzApplicationGatewaySslCertificate
  href: ./Set-AzApplicationGatewaySslCertificate.yml
syntaxes:
- >-
  Get-AzApplicationGatewaySslCertificate [-Name <String>] -ApplicationGateway <PSApplicationGateway>

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
examples:
- title: 'Example 1: Get a specific SSL certificate'
  code: |-
    PS C:\>$AppGW = Get-AzApplicationGateway -Name "ApplicationGateway01" -ResourceGroupName "ResourceGroup01"
    PS C:\> $Cert = Get-AzApplicationGatewaySslCertificate -Name "Cert01" -ApplicationGateway $AppGW
  description: |-
    The first command gets the Application Gateway named ApplicationGateway01 and stores the result in the variable named $AppGW.
    The second command gets the SSL certificate named Cert01 from the application gateway stored in the variable named $AppGW.
    The command stores the certificate in the variable named $Cert.
  summary: ""
- title: 'Example 2: Get a list of SSL certificates'
  code: |-
    PS C:\>$AppGW = Get-AzApplicationGateway -Name "ApplicationGateway01" -ResourceGroupName "ResourceGroup01"
    PS C:\> $Certs = Get-AzApplicationGatewaySslCertificate -ApplicationGateway $AppGW
  description: |-
    The first command gets the Application Gateway named ApplicationGateway01 and stores the result in the variable named $AppGW.
    This second command gets a list of SSL certificates from the application gateway stored in the variable named $AppGW.
    The command then stores the results in the variable named $Certs.
  summary: ""
parameters:
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationGateway" data-throw-if-not-resolved="False" />
  name: ApplicationGateway
  isRequired: true
  description: |+
    Specifies the application gateway object that contains the SSL certificate.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  description: |+
    Specifies the name of SSL certificate pool that this cmdlet gets.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Az.Network.Get-AzApplicationGatewaySslCertificate
name: Get-AzApplicationGatewaySslCertificate
description: |-
  The **Get-AzApplicationGatewaySslCertificate** cmdlet gets an SSL certificate for an application gateway.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  Module Name: Az.Network
  ms.assetid: 919B3755-81D4-43FB-AE8C-B071329A61D9
  online version: https://docs.microsoft.com/en-us/powershell/module/az.network/get-azapplicationgatewaysslcertificate
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Get-AzApplicationGatewaySslCertificate.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Get-AzApplicationGatewaySslCertificate.md
