### YamlMime:PowershellCmdlet
summary: |-
  Generates and downloads Vpn profile at VirtualWan-VpnServerConfiguration level for Point to site client setup.
module: Az.Network
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: |-
    Microsoft.Azure.Commands.Network.Models.PSVirtualWan
    Microsoft.Azure.Commands.Network.Models.PSVpnServerConfiguration
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSVpnProfileResponse" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Get-AzVirtualWanVpnServerConfigurationVpnProfile [-Name <String>] -ResourceGroupName <String>

   -VpnServerConfiguration <PSVpnServerConfiguration> [-AuthenticationMethod <String>]

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
- >-
  Get-AzVirtualWanVpnServerConfigurationVpnProfile [-Name <String>] -ResourceGroupName <String>

   -VpnServerConfigurationId <String> [-AuthenticationMethod <String>] [-DefaultProfile <IAzureContextContainer>]

   [<CommonParameters>]
- >-
  Get-AzVirtualWanVpnServerConfigurationVpnProfile -VirtualWanObject <PSVirtualWan>

   -VpnServerConfiguration <PSVpnServerConfiguration> [-AuthenticationMethod <String>]

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
- >-
  Get-AzVirtualWanVpnServerConfigurationVpnProfile -VirtualWanObject <PSVirtualWan>

   -VpnServerConfigurationId <String> [-AuthenticationMethod <String>] [-DefaultProfile <IAzureContextContainer>]

   [<CommonParameters>]
- >-
  Get-AzVirtualWanVpnServerConfigurationVpnProfile -ResourceId <String>

   -VpnServerConfiguration <PSVpnServerConfiguration> [-AuthenticationMethod <String>]

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
- >-
  Get-AzVirtualWanVpnServerConfigurationVpnProfile -ResourceId <String> -VpnServerConfigurationId <String>

   [-AuthenticationMethod <String>] [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    PS C:\> Get-AzVirtualWanVpnServerConfigurationVpnProfile -Name WestUsVirtualWan -ResourceGroupName P2SCortexGATesting -VpnServerConfiguration $vpnServerConfig -AuthenticationMethod EAPTLS

    ProfileUrl : https://nfvprodsuppby.blob.core.windows.net/vpnprofileimmutable/aa316f33-d0f6-4e61-994a-9aa24c0e5f70/vpnprofile/eb99aa3d-1106-49eb-9644-791c045c5cca/vpnclientconfiguration.zip?sv=2017-04-17&sr=b&sig=kZinevNqW
                 qsEAbWAcYiKfUHFxZzh2hwvtb49dfVtUDA%3D&st=2019-10-25T19%3A52%3A36Z&se=2019-10-25T20%3A52%3A36Z&sp=r&fileExtension=.zip
  description: |-
    The above command will generate and returns SAS Url for customer to download the Vpn profile at VirtualWan-VpnServerConfiguration level for Point to site client setup.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: AuthenticationMethod
  description: |+
    Authentication Method

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: EAPTLS, EAPMSCHAPv2
- type: <xref href="IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with Azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Name
  description: |+
    The resource name.

  defaultValue: None
  position: Named
  aliases: ResourceName
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ResourceGroupName
  isRequired: true
  description: |+
    The resource group name.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ResourceId
  isRequired: true
  description: |+
    The Azure resource ID for the virtual wan.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: VirtualWanId
  parameterValueGroup: ""
- type: <xref href="PSVirtualWan" data-throw-if-not-resolved="False" />
  name: VirtualWanObject
  isRequired: true
  description: |+
    The virtual wan object.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: VirtualWan
  parameterValueGroup: ""
- type: <xref href="PSVpnServerConfiguration" data-throw-if-not-resolved="False" />
  name: VpnServerConfiguration
  isRequired: true
  description: |+
    The VpnServerConfiguration with which this VirtualWan is associated.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: VpnServerConfigurationId
  isRequired: true
  description: |+
    The id of Vpn server configuraiton object this Virtual wan will be associated with.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Az.Network.Get-AzVirtualWanVpnServerConfigurationVpnProfile
name: Get-AzVirtualWanVpnServerConfigurationVpnProfile
description: |-
  The **Get-AzVirtualWanVpnServerConfigurationVpnProfile** cmdlet enables you to generate and download the Vpn profile at VirtualWan-VpnServerConfiguration level for Point to site client setup. This is required for Point to site connectivity from Point to site client to Azure P2SVpnGateway.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  Module Name: Az.Network
  online version: https://docs.microsoft.com/en-us/powershell/module/az.network/get-azvirtualwanvpnserverconfigurationvpnprofile
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Get-AzVirtualWanVpnServerConfigurationVpnProfile.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Get-AzVirtualWanVpnServerConfigurationVpnProfile.md
