### YamlMime:PowershellCmdlet
summary: |-
  Creates a new protocol configuration object.
module: Az.Network
notes: |-
  Keywords: azure, azurerm, arm, resource, management, manager, network, networking, watcher, packet, capture, traffic, filter
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSNetworkWatcherProtocolConfiguration" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: New-AzNetworkWatcher
  href: ./New-AzNetworkWatcher.yml
- text: Get-AzNetworkWatcher
  href: ./Get-AzNetworkWatcher.yml
- text: Remove-AzNetworkWatcher
  href: ./Remove-AzNetworkWatcher.yml
- text: Get-AzNetworkWatcherNextHop
  href: ./Get-AzNetworkWatcherNextHop.yml
- text: Get-AzNetworkWatcherSecurityGroupView
  href: ./Get-AzNetworkWatcherSecurityGroupView.yml
- text: Get-AzNetworkWatcherTopology
  href: ./Get-AzNetworkWatcherTopology.yml
- text: Start-AzNetworkWatcherResourceTroubleshooting
  href: ./Start-AzNetworkWatcherResourceTroubleshooting.yml
- text: New-AzNetworkWatcherPacketCapture
  href: ./New-AzNetworkWatcherPacketCapture.yml
- text: New-AzPacketCaptureFilterConfig
  href: ./New-AzPacketCaptureFilterConfig.yml
- text: Get-AzNetworkWatcherPacketCapture
  href: ./Get-AzNetworkWatcherPacketCapture.yml
- text: Remove-AzNetworkWatcherPacketCapture
  href: ./Remove-AzNetworkWatcherPacketCapture.yml
- text: Stop-AzNetworkWatcherPacketCapture
  href: ./Stop-AzNetworkWatcherPacketCapture.yml
- text: New-AzNetworkWatcherProtocolConfiguration
  href: ./New-AzNetworkWatcherProtocolConfiguration.yml
- text: Test-AzNetworkWatcherIPFlow
  href: ./Test-AzNetworkWatcherIPFlow.yml
- text: Test-AzNetworkWatcherConnectivity
  href: ./Test-AzNetworkWatcherConnectivity.yml
- text: Stop-AzNetworkWatcherConnectionMonitor
  href: ./Stop-AzNetworkWatcherConnectionMonitor.yml
- text: Start-AzNetworkWatcherConnectionMonitor
  href: ./Start-AzNetworkWatcherConnectionMonitor.yml
- text: Set-AzNetworkWatcherConnectionMonitor
  href: ./Set-AzNetworkWatcherConnectionMonitor.yml
- text: Set-AzNetworkWatcherConfigFlowLog
  href: ./Set-AzNetworkWatcherConfigFlowLog.yml
- text: Remove-AzNetworkWatcherConnectionMonitor
  href: ./Remove-AzNetworkWatcherConnectionMonitor.yml
- text: New-AzNetworkWatcherConnectionMonitor
  href: ./New-AzNetworkWatcherConnectionMonitor.yml
- text: Get-AzNetworkWatcherTroubleshootingResult
  href: ./Get-AzNetworkWatcherTroubleshootingResult.yml
- text: Get-AzNetworkWatcherReachabilityReport
  href: ./Get-AzNetworkWatcherReachabilityReport.yml
- text: Get-AzNetworkWatcherReachabilityProvidersList
  href: ./Get-AzNetworkWatcherReachabilityProvidersList.yml
- text: Get-AzNetworkWatcherFlowLogStatus
  href: ./Get-AzNetworkWatcherFlowLogStatus.yml
- text: Get-AzNetworkWatcherConnectionMonitorReport
  href: ./Get-AzNetworkWatcherConnectionMonitorReport.yml
- text: Get-AzNetworkWatcherConnectionMonitor
  href: ./Get-AzNetworkWatcherConnectionMonitor.yml
syntaxes:
- >-
  New-AzNetworkWatcherProtocolConfiguration -Protocol <String> [-Method <String>] [-Header <IDictionary>]

   [-ValidStatusCode <Int32[]>] [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
examples:
- title: 'Example 1: Test Network Watcher Connectivity from a VM to a website with protocol configuration'
  code: |-
    $config = New-AzNetworkWatcherProtocolConfiguration -Protocol Http -Method Get -Headers @{"accept"="application/json"} -ValidStatusCodes @(200,202,204)

    Test-AzNetworkWatcherConnectivity -NetworkWatcherName NetworkWatcher -ResourceGroupName NetworkWatcherRG -SourceId "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/ContosoRG/providers/Microsoft.Compute/virtualMachines/MultiTierApp0" -DestinationAddress "bing.com" -DestinationPort 80 -ProtocolConfiguration $config


    ConnectionStatus : Reachable
    AvgLatencyInMs   : 4
    MinLatencyInMs   : 2
    MaxLatencyInMs   : 15
    ProbesSent       : 15
    ProbesFailed     : 0
    Hops             : [
                         {
                           "Type": "Source",
                           "Id": "f8cff464-e13f-457f-a09e-4dcd53d38a85",
                           "Address": "10.1.1.4",
                           "ResourceId": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/ContosoRG/provi                   iders/Microsoft.Network/networkInterfaces/appNic0/ipConfigurations/ipconfig1",
                           "NextHopIds": [
                             "1034b1bf-0b1b-4f0a-93b2-900477f45485"
                           ],
                           "Issues": []
                         },
                         {
                           "Type": "Internet",
                           "Id": "1034b1bf-0b1b-4f0a-93b2-900477f45485",
                           "Address": "13.107.21.200",
                           "ResourceId": "Internet",
                           "NextHopIds": [],
                           "Issues": []
                         }
                       ]
  description: |-
    In this example we test connectivity from a VM in Azure to www.bing.com.
  summary: ""
parameters:
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with Azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.Collections.IDictionary" data-throw-if-not-resolved="False" />
  name: Header
  description: |+
    list of HTTP headers

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Method
  description: |+
    HTTP method

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Protocol
  isRequired: true
  description: |+
    Protocol type

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Int32" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: ValidStatusCode
  description: |+
    valid status codes

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Az.Network.New-AzNetworkWatcherProtocolConfiguration
name: New-AzNetworkWatcherProtocolConfiguration
description: |-
  The New-AzNetworkWatcherProtocolConfiguration cmdlet creates a new protocol configuration object. 
  This object is used to restrict the protocol configuration during a connectivity check session using the specified criteria.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  Module Name: Az.Network
  online version: https://docs.microsoft.com/en-us/powershell/module/az.network/new-aznetworkwatcherprotocolconfiguration
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/New-AzNetworkWatcherProtocolConfiguration.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/New-AzNetworkWatcherProtocolConfiguration.md
