### YamlMime:PowershellCmdlet
summary: |-
  Creates an Ip Configuration to be associated with PrivateLink Configuration
module: Az.Network
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationGatewayPrivateLinkIpConfiguration" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: New-AzApplicationGatewayPrivateLinkConfiguration
  href: ./New-AzApplicationGatewayPrivateLinkConfiguration.yml
syntaxes:
- >-
  New-AzApplicationGatewayPrivateLinkIpConfiguration -Name <String> -Subnet <PSSubnet>

   [-PrivateIpAddressVersion <String>] [-PrivateIpAddress <String>] [-Primary]

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
examples:
- title: 'Example 1: PrivateLink Ip Configuration'
  code: |-
    PS C:\> $PrivateLinkIpConfiguration = New-AzApplicationGatewayPrivateLinkIpConfiguration -Name "ipConfig01" -Subnet $subnet -Primary
  description: |-
    This command creates an PrivateLink IP Configuration named 'ipConfig01' stores the result in the variable named $PrivateLinkIpConfiguration.
  summary: ""
parameters:
- type: <xref href="IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with Azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    The name of the IpConfiguration

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Primary
  description: |+
    Indicate the ip configuration is primary.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: PrivateIpAddress
  description: |+
    The private ip address of the ipConfiguration if static allocation is desired.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: PrivateIpAddressVersion
  description: |+
    The ip version of the ip configuration

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: IPv4
- type: <xref href="PSSubnet" data-throw-if-not-resolved="False" />
  name: Subnet
  isRequired: true
  description: |+
    Subnet

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Az.Network.New-AzApplicationGatewayPrivateLinkIpConfiguration
name: New-AzApplicationGatewayPrivateLinkIpConfiguration
description: |-
  The **New-AzApplicationGatewayPrivateLinkIpConfiguration** cmdlet creates an Ip Configuration to be associated with PrivateLink Configuration for an Azure application gateway.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  Module Name: Az.Network
  online version: https://docs.microsoft.com/en-us/powershell/module/az.network/new-azapplicationgatewayprivatelinkipconfiguration
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/New-AzApplicationGatewayPrivateLinkIpConfiguration.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/New-AzApplicationGatewayPrivateLinkIpConfiguration.md
