### YamlMime:PowershellCmdlet
summary: |-
  Creates a managedRuleOverride entry for RuleGroupOverrideGroup entry.
module: Az.Network
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationGatewayFirewallPolicyManagedRuleOverride" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  New-AzApplicationGatewayFirewallPolicyManagedRuleOverride -RuleId <String> [-State <String>]

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    PS C:\> ruleOverrideEntry = New-AzApplicationGatewayFirewallPolicyManagedRuleOverride -RuleId $ruleId -State Disabled
  description: |-
    Creates a ruleOverride Entry with RuleId as $ruleId and State as Disabled.
  summary: ""
parameters:
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with Azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: RuleId
  isRequired: true
  description: |+
    Specify the RuleId in override rule entry.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: State
  description: |+
    Specify the RuleId in override rule entry.

  defaultValue: Disabled
  position: Named
  aliases: ""
  parameterValueGroup: Disabled
uid: Az.Network.New-AzApplicationGatewayFirewallPolicyManagedRuleOverride
name: New-AzApplicationGatewayFirewallPolicyManagedRuleOverride
description: |-
  The **New-AzApplicationGatewayFirewallPolicyManagedRuleOverride** creates a ruleOverride entry.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  Module Name: Az.Network
  online version: https://docs.microsoft.com/en-us/powershell/module/az.network/new-azapplicationgatewayfirewallpolicymanagedruleoverride
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/New-AzApplicationGatewayFirewallPolicyManagedRuleOverride.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/New-AzApplicationGatewayFirewallPolicyManagedRuleOverride.md
