### YamlMime:PowershellCmdlet
summary: |-
  Creates a network interface IP configuration.
module: Az.Network
notes: |-
  * Keywords: azure, azurerm, arm, resource, management, manager, network, networking
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  description: ""
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSBackendAddressPool" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  description: ""
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSInboundNatRule" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  description: ""
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationGatewayBackendAddressPool" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  description: ""
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationSecurityGroup" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSNetworkInterfaceIPConfiguration" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Add-AzNetworkInterfaceIpConfig
  href: ./Add-AzNetworkInterfaceIpConfig.yml
- text: Get-AzNetworkInterfaceIpConfig
  href: ./Get-AzNetworkInterfaceIpConfig.yml
- text: Remove-AzNetworkInterfaceIpConfig
  href: ./Remove-AzNetworkInterfaceIpConfig.yml
- text: Set-AzNetworkInterfaceIpConfig
  href: ./Set-AzNetworkInterfaceIpConfig.yml
syntaxes:
- >-
  New-AzNetworkInterfaceIpConfig -Name <String> [-PrivateIpAddressVersion <String>] [-PrivateIpAddress <String>]

   [-Primary] [-Subnet <PSSubnet>] [-PublicIpAddress <PSPublicIpAddress>]

   [-LoadBalancerBackendAddressPool <PSBackendAddressPool[]>] [-LoadBalancerInboundNatRule <PSInboundNatRule[]>]

   [-ApplicationGatewayBackendAddressPool <PSApplicationGatewayBackendAddressPool[]>]

   [-ApplicationSecurityGroup <PSApplicationSecurityGroup[]>] [-DefaultProfile <IAzureContextContainer>]

   [<CommonParameters>]
- >-
  New-AzNetworkInterfaceIpConfig -Name <String> [-PrivateIpAddressVersion <String>] [-PrivateIpAddress <String>]

   [-Primary] [-SubnetId <String>] [-PublicIpAddressId <String>] [-LoadBalancerBackendAddressPoolId <String[]>]

   [-LoadBalancerInboundNatRuleId <String[]>] [-ApplicationGatewayBackendAddressPoolId <String[]>]

   [-ApplicationSecurityGroupId <String[]>] [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
examples:
- title: '1: Create an IP configuration with a public IP address for a network interface'
  code: |-
    $vnet = Get-AzVirtualNetwork -Name myvnet -ResourceGroupName myrg
    $Subnet = Get-AzVirtualNetworkSubnetConfig -Name mysubnet -VirtualNetwork $vnet
    $PIP1 = Get-AzPublicIPAddress -Name "PIP1" -ResourceGroupName "RG1"

    $IPConfig1 = New-AzNetworkInterfaceIpConfig -Name "IPConfig-1" -Subnet $Subnet -PublicIpAddress $PIP1
        -Primary

     $nic = New-AzNetworkInterface -Name $NicName -ResourceGroupName myrg -Location westus
        -IpConfiguration $IpConfig1
  description: |-
    The first two commands get a virtual network called myvnet and a subnet called mysubnet respectively that were
        previously created. These are stored in $vnet and $Subnet respectively. The third command gets a previously
        created public IP address called PIP1. The forth command creates a new IP configuration called "IPConfig-1" as the
        primary IP configuration with a public IP address associated with it.
        The last command then creates a network interface called mynic1 using this IP configuration.
  summary: ""
- title: '2: Create an IP configuration with a private IP address'
  code: |-
    $vnet = Get-AzVirtualNetwork -Name myvnet -ResourceGroupName myrg
    $Subnet = Get-AzVirtualNetworkSubnetConfig -Name mysubnet -VirtualNetwork $vnet

    $IPConfig2 = New-AzNetworkInterfaceIpConfig -Name "IP-Config2" -Subnet $Subnet -PrivateIpAddress
        10.0.0.5

    $nic = New-AzNetworkInterface -Name mynic1 -ResourceGroupName myrg -Location westus -IpConfiguration
        $IpConfig2
  description: |-
    The first two commands get a virtual network called myvnet and a subnet called mysubnet respectively that were
        previously created. These are stored in $vnet and $Subnet respectively. The third command creates a new IP
        configuration called "IPConfig-2" with a private IP address 10.0.0.5 associated with it.
        The last command then creates a network interface called mynic1 using this IP configuration.
  summary: ""
parameters:
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationGatewayBackendAddressPool" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: ApplicationGatewayBackendAddressPool
  description: |+
    Specifies a collection of application gateway backend address pool references to which this network interface IP configuration belongs.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: ApplicationGatewayBackendAddressPoolId
  description: |+
    Specifies a collection of application gateway backend address pool references to which this network interface IP configuration belongs.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationSecurityGroup" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: ApplicationSecurityGroup
  description: |+
    Specifies a collection of application security group references to which this network interface IP configuration belongs.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: ApplicationSecurityGroupId
  description: |+
    Specifies a collection of application security group references to which this network interface IP configuration belongs.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSBackendAddressPool" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: LoadBalancerBackendAddressPool
  description: |+
    Specifies a collection of load balancer backend address pool references to which this network interface IP configuration belongs.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: LoadBalancerBackendAddressPoolId
  description: |+
    Specifies a collection of load balancer backend address pool references to which this network interface IP configuration belongs.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSInboundNatRule" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: LoadBalancerInboundNatRule
  description: |+
    Specifies a collection of load balancer inbound Nat Rule references to which this network interface IPConfiguration belongs.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: LoadBalancerInboundNatRuleId
  description: |+
    Specifies a collection of load balancer inbound network address translation (NAT) rule references to which this network interface IP configuration belongs.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    Specifies the name of the network interface IP configuration.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: Primary
  description: ""
  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: PrivateIpAddress
  description: |+
    Specifies the static IP address of the network interface IP configuration.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: PrivateIpAddressVersion
  description: |+
    Specifies the IP address version of a network interface IP configuration.
    The acceptable values for this parameter are:
    - IPv4
    - IPv6

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: IPv4, IPv6
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSPublicIpAddress" data-throw-if-not-resolved="False" />
  name: PublicIpAddress
  description: |+
    Specifies a **PublicIPAddress** object.
    This cmdlet creates a reference to a public IP Address to associate with this network interface IP configuration.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: PublicIpAddressId
  description: |+
    This cmdlet creates a reference to a public IP Address to associate with this network interface IP configuration.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSSubnet" data-throw-if-not-resolved="False" />
  name: Subnet
  description: |+
    Specifies a **Subnet** object.
    This cmdlet creates a reference to a subnet in which this network interface IP configuration is created.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: SubnetId
  description: |+
    Specifies a reference to a subnet in which this network interface IP configuration is created.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Az.Network.New-AzNetworkInterfaceIpConfig
name: New-AzNetworkInterfaceIpConfig
description: |-
  The **New-AzNetworkInterfaceIpConfig** cmdlet creates an Azure network interface IP configuration for a network interface.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  Module Name: Az.Network
  ms.assetid: D29C82CC-2080-48DA-880A-1AA83007E552
  online version: https://docs.microsoft.com/en-us/powershell/module/az.network/new-aznetworkinterfaceipconfig
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/New-AzNetworkInterfaceIpConfig.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/New-AzNetworkInterfaceIpConfig.md
