### YamlMime:PowershellCmdlet
summary: |-
  Creates a match condition for custom rule
module: Az.Network
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationGatewayFirewallCondition" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  New-AzApplicationGatewayFirewallCondition -MatchVariable <PSApplicationGatewayFirewallMatchVariable[]>

   -Operator <String> [-NegationCondition <Boolean>] -MatchValue <String[]> [-Transform <String[]>]

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    PS C:\> $condition = New-AzApplicationGatewayFirewallCondition -MatchVariable $variable -Operator Contains -NegationCondition false -Transforms Lowercase, Trim -MatchValue abc, cde
  description: |-
    The command creates a new match condition using the match variable defined in the $variable, the operator is Contains and negation condition is false, Transfroms including lowercase and trim, the match value is abc and cde. The new match condition is saved in $condition.
  summary: ""
parameters:
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with Azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: MatchValue
  isRequired: true
  description: |+
    Match value.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationGatewayFirewallMatchVariable" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: MatchVariable
  isRequired: true
  description: |+
    List of match variables.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Boolean" data-throw-if-not-resolved="False" />
  name: NegationCondition
  description: |+
    Describes if this is negate condition or not.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Operator
  isRequired: true
  description: |+
    Describes operator to be matched.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: IPMatch, Equal, Contains, LessThan, GreaterThan, LessThanOrEqual, GreaterThanOrEqual, BeginsWith, EndsWith, Regex
- type: <xref href="System.String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: Transform
  description: |+
    List of transforms.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: Lowercase, Trim, UrlDecode, UrlEncode, RemoveNulls, HtmlEntityDecode
uid: Az.Network.New-AzApplicationGatewayFirewallCondition
name: New-AzApplicationGatewayFirewallCondition
description: |-
  The **New-AzApplicationGatewayFirewallCondition** creates a match condition for firewall custom rule.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  Module Name: Az.Network
  online version: https://docs.microsoft.com/en-us/powershell/module/az.network/new-azapplicationgatewayfirewallcondition
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/New-AzApplicationGatewayFirewallCondition.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/New-AzApplicationGatewayFirewallCondition.md
