### YamlMime:PowershellCmdlet
summary: |-
  Creates an IP configuration for an application gateway.
module: Az.Network
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationGatewayIPConfiguration" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Add-AzApplicationGatewayIPConfiguration
  href: ./Add-AzApplicationGatewayIPConfiguration.yml
- text: Get-AzApplicationGatewayIPConfiguration
  href: ./Get-AzApplicationGatewayIPConfiguration.yml
- text: Remove-AzApplicationGatewayIPConfiguration
  href: ./Remove-AzApplicationGatewayIPConfiguration.yml
- text: Set-AzApplicationGatewayIPConfiguration
  href: ./Set-AzApplicationGatewayIPConfiguration.yml
syntaxes:
- >-
  New-AzApplicationGatewayIPConfiguration -Name <String> [-SubnetId <String>]

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
- >-
  New-AzApplicationGatewayIPConfiguration -Name <String> [-Subnet <PSSubnet>]

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
examples:
- title: 'Example 1: Create an IP configuration for an application gateway.'
  code: |-
    PS C:\>$VNet = Get-AzVirtualNetwork -Name "VNet01" -ResourceGroupName "ResourceGroup01"
    PS C:\> $Subnet = Get-AzVirtualNetworkSubnetConfig -Name "Subnet01" -VirtualNetwork $VNet 
    PS C:\ $GatewayIpConfig = New-AzApplicationGatewayIPConfiguration -Name "AppGwSubnet01" -Subnet $Subnet
  description: |-
    The first command gets a virtual network named VNet01 that belongs to the resource group named ResourceGroup01.
    The second command gets the subnet configuration for the subnet that the virtual network in the previous command belongs to, and stores it in the $Subnet variable.
    The third command creates the IP configuration using $Subnet.
  summary: ""
parameters:
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    Specifies the name of the IP configuration to create.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSSubnet" data-throw-if-not-resolved="False" />
  name: Subnet
  description: |+
    Specifies the subnet object.
    This is the subnet in which the application gateway is deployed.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: SubnetId
  description: |+
    Specifies the subnet ID.
    This is the subnet in which the application gateway would be deployed.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Az.Network.New-AzApplicationGatewayIPConfiguration
name: New-AzApplicationGatewayIPConfiguration
description: |-
  The **New-AzApplicationGatewayIPConfiguration** cmdlet creates an IP configuration for an application gateway.
  The IP configuration contains the subnet in which application gateway is deployed.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  Module Name: Az.Network
  ms.assetid: 312AA609-7362-42A5-A889-C0784D5A2943
  online version: https://docs.microsoft.com/en-us/powershell/module/az.network/new-azapplicationgatewayipconfiguration
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/New-AzApplicationGatewayIPConfiguration.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/New-AzApplicationGatewayIPConfiguration.md
