### YamlMime:PowershellCmdlet
summary: |-
  Creates a probe configuration for a load balancer.
module: Az.Network
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="System.Int32" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSProbe" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Add-AzLoadBalancerProbeConfig
  href: ./Add-AzLoadBalancerProbeConfig.yml
- text: Get-AzLoadBalancerProbeConfig
  href: ./Get-AzLoadBalancerProbeConfig.yml
- text: Remove-AzLoadBalancerProbeConfig
  href: ./Remove-AzLoadBalancerProbeConfig.yml
- text: Set-AzLoadBalancerProbeConfig
  href: ./Set-AzLoadBalancerProbeConfig.yml
syntaxes:
- >-
  New-AzLoadBalancerProbeConfig -Name <String> [-Protocol <String>] -Port <Int32> -IntervalInSeconds <Int32>

   -ProbeCount <Int32> [-RequestPath <String>] [-DefaultProfile <IAzureContextContainer>] [-WhatIf] [-Confirm]

   [<CommonParameters>]
examples:
- title: 'Example 1: Create a probe configuration'
  code: |-
    PS C:\>New-AzLoadBalancerProbeConfig -Name "MyProbe" -Protocol "http" -Port 80 -IntervalInSeconds 15 -ProbeCount 15
  description: |-
    This command creates a probe configuration named MyProbe using the HTTP protocol.
    The new probe will connect to a load-balanced service on port 80.
  summary: ""
- title: Example 2
  code: |-
    New-AzLoadBalancerProbeConfig -IntervalInSeconds 15 -Name 'MyProbe' -Port 80 -ProbeCount 15 -Protocol 'http' -RequestPath 'healthcheck.aspx'
  description: ""
  summary: |+
    Creates a probe configuration for a load balancer. (autogenerated)

    <!-- Aladdin Generated Example -->
parameters:
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.Int32" data-throw-if-not-resolved="False" />
  name: IntervalInSeconds
  isRequired: true
  description: |+
    Specifies the interval, in seconds, between probes to each instance of a load-balanced service.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    Specifies the name of the probe configuration to create.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Int32" data-throw-if-not-resolved="False" />
  name: Port
  isRequired: true
  description: |+
    Specifies the port on which the new probe should connect to a load-balanced service.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Int32" data-throw-if-not-resolved="False" />
  name: ProbeCount
  isRequired: true
  description: |+
    Specifies the number of per-instance consecutive failures for an instance to be considered unhealthy.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Protocol
  description: |+
    Specifies the protocol to use for the probe configuration.
    The acceptable values for this parameter are: Tcp or Http.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: RequestPath
  description: |+
    Specifies the path in a load-balanced service to probe to determine health.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs. The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Az.Network.New-AzLoadBalancerProbeConfig
name: New-AzLoadBalancerProbeConfig
description: |-
  The **New-AzLoadBalancerProbeConfig** cmdlet creates a probe configuration for an Azure load balancer.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  Module Name: Az.Network
  ms.assetid: 2049CB74-E3CB-4294-B97C-B41E91209A1E
  online version: https://docs.microsoft.com/en-us/powershell/module/az.network/new-azloadbalancerprobeconfig
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/New-AzLoadBalancerProbeConfig.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/New-AzLoadBalancerProbeConfig.md
