### YamlMime:PowershellCmdlet
summary: |-
  Create a private link service ip configuration.
module: Az.Network
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSPrivateLinkServiceIpConfiguration" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: New-AzPrivateLinkService
  href: ./New-AzPrivateLinkService.yml
syntaxes:
- >-
  New-AzPrivateLinkServiceIpConfig -Name <String> [-PrivateIpAddressVersion <String>]

   [-PrivateIpAddress <String>] [-PublicIpAddress <PSPublicIpAddress>]

   [-Subnet <PSSubnet>] [-Primary]

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    New-AzPrivateLinkServiceIpConfig -Name $IpConfigurationName -PrivateIpAddress "10.0.0.5" -Primary
  description: |-
    This example create a private link service ip configuration in memory.
  summary: ""
- title: Example 2
  code: |-
    New-AzPrivateLinkServiceIpConfig -Name 'IP-Config' -PrivateIpAddress '10.0.0.5' -Subnet <PSSubnet>
  description: ""
  summary: |+
    Create a private link service ip configuration. (autogenerated)

    <!-- Aladdin Generated Example -->
parameters:
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with Azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    The name of the IpConfiguration

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: Primary
  description: |+
    Indicate current ip configuration is primary or not.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: PrivateIpAddress
  description: |+
    The private ip address of the ipConfiguration if static allocation is specified.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: PrivateIpAddressVersion
  description: |+
    The ip version of the ip configuration

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: IPv4, IPv6
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSSubnet" data-throw-if-not-resolved="False" />
  name: Subnet
  description: |+
    Subnet

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Az.Network.New-AzPrivateLinkServiceIpConfig
name: New-AzPrivateLinkServiceIpConfig
description: |-
  The **New-AzPrivateLinkServiceIpConfig** cmdlet creates a private link service ip configuration. This configuration is used for source NAT-ing the incoming traffic from private endpoint.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  Module Name: Az.Network
  online version: https://docs.microsoft.com/en-us/powershell/module/az.network/new-azprivatelinkserviceipconfig
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/New-AzPrivateLinkServiceIpConfig.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/New-AzPrivateLinkServiceIpConfig.md
