### YamlMime:PowershellCmdlet
summary: |-
  Creates a new network configuration diagnostic profile object. 
  This object is used to restrict the network configuration during a diagnostic session using the specified criteria.
module: Az.Network
notes: |-
  Keywords: azure, azurerm, arm, resource, management, manager, network, networking, watcher, diagnostic, profile
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSNetworkConfigurationDiagnosticProfile" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: New-AzNetworkWatcher
  href: ./New-AzNetworkWatcher.yml
- text: Get-AzNetworkWatcher
  href: ./Get-AzNetworkWatcher.yml
- text: Remove-AzNetworkWatcher
  href: ./Remove-AzNetworkWatcher.yml
- text: Get-AzNetworkWatcherNextHop
  href: ./Get-AzNetworkWatcherNextHop.yml
- text: Get-AzNetworkWatcherSecurityGroupView
  href: ./Get-AzNetworkWatcherSecurityGroupView.yml
- text: Get-AzNetworkWatcherTopology
  href: ./Get-AzNetworkWatcherTopology.yml
- text: Start-AzNetworkWatcherResourceTroubleshooting
  href: ./Start-AzNetworkWatcherResourceTroubleshooting.yml
- text: New-AzNetworkWatcherPacketCapture
  href: ./New-AzNetworkWatcherPacketCapture.yml
- text: New-AzPacketCaptureFilterConfig
  href: ./New-AzPacketCaptureFilterConfig.yml
- text: Get-AzNetworkWatcherPacketCapture
  href: ./Get-AzNetworkWatcherPacketCapture.yml
- text: Remove-AzNetworkWatcherPacketCapture
  href: ./Remove-AzNetworkWatcherPacketCapture.yml
- text: Stop-AzNetworkWatcherPacketCapture
  href: ./Stop-AzNetworkWatcherPacketCapture.yml
- text: New-AzNetworkWatcherProtocolConfiguration
  href: ./New-AzNetworkWatcherProtocolConfiguration.yml
- text: Test-AzNetworkWatcherIPFlow
  href: ./Test-AzNetworkWatcherIPFlow.yml
- text: Test-AzNetworkWatcherConnectivity
  href: ./Test-AzNetworkWatcherConnectivity.yml
- text: Stop-AzNetworkWatcherConnectionMonitor
  href: ./Stop-AzNetworkWatcherConnectionMonitor.yml
- text: Start-AzNetworkWatcherConnectionMonitor
  href: ./Start-AzNetworkWatcherConnectionMonitor.yml
- text: Set-AzNetworkWatcherConnectionMonitor
  href: ./Set-AzNetworkWatcherConnectionMonitor.yml
- text: Set-AzNetworkWatcherConfigFlowLog
  href: ./Set-AzNetworkWatcherConfigFlowLog.yml
- text: Remove-AzNetworkWatcherConnectionMonitor
  href: ./Remove-AzNetworkWatcherConnectionMonitor.yml
- text: New-AzNetworkWatcherConnectionMonitor
  href: ./New-AzNetworkWatcherConnectionMonitor.yml
- text: Get-AzNetworkWatcherTroubleshootingResult
  href: ./Get-AzNetworkWatcherTroubleshootingResult.yml
- text: Get-AzNetworkWatcherReachabilityReport
  href: ./Get-AzNetworkWatcherReachabilityReport.yml
- text: Get-AzNetworkWatcherReachabilityProvidersList
  href: ./Get-AzNetworkWatcherReachabilityProvidersList.yml
- text: Get-AzNetworkWatcherFlowLogStatus
  href: ./Get-AzNetworkWatcherFlowLogStatus.yml
- text: Get-AzNetworkWatcherConnectionMonitorReport
  href: ./Get-AzNetworkWatcherConnectionMonitorReport.yml
- text: Get-AzNetworkWatcherConnectionMonitor
  href: ./Get-AzNetworkWatcherConnectionMonitor.yml
syntaxes:
- >-
  New-AzNetworkWatcherNetworkConfigurationDiagnosticProfile -Direction <String> -Protocol <String>

   -Source <String> -Destination <String> -DestinationPort <String> [-DefaultProfile <IAzureContextContainer>]

   [<CommonParameters>]
examples:
- title: 'Example 1: Invoke network configuration diagnostic session for VM and specified network profile'
  code: |-
    PS C:\> $profile = New-AzNetworkWatcherNetworkConfigurationDiagnosticProfile -Direction Inbound -Protocol Tcp -Source 10.1.1.4 -Destination * -DestinationPort 50
    PS C:\> Invoke-AzNetworkWatcherNetworkConfigurationDiagnostic -Location eastus -TargetResourceId /subscriptions/61cc8a98-a8be-4bfe-a04e-0b461f93fe35/resourceGroups/NwRgEastUS/providers/Microsoft.Compute/virtualMachines/vm1 -Profile $profile

    Results : [
                {
                  "Profile": {
                    "Direction": "Inbound",
                    "Protocol": "Tcp",
                    "Source": "10.1.1.4",
                    "Destination": "*",
                    "DestinationPort": "50"
                  },
                  "NetworkSecurityGroupResult": {
                    "SecurityRuleAccessResult": "Allow",
                    "EvaluatedNetworkSecurityGroups": [
                      {
                        "NetworkSecurityGroupId": "/subscriptions/61cc8a98-a8be-4bfe-a04e-0b461f93fe35/resourceGroups/clean
              upservice/providers/Microsoft.Network/networkSecurityGroups/rg-cleanupservice-nsg1",
                        "MatchedRule": {
                          "RuleName": "UserRule_Cleanuptool-Allow-4001",
                          "Action": "Allow"
                        },
                        "RulesEvaluationResult": [
                          {
                            "Name": "UserRule_Cleanuptool-Allow-100",
                            "ProtocolMatched": true,
                            "SourceMatched": false,
                            "SourcePortMatched": true,
                            "DestinationMatched": true,
                            "DestinationPortMatched": false
                          },
  description: ""
  summary: ""
parameters:
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with Azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Destination
  isRequired: true
  description: |+
    Traffic destination.
    Accepted values are: '*', IP Address/CIDR, Service Tag.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: DestinationPort
  isRequired: true
  description: |+
    Traffic destination port.
    Accepted values are '*', port (for example, 3389) and port range (for example, 80-100).

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Direction
  isRequired: true
  description: |+
    The direction of the traffic.
    Accepted values are 'Inbound' and 'Outbound'

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Protocol
  isRequired: true
  description: |+
    Protocol to be verified on.
    Accepted values are '*', TCP, UDP.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Source
  isRequired: true
  description: |+
    Traffic source.
    Accepted values are '*', IP Address/CIDR, Service Tag.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Az.Network.New-AzNetworkWatcherNetworkConfigurationDiagnosticProfile
name: New-AzNetworkWatcherNetworkConfigurationDiagnosticProfile
description: |-
  The New-AzNetworkWatcherNetworkConfigurationDiagnosticProfile cmdlet creates a new diagnostic profile object. 
  This object is used to restrict the network configuration during a network configuration diagnostic session using the specified criteria.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  Module Name: Az.Network
  online version: https://docs.microsoft.com/en-us/powershell/module/az.network/new-aznetworkwatchernetworkconfigurationdiagnosticprofile
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/New-AzNetworkWatcherNetworkConfigurationDiagnosticProfile.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/New-AzNetworkWatcherNetworkConfigurationDiagnosticProfile.md
