### YamlMime:PowershellCmdlet
summary: |-
  Removes URL path mappings to a backend server pool.
module: Az.Network
notes: ""
inputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationGateway" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationGateway" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Add-AzApplicationGatewayUrlPathMapConfig
  href: ./Add-AzApplicationGatewayUrlPathMapConfig.yml
- text: Get-AzApplicationGatewayUrlPathMapConfig
  href: ./Get-AzApplicationGatewayUrlPathMapConfig.yml
- text: New-AzApplicationGatewayUrlPathMapConfig
  href: ./New-AzApplicationGatewayUrlPathMapConfig.yml
- text: Set-AzApplicationGatewayUrlPathMapConfig
  href: ./Set-AzApplicationGatewayUrlPathMapConfig.yml
syntaxes:
- >-
  Remove-AzApplicationGatewayUrlPathMapConfig -Name <String> -ApplicationGateway <PSApplicationGateway>

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
examples:
- title: 'Example 1: Remove an URL path mapping from an application gateway'
  code: |-
    PS C:\> $appgw = Get-AzApplicationGateway -ResourceGroupName "rg" -Name "appGwName"
    PS C:\> $appgw = Remove-AzApplicationGatewayUrlPathMapConfig -ApplicationGateway $appgw -Name "map01"
    PS C:\> $appgw = Set-AzApplicationGateway -ApplicationGateway $appgw
  description: |-
    The first command gets the application gateway named appGwName and stores the result in the $appgw variable.
    The second command removes the URL path mapping named map01 from the application gateway.
    The third command updates the application gateway.
  summary: ""
parameters:
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationGateway" data-throw-if-not-resolved="False" />
  name: ApplicationGateway
  isRequired: true
  description: |+
    Specifies the application gateway to which this cmdlet removes URL path map configuration.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    Specifies the URL path map name that this cmdlet removes from the backend server.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Az.Network.Remove-AzApplicationGatewayUrlPathMapConfig
name: Remove-AzApplicationGatewayUrlPathMapConfig
description: |-
  The **Remove-AzApplicationGatewayUrlPathMapConfig** cmdlet removes URL path mappings to a backend server pool.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  Module Name: Az.Network
  ms.assetid: E43C8D2A-A6B5-4259-94B9-353FBC15F5A8
  online version: https://docs.microsoft.com/en-us/powershell/module/az.network/remove-azapplicationgatewayurlpathmapconfig
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Remove-AzApplicationGatewayUrlPathMapConfig.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Remove-AzApplicationGatewayUrlPathMapConfig.md
