### YamlMime:PowershellCmdlet
summary: |-
  Removes an IP Configuration from a Virtual Network Gateway
module: Az.Network
notes: ""
inputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSVirtualNetworkGateway" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSVirtualNetworkGateway" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Add-AzVirtualNetworkGatewayIpConfig
  href: ./Add-AzVirtualNetworkGatewayIpConfig.yml
- text: New-AzVirtualNetworkGatewayIpConfig
  href: ./New-AzVirtualNetworkGatewayIpConfig.yml
syntaxes:
- >-
  Remove-AzVirtualNetworkGatewayIpConfig -VirtualNetworkGateway <PSVirtualNetworkGateway> -Name <String>

   [-DefaultProfile <IAzureContextContainer>] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: 'Example 1:'
  code: |-
    Remove-AzVirtualNetworkGatewayIpConfig -VirtualNetworkGateway $gateway -Name ActiveActive

    Name                   : myGateway
    ResourceGroupName      : myRG
    Location               : eastus
    Id                     : /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/myRG/providers/Microsoft
                             .Network/virtualNetworkGateways/VNet8GW
    Etag                   : W/"00000000-0000-0000-0000-000000000000"
    ResourceGuid           : 00000000-0000-0000-0000-000000000000
    ProvisioningState      : Succeeded
    Tags                   :
    IpConfigurations       : [
                               {
                                 "PrivateIpAllocationMethod": "Dynamic",
                                 "Subnet": {
                                   "Id": "/subscriptions/800000000-0000-0000-0000-000000000000/resourceGroups/myRG/provid
                             ers/Microsoft.Network/virtualNetworks/VNet8/subnets/GatewaySubnet"
                                 },
                                 "PublicIpAddress": {
                                   "Id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/myRG/provid
                             ers/Microsoft.Network/publicIPAddresses/VNet8GWIP"
                                 },
                                 "Name": "gwipconfig1",
                                 "Etag": "W/\"00000000-0000-0000-0000-000000000000\"",
                                 "Id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/myRG/provider
                             s/Microsoft.Network/virtualNetworkGateways/VNet8GW/ipConfigurations/gwipconfig1"
                               }
                             ]
    GatewayType            : Vpn
    VpnType                : RouteBased
    EnableBgp              : False
    ActiveActive           : True
    GatewayDefaultSite     : null
    Sku                    : {
                               "Capacity": 2,
                               "Name": "VpnGw1",
                               "Tier": "VpnGw1"
                             }
    VpnClientConfiguration : null
    BgpSettings            : {
                               "Asn": 65515,
                               "BgpPeeringAddress": "192.0.2.4,192.0.2.5",
                               "PeerWeight": 0
                             }
  description: ""
  summary: ""
parameters:
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: ""
  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSVirtualNetworkGateway" data-throw-if-not-resolved="False" />
  name: VirtualNetworkGateway
  isRequired: true
  description: ""
  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Az.Network.Remove-AzVirtualNetworkGatewayIpConfig
name: Remove-AzVirtualNetworkGatewayIpConfig
description: |-
  Removes an IP Configuration from a Virtual Network Gateway
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  Module Name: Az.Network
  ms.assetid: 60DA2175-7970-410C-A13C-B1314716AD8A
  online version: https://docs.microsoft.com/en-us/powershell/module/az.network/remove-azvirtualnetworkgatewayipconfig
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Remove-AzVirtualNetworkGatewayIpConfig.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Remove-AzVirtualNetworkGatewayIpConfig.md
