### YamlMime:PowershellCmdlet
summary: |-
  Removes a subnet configuration from a virtual network.
module: Az.Network
notes: ""
inputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSVirtualNetwork" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSVirtualNetwork" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Add-AzVirtualNetworkSubnetConfig
  href: ./Add-AzVirtualNetworkSubnetConfig.yml
- text: Get-AzVirtualNetworkSubnetConfig
  href: ./Get-AzVirtualNetworkSubnetConfig.yml
- text: New-AzVirtualNetworkSubnetConfig
  href: ./New-AzVirtualNetworkSubnetConfig.yml
- text: Set-AzVirtualNetworkSubnetConfig
  href: ./Set-AzVirtualNetworkSubnetConfig.yml
syntaxes:
- >-
  Remove-AzVirtualNetworkSubnetConfig [-Name <String>] -VirtualNetwork <PSVirtualNetwork>

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
examples:
- title: '1: Remove a subnet from a virtual network and update the virtual network'
  code: |-
    New-AzResourceGroup -Name TestResourceGroup -Location centralus
        $frontendSubnet = New-AzVirtualNetworkSubnetConfig -Name frontendSubnet 
        -AddressPrefix "10.0.1.0/24"

    $backendSubnet = New-AzVirtualNetworkSubnetConfig -Name backendSubnet -AddressPrefix 
        "10.0.2.0/24"

    $virtualNetwork = New-AzVirtualNetwork -Name MyVirtualNetwork -ResourceGroupName 
        TestResourceGroup -Location centralus -AddressPrefix "10.0.0.0/16" -Subnet 
        $frontendSubnet,$backendSubnet

    Remove-AzVirtualNetworkSubnetConfig -Name backendSubnet -VirtualNetwork 
        $virtualNetwork
        $virtualNetwork | Set-AzVirtualNetwork
  description: |-
    This example creates a resource group and a virtual network with two subnets. It then 
        uses the Remove-AzVirtualNetworkSubnetConfig command to remove the backend subnet 
        from the in-memory representation of the virtual network. Set-AzVirtualNetwork is 
        then called to modify the virtual network on the server side.
  summary: ""
parameters:
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  description: |+
    Specifies the name of the subnet configuration to remove.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSVirtualNetwork" data-throw-if-not-resolved="False" />
  name: VirtualNetwork
  isRequired: true
  description: |+
    Specifies the **VirtualNetwork** object that contains the subnet configuration to remove.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Az.Network.Remove-AzVirtualNetworkSubnetConfig
name: Remove-AzVirtualNetworkSubnetConfig
description: |-
  The **Remove-AzVirtualNetworkSubnetConfig** cmdlet removes a subnet from an Azure virtual network.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  Module Name: Az.Network
  ms.assetid: 47FE9EF4-6000-4096-8F04-26A0C6661FDB
  online version: https://docs.microsoft.com/en-us/powershell/module/az.network/remove-azvirtualnetworksubnetconfig
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Remove-AzVirtualNetworkSubnetConfig.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Remove-AzVirtualNetworkSubnetConfig.md
