### YamlMime:PowershellCmdlet
summary: |-
  Updates a rule configuration for a load balancer.
module: Az.Network
notes: ""
inputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSLoadBalancer" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="System.Int32" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSFrontendIPConfiguration" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSBackendAddressPool" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSProbe" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSLoadBalancer" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Add-AzLoadBalancerRuleConfig
  href: ./Add-AzLoadBalancerRuleConfig.yml
- text: Add-AzLoadBalancerRuleConfig
  href: ./Add-AzLoadBalancerRuleConfig.yml
- text: Get-AzLoadBalancerRuleConfig
  href: ./Get-AzLoadBalancerRuleConfig.yml
- text: New-AzLoadBalancerRuleConfig
  href: ./New-AzLoadBalancerRuleConfig.yml
- text: Remove-AzLoadBalancerRuleConfig
  href: ./Remove-AzLoadBalancerRuleConfig.yml
syntaxes:
- >-
  Set-AzLoadBalancerRuleConfig -LoadBalancer <PSLoadBalancer> -Name <String> [-Protocol <String>]

   [-LoadDistribution <String>] [-FrontendPort <Int32>] [-BackendPort <Int32>] [-IdleTimeoutInMinutes <Int32>]

   [-EnableFloatingIP] [-EnableTcpReset] [-DisableOutboundSNAT]

   [-FrontendIpConfiguration <PSFrontendIPConfiguration>] [-BackendAddressPool <PSBackendAddressPool>]

   [-Probe <PSProbe>] [-DefaultProfile <IAzureContextContainer>] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Set-AzLoadBalancerRuleConfig -LoadBalancer <PSLoadBalancer> -Name <String> [-Protocol <String>]

   [-LoadDistribution <String>] [-FrontendPort <Int32>] [-BackendPort <Int32>] [-IdleTimeoutInMinutes <Int32>]

   [-EnableFloatingIP] [-EnableTcpReset] [-DisableOutboundSNAT] [-FrontendIpConfigurationId <String>]

   [-BackendAddressPoolId <String>] [-ProbeId <String>] [-DefaultProfile <IAzureContextContainer>] [-WhatIf]

   [-Confirm] [<CommonParameters>]
examples:
- title: 'Example 1: Modify a load balancing rule configuration'
  code: |-
    PS C:\>$slb = Get-AzLoadBalancer -Name "MyLoadBalancer" -ResourceGroupName "MyResourceGroup"
    PS C:\> $slb | Add-AzLoadBalancerRuleConfig -Name "NewRule" -FrontendIPConfiguration $slb.FrontendIpConfigurations[0] -Protocol "Tcp" -FrontendPort 3350 -BackendPort 3350 -EnableFloatingIP
    PS C:\> $slb | Set-AzLoadBalancerRuleConfig -Name "NewRule" -FrontendIPConfiguration $slb.FrontendIpConfigurations[0] -Protocol "Tcp" -FrontendPort 3350 -BackendPort 3350
    PS C:\> $slb | Set-AzLoadBalancer
  description: |-
    The first command gets the load balancer named MyLoadBalancer, and then stores it in the $slb variable.
    The second command uses the pipeline operator to pass the load balancer in $slb to Add-AzLoadBalancerRuleConfig, which adds a rule named NewRule to it.
    The third command passes the load balancer to **Set-AzLoadBalancerRuleConfig**, which sets the new rule configuration.
    Note that the configuration does not enable a floating IP address, which had been enabled by the previous command.
  summary: ""
parameters:
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSBackendAddressPool" data-throw-if-not-resolved="False" />
  name: BackendAddressPool
  description: |+
    Specifies a **BackendAddressPool** object to associate with a load balancer rule.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: BackendAddressPoolId
  description: |+
    Specifies the ID of a **BackendAddressPool** object to associate with a load balancer rule configuration.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Int32" data-throw-if-not-resolved="False" />
  name: BackendPort
  description: |+
    Specifies the backend port for traffic that is matched by this rule configuration.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: DisableOutboundSNAT
  description: |+
    Configures SNAT for the VMs in the backend pool to use the publicIP address specified in the frontend of the load balancing rule.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: EnableFloatingIP
  description: |+
    Indicates that this cmdlet enables a floating IP address for a rule configuration.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: EnableTcpReset
  description: |+
    Receive bidirectional TCP Reset on TCP flow idle timeout or unexpected connection termination. This element is only used when the protocol is set to TCP.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSFrontendIPConfiguration" data-throw-if-not-resolved="False" />
  name: FrontendIpConfiguration
  description: |+
    Specifies a list of front-end IP addresses to associate with a load balancer rule configuration.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: FrontendIpConfigurationId
  description: |+
    Specifies the ID for a front-end IP address configuration.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Int32" data-throw-if-not-resolved="False" />
  name: FrontendPort
  description: |+
    Specifies the front-end port that is matched by a load balancer rule configuration.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Int32" data-throw-if-not-resolved="False" />
  name: IdleTimeoutInMinutes
  description: |+
    Specifies the length of time, in minutes, for which the state of conversations is maintained in a load balancer.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSLoadBalancer" data-throw-if-not-resolved="False" />
  name: LoadBalancer
  isRequired: true
  description: |+
    Specifies a load balancer.
    This cmdlet updates a rule configuration for the load balancer that this parameter specifies.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: LoadDistribution
  description: |+
    Specifies a load distribution.
    The acceptable values for this parameter are: SourceIP and SourceIPProtocol.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    Specifies the name of a load balancer.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSProbe" data-throw-if-not-resolved="False" />
  name: Probe
  description: |+
    Specifies a probe to associate with a load balancer rule configuration.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: ProbeId
  description: |+
    Specifies the ID of the probe to associate with a load balancer rule configuration.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Protocol
  description: |+
    Specifies the protocol that is matched by a load balancer rule.
    The acceptable values for this parameter are: Tcp or Udp.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs. The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Az.Network.Set-AzLoadBalancerRuleConfig
name: Set-AzLoadBalancerRuleConfig
description: |-
  The **Set-AzLoadBalancerRuleConfig** cmdlet updates a rule configuration for a load balancer.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  Module Name: Az.Network
  ms.assetid: 2638B226-B974-43B6-ACC2-D67573CF6B56
  online version: https://docs.microsoft.com/en-us/powershell/module/az.network/set-azloadbalancerruleconfig
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Set-AzLoadBalancerRuleConfig.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Set-AzLoadBalancerRuleConfig.md
