### YamlMime:PowershellCmdlet
summary: |-
  Sets the health probe configuration on an existing Application Gateway.
module: Az.Network
notes: ""
inputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationGateway" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationGateway" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Add-AzApplicationGatewayProbeConfig
  href: ./Add-AzApplicationGatewayProbeConfig.yml
- text: Get-AzApplicationGatewayProbeConfig
  href: ./Get-AzApplicationGatewayProbeConfig.yml
- text: New-AzApplicationGatewayProbeConfig
  href: ./New-AzApplicationGatewayProbeConfig.yml
- text: Remove-AzApplicationGatewayProbeConfig
  href: ./Remove-AzApplicationGatewayProbeConfig.yml
syntaxes:
- >-
  Set-AzApplicationGatewayProbeConfig -ApplicationGateway <PSApplicationGateway> -Name <String>

   -Protocol <String> [-HostName <String>] -Path <String> -Interval <Int32> -Timeout <Int32>

   -UnhealthyThreshold <Int32> [-PickHostNameFromBackendHttpSettings] [-MinServers <Int32>]

   [-Match <PSApplicationGatewayProbeHealthResponseMatch>] [-DefaultProfile <IAzureContextContainer>]

   [<CommonParameters>]
examples:
- title: 'Example 1: Set the configuration for a health probe on an application gateway'
  code: |-
    PS C:\>Set-AzApplicationGatewayProbeConfig -ApplicationGateway Gateway -Name "Probe05" -Protocol Http -HostName "contoso.com" -Path "/path/custompath.htm" -Interval 30 -Timeout 120 -UnhealthyThreshold 8
  description: |-
    This command sets the configuration for a health probe named Probe05 for the application gateway named Gateway.
    The command also sets the unhealthy threshold to 8 retries and times out after 120 seconds.
  summary: ""
- title: Example 2
  code: |-
    Set-AzApplicationGatewayProbeConfig -ApplicationGateway Gateway -Interval 30 -Match <PSApplicationGatewayProbeHealthResponseMatch> -Name 'Probe05' -Path '/path/custompath.htm' -PickHostNameFromBackendHttpSettings -Protocol https -Timeout 120 -UnhealthyThreshold 8
  description: ""
  summary: |+
    Sets the health probe configuration on an existing Application Gateway. (autogenerated)

    <!-- Aladdin Generated Example -->
parameters:
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationGateway" data-throw-if-not-resolved="False" />
  name: ApplicationGateway
  isRequired: true
  description: |+
    Specifies the application gateway to which this cmdlet sends a probe.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: HostName
  description: |+
    Specifies the host name that this cmdlet sends the probe to.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Int32" data-throw-if-not-resolved="False" />
  name: Interval
  isRequired: true
  description: |+
    Specifies the probe interval in seconds.
    This is the time interval between two consecutive probes.
    This value is between 1 second and 86400 seconds.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationGatewayProbeHealthResponseMatch" data-throw-if-not-resolved="False" />
  name: Match
  description: |+
    Body that must be contained in the health response.
    Default value is empty

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Int32" data-throw-if-not-resolved="False" />
  name: MinServers
  description: |+
    Minimum number of servers that are always marked healthy.
    Default value is 0

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    Specifies the name of the probe.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Path
  isRequired: true
  description: |+
    Specifies the relative path of probe.
    Valid paths start with the slash character (/).
    The probe is sent to \<Protocol\>://\<host\>:\<port\>\<path\>.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: PickHostNameFromBackendHttpSettings
  description: |+
    Whether the host header should be picked from the backend http settings.
    Default value is false

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Protocol
  isRequired: true
  description: |+
    Specifies the protocol used to send probe.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: Http, Https
- type: <xref href="System.Int32" data-throw-if-not-resolved="False" />
  name: Timeout
  isRequired: true
  description: |+
    Specifies the probe timeout in seconds.
    This cmdlet marks the probe as failed if a valid response is not received with this timeout period.
    Valid values are between 1 second and 86400 seconds.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Int32" data-throw-if-not-resolved="False" />
  name: UnhealthyThreshold
  isRequired: true
  description: |+
    Specifies the probe retry count.
    The backend server is marked down after consecutive probe failure count reaches the unhealthy threshold.
    Valid values are between 1 second and 20 seconds.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Az.Network.Set-AzApplicationGatewayProbeConfig
name: Set-AzApplicationGatewayProbeConfig
description: |-
  The Set-AzApplicationGatewayProbeConfig cmdlet sets the health probe configuration on an existing Application Gateway.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  Module Name: Az.Network
  online version: https://docs.microsoft.com/en-us/powershell/module/az.network/set-azapplicationgatewayprobeconfig
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Set-AzApplicationGatewayProbeConfig.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Set-AzApplicationGatewayProbeConfig.md
