### YamlMime:PowershellCmdlet
summary: |-
  Updates a configuration of a server.
  Use Update-AzMariaDbServer instead if you want update AdministratorLoginPassword, sku, etc.
module: Az.MariaDb
notes: |-
  ALIASES

  COMPLEX PARAMETER PROPERTIES

  To create the parameters described below, construct a hash table containing the appropriate properties. For information on hash tables, run Get-Help about_Hash_Tables.


  INPUTOBJECT <IMariaDbIdentity>: Identity Parameter
    - `[ConfigurationName <String>]`: The name of the server configuration.
    - `[DatabaseName <String>]`: The name of the database.
    - `[FirewallRuleName <String>]`: The name of the server firewall rule.
    - `[Id <String>]`: Resource identity path
    - `[LocationName <String>]`: The name of the location.
    - `[ResourceGroupName <String>]`: The name of the resource group that contains the resource. You can obtain this value from the Azure Resource Manager API or the portal.
    - `[SecurityAlertPolicyName <SecurityAlertPolicyName?>]`: The name of the security alert policy.
    - `[ServerName <String>]`: The name of the server.
    - `[SubscriptionId <String>]`: The subscription ID that identifies an Azure subscription.
    - `[VirtualNetworkRuleName <String>]`: The name of the virtual network rule.
inputs:
- name: <xref href="Microsoft.Azure.PowerShell.Cmdlets.MariaDb.Models.IMariaDbIdentity" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.PowerShell.Cmdlets.MariaDb.Models.Api20180601Preview.IConfiguration" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Update-AzMariaDbConfiguration -Name <String> -ResourceGroupName <String> -ServerName <String>

   [-SubscriptionId <String>] [-Source <String>] [-Value <String>] [-DefaultProfile <PSObject>] [-AsJob]

   [-NoWait] [-Confirm] [-WhatIf] [<CommonParameters>]
- >-
  Update-AzMariaDbConfiguration -InputObject <IMariaDbIdentity> [-Source <String>] [-Value <String>]

   [-DefaultProfile <PSObject>] [-AsJob] [-NoWait] [-Confirm] [-WhatIf] [<CommonParameters>]
examples:
- title: 'Example 1: Update MariaDB configuration'
  code: |-
    PS C:\> Update-AzMariaDbConfiguration -Name delayed_insert_timeout -Value 200 -ServerName mariadb-test-h3pame -ResourceGroupName mariadb-test-qu5ov0 

    Name                   Type
    ----                   ----
    delayed_insert_timeout Microsoft.DBforMariaDB/servers/configurations
  description: |-
    This command updates a MariaDB configuration.
  summary: ""
parameters:
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: AsJob
  description: |+
    Run the command as a job

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.PSObject" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with Azure.

  defaultValue: None
  position: Named
  aliases: AzureRMContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.PowerShell.Cmdlets.MariaDb.Models.IMariaDbIdentity" data-throw-if-not-resolved="False" />
  name: InputObject
  isRequired: true
  description: |+
    Identity Parameter
    To construct, see NOTES section for INPUTOBJECT properties and create a hash table.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    The name of the server configuration.

  defaultValue: None
  position: Named
  aliases: ConfigurationName
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: NoWait
  description: |+
    Run the command asynchronously

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: ResourceGroupName
  isRequired: true
  description: |+
    The name of the resource group that contains the resource.
    You can obtain this value from the Azure Resource Manager API or the portal.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: ServerName
  isRequired: true
  description: |+
    The name of the server.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Source
  description: |+
    Source of the configuration.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: SubscriptionId
  description: |+
    The subscription ID that identifies an Azure subscription.

  defaultValue: (Get-AzContext).Subscription.Id
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Value
  description: |+
    Value of the configuration.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Az.MariaDb.Update-AzMariaDbConfiguration
name: Update-AzMariaDbConfiguration
description: |-
  Updates a configuration of a server.
  Use Update-AzMariaDberver instead if you want update AdministratorLoginPassword, sku, etc.
metadata:
  external help file: ""
  Module Name: Az.MariaDb
  online version: https://docs.microsoft.com/en-us/powershell/module/az.mariadb/update-azmariadbconfiguration
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/MariaDb/help/Update-AzMariaDbConfiguration.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/MariaDb/help/Update-AzMariaDbConfiguration.md
