### YamlMime:PowershellCmdlet
summary: |-
  Update an applicationGroup.
module: Az.DesktopVirtualization
notes: |-
  ALIASES

  COMPLEX PARAMETER PROPERTIES

  To create the parameters described below, construct a hash table containing the appropriate properties. For information on hash tables, run Get-Help about_Hash_Tables.


  INPUTOBJECT <IDesktopVirtualizationIdentity>: Identity Parameter
    - `[ApplicationGroupName <String>]`: The name of the application group
    - `[ApplicationName <String>]`: The name of the application within the specified application group
    - `[DesktopName <String>]`: The name of the desktop within the specified desktop group
    - `[HostPoolName <String>]`: The name of the host pool within the specified resource group
    - `[Id <String>]`: Resource identity path
    - `[ResourceGroupName <String>]`: The name of the resource group. The name is case insensitive.
    - `[SessionHostName <String>]`: The name of the session host within the specified host pool
    - `[SubscriptionId <String>]`: The ID of the target subscription.
    - `[UserSessionId <String>]`: The name of the user session within the specified session host
    - `[WorkspaceName <String>]`: The name of the workspace
inputs:
- name: <xref href="Microsoft.Azure.PowerShell.Cmdlets.DesktopVirtualization.Models.IDesktopVirtualizationIdentity" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.PowerShell.Cmdlets.DesktopVirtualization.Models.Api20191210Preview.IApplicationGroup" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Update-AzWvdApplicationGroup -Name <String> -ResourceGroupName <String> [-SubscriptionId <String>]

   [-Description <String>] [-FriendlyName <String>] [-Tag <Hashtable>] [-DefaultProfile <PSObject>] [-Confirm]

   [-WhatIf] [<CommonParameters>]
- >-
  Update-AzWvdApplicationGroup -InputObject <IDesktopVirtualizationIdentity> [-Description <String>]

   [-FriendlyName <String>] [-Tag <Hashtable>] [-DefaultProfile <PSObject>] [-Confirm] [-WhatIf]

   [<CommonParameters>]
examples:
- title: 'Example 1: Create a Windows Virtual Desktop ApplicationGroup by name'
  code: |-
    PS C:\> New-AzWvdApplicationGroup -ResourceGroupName ResourceGroupName `
                                -Name ApplicationGroupName `
                                -FriendlyName 'Friendly Name' `
                                -Description 'Description' `

    Location   Name                 Type
    --------   ----                 ----
    eastus     ApplicationGroupName Microsoft.DesktopVirtualization/applicationgroups
  description: |-
    This command creates a Windows Virtual Desktop ApplicationGroup in a Resource Group.
  summary: ""
parameters:
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.PSObject" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with Azure.

  defaultValue: None
  position: Named
  aliases: AzureRMContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Description
  description: |+
    Description of ApplicationGroup.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: FriendlyName
  description: |+
    Friendly name of ApplicationGroup.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.PowerShell.Cmdlets.DesktopVirtualization.Models.IDesktopVirtualizationIdentity" data-throw-if-not-resolved="False" />
  name: InputObject
  isRequired: true
  description: |+
    Identity Parameter
    To construct, see NOTES section for INPUTOBJECT properties and create a hash table.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    The name of the application group

  defaultValue: None
  position: Named
  aliases: ApplicationGroupName
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: ResourceGroupName
  isRequired: true
  description: |+
    The name of the resource group.
    The name is case insensitive.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: SubscriptionId
  description: |+
    The ID of the target subscription.

  defaultValue: (Get-AzContext).Subscription.Id
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Hashtable" data-throw-if-not-resolved="False" />
  name: Tag
  description: |+
    tags to be updated

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Az.DesktopVirtualization.Update-AzWvdApplicationGroup
name: Update-AzWvdApplicationGroup
description: |-
  Update an applicationGroup.
metadata:
  external help file: ""
  Module Name: Az.DesktopVirtualization
  online version: https://docs.microsoft.com/en-us/powershell/module/az.desktopvirtualization/update-azwvdapplicationgroup
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/DesktopVirtualization/help/Update-AzWvdApplicationGroup.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/DesktopVirtualization/help/Update-AzWvdApplicationGroup.md
