### YamlMime:PowershellCmdlet
summary: |-
  Creates a local configuration object for a container service.
module: Az.Compute
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="System.Collections.Hashtable" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="System.Nullable`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Azure.Management.Compute.Models.ContainerServiceOrchestratorTypes, Microsoft.Azure.Management.Compute, Version=23.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" data-throw-if-not-resolved="False" /><span>]</span><span>]</span>
  description: ""
- name: <xref href="System.Int32" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Azure.Management.Compute.Models.ContainerServiceAgentPoolProfile" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  description: ""
- name: <xref href="System.String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  description: ""
- name: <xref href="System.Boolean" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Compute.Automation.Models.PSContainerService" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Add-AzContainerServiceAgentPoolProfile
  href: ./Add-AzContainerServiceAgentPoolProfile.yml
- text: New-AzContainerService
  href: ./New-AzContainerService.yml
syntaxes:
- >-
  New-AzContainerServiceConfig [[-Location] <String>] [[-Tag] <Hashtable>]

   [[-OrchestratorType] <ContainerServiceOrchestratorTypes>] [[-MasterCount] <Int32>]

   [[-MasterDnsPrefix] <String>] [[-AgentPoolProfile] <ContainerServiceAgentPoolProfile[]>]

   [[-WindowsProfileAdminUsername] <String>] [[-WindowsProfileAdminPassword] <String>]

   [[-AdminUsername] <String>] [[-SshPublicKey] <String[]>] [[-VmDiagnosticsEnabled] <Boolean>]

   [-CustomProfileOrchestrator <String>] [-ServicePrincipalProfileClientId <String>]

   [-ServicePrincipalProfileSecret <String>] [-DefaultProfile <IAzureContextContainer>] [-WhatIf] [-Confirm]

   [<CommonParameters>]
examples:
- title: 'Example 1: Create a container service configuration'
  code: |-
    PS C:\> $Container = New-AzContainerServiceConfig -Location "Australia Southeast" -OrchestratorType "DCOS" -MasterDnsPrefix "MasterResourceGroup17" -AdminUsername "AcsLinuxAdmin" -SshPublicKey "<ssh-key>"
    PS C:\> $Container | Add-AzContainerServiceAgentPoolProfile -Name "AgentPool01" -VmSize "Standard_A1" -DnsPrefix "APResourceGroup17"
  description: |-
    This command creates a container, and then stores it in the $Container variable.
    The command specifies various settings for the container service configuration. The command passes
    the configuration object to the Add-AzContainerServiceAgentPoolProfile cmdlet by using the
    pipeline operator. That cmdlet adds an agent pool profile.
    Specify the object in $Container for the *ContainerService* parameter of **New-AzContainerService**.
  summary: ""
parameters:
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: AdminUsername
  description: |+
    Specifies the administrator account name to use for a Linux-based container service.

  defaultValue: None
  pipelineInput: true
  position: "8"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Management.Compute.Models.ContainerServiceAgentPoolProfile" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: AgentPoolProfile
  description: |+
    Specifies an array of agent pool profile objects for the container service.
    Add a profile by using the Add-AzContainerServiceAgentPoolProfile cmdlet.

  defaultValue: None
  pipelineInput: true
  position: "5"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: CustomProfileOrchestrator
  description: |+
    Specifies the custom profile orchestrator.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Location
  description: |+
    Specifies the location in which to create the container service.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Int32" data-throw-if-not-resolved="False" />
  name: MasterCount
  description: |+
    Specifies the number of master virtual machines to create.

  defaultValue: None
  pipelineInput: true
  position: "3"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: MasterDnsPrefix
  description: |+
    Specifies the DNS prefix for the master virtual machine.

  defaultValue: None
  pipelineInput: true
  position: "4"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Nullable`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Azure.Management.Compute.Models.ContainerServiceOrchestratorTypes" data-throw-if-not-resolved="False" /><span>]</span>
  name: OrchestratorType
  description: |+
    Specifies the type of orchestrator for the container service.
    The acceptable values for this parameter are: DCOS and Swarm.

  defaultValue: None
  pipelineInput: true
  position: "2"
  aliases: ""
  parameterValueGroup: Swarm, DCOS, Custom, Kubernetes
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: ServicePrincipalProfileClientId
  description: |+
    Specifies the principal profile client ID.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: ServicePrincipalProfileSecret
  description: |+
    Specifies the principal profile secret.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: SshPublicKey
  description: |+
    Specifies the SSH public key for a Linux-based container service.

  defaultValue: None
  pipelineInput: true
  position: "9"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Hashtable" data-throw-if-not-resolved="False" />
  name: Tag
  description: |+
    Key-value pairs in the form of a hash table. For example:
    @{key0="value0";key1=$null;key2="value2"}

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Boolean" data-throw-if-not-resolved="False" />
  name: VmDiagnosticsEnabled
  description: |+
    Indicates whether this configuration enables diagnostics for the container service virtual machine.

  defaultValue: None
  pipelineInput: true
  position: "10"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs. The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: WindowsProfileAdminPassword
  description: |+
    Specifies the administrator password for a container service that uses the Windows operating system.

  defaultValue: None
  pipelineInput: true
  position: "7"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: WindowsProfileAdminUsername
  description: |+
    Specifies the administrator username for a container service that uses the Windows operating system.

  defaultValue: None
  pipelineInput: true
  position: "6"
  aliases: ""
  parameterValueGroup: ""
uid: Az.Compute.New-AzContainerServiceConfig
name: New-AzContainerServiceConfig
description: |-
  The **New-AzContainerServiceConfig** cmdlet creates a local configuration object for a container service.
  Provide this object to the New-AzContainerService cmdlet to create a container service.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Compute.dll-Help.xml
  Module Name: Az.Compute
  ms.assetid: EC8C915A-A0BC-41DE-9DBF-3617536E3D1A
  online version: https://docs.microsoft.com/en-us/powershell/module/az.compute/new-azcontainerserviceconfig
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Compute/Compute/help/New-AzContainerServiceConfig.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Compute/Compute/help/New-AzContainerServiceConfig.md
