### YamlMime:PowershellCmdlet
summary: |-
  Uploads a DSC script to Azure blob storage.
module: Az.Compute
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="System.String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  description: ""
outputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-AzVMDscExtension
  href: ./Get-AzVMDscExtension.yml
- text: Remove-AzVMDscExtension
  href: ./Remove-AzVMDscExtension.yml
- text: Set-AzVMDscExtension
  href: ./Set-AzVMDscExtension.yml
syntaxes:
- >-
  Publish-AzVMDscConfiguration [-ResourceGroupName] <String> [-ConfigurationPath] <String>

   [[-ContainerName] <String>] [-StorageAccountName] <String> [-StorageEndpointSuffix <String>] [-Force]

   [-SkipDependencyDetection] [-ConfigurationDataPath <String>] [-AdditionalPath <String[]>]

   [-DefaultProfile <IAzureContextContainer>] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Publish-AzVMDscConfiguration [-ConfigurationPath] <String> [[-OutputArchivePath] <String>] [-Force]

   [-SkipDependencyDetection] [-ConfigurationDataPath <String>] [-AdditionalPath <String[]>]

   [-DefaultProfile <IAzureContextContainer>] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: 'Example 1: Create a .zip package an upload it to Azure storage'
  code: |-
    PS C:\> Publish-AzVMDscConfiguration ".\MyConfiguration.ps1"
  description: |-
    This command creates a .zip package for the given script and any dependent resource modules and uploads it to Azure storage.
  summary: ""
- title: 'Example 2: Create a .zip package and store it to a local file'
  code: |-
    PS C:\> Publish-AzVMDscConfiguration ".\MyConfiguration.ps1" -OutputArchivePath ".\MyConfiguration.ps1.zip"
  description: |-
    This command creates a .zip package for the given script and any dependent resource modules and stores it in the local file that is named .\MyConfiguration.ps1.zip.
  summary: ""
- title: 'Example 3: Add configuration to the archive and then upload it to storage'
  code: |-
    PS C:\> Publish-AzVMDscConfiguration -ConfigurationPath "C:\Sample.ps1" -SkipDependencyDetection
  description: |-
    This command adds configuration named Sample.ps1 to the configuration archive to upload to Azure storage and skips dependent resource modules.
  summary: ""
- title: 'Example 4: Add configuration and configuration data to the archive and then upload it to storage'
  code: |-
    PS C:\> Publish-AzVMDscConfiguration -ConfigurationPath "C:\Sample.ps1" -ConfigurationDataPath "C:\SampleData.psd1"
  description: |-
    This command adds configuration named Sample.ps1 and configuration data named SampleData.psd1 to the configuration archive to upload to Azure storage.
  summary: ""
- title: 'Example 5: Add configuration, configuration data, and additional content to the archive and then upload it to storage'
  code: |-
    PS C:\> Publish-AzVMDscConfiguration -ConfigurationPath "C:\Sample.ps1" -AdditionalPath @("C:\ContentDir1", "C:\File.txt") -ConfigurationDataPath "C:\SampleData.psd1"
  description: |-
    This command adds configuration named Sample.ps1, configuration data SampleData.psd1, and additional content to configuration archive to upload to Azure storage.
  summary: ""
parameters:
- type: <xref href="System.String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: AdditionalPath
  description: |+
    Specifies the path of a file or a directory to include in the configuration archive.
    It gets downloaded to the virtual machine together with the configuration.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: ConfigurationDataPath
  description: |+
    Specifies the path of a .psd1 file that specifies the data for the configuration.
    This is added to the configuration archive and then passed to the configuration function.
    It gets overwritten by the configuration data path provided through the Set-AzVMDscExtension cmdlet

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: ConfigurationPath
  isRequired: true
  description: |+
    Specifies the path of a file that contains one or more configurations.
    The file can be a Windows PowerShell script (.ps1) file or a Windows PowerShell module (.psm1) file.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: ContainerName
  description: |+
    Specifies the name of the Azure storage container the configuration is uploaded to.

  defaultValue: None
  pipelineInput: true
  position: "4"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Forces the command to run without asking for user confirmation.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: OutputArchivePath
  description: |+
    Specifies the path of a local .zip file to write the configuration archive to.
    When this parameter is used, the configuration script is not uploaded to Azure blob storage.

  defaultValue: None
  pipelineInput: true
  position: "2"
  aliases: ConfigurationArchivePath
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: ResourceGroupName
  isRequired: true
  description: |+
    Specifies the name of the resource group that contains the storage account.

  defaultValue: None
  pipelineInput: true
  position: "2"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: SkipDependencyDetection
  description: |+
    Indicates that this cmdlet excludes DSC resource dependencies from the configuration archive.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: StorageAccountName
  isRequired: true
  description: |+
    Specifies the Azure storage account name that is used to upload the configuration script to the container specified by the *ContainerName* parameter.

  defaultValue: None
  pipelineInput: true
  position: "3"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: StorageEndpointSuffix
  description: |+
    Specifies the suffix for the storage end point.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Az.Compute.Publish-AzVMDscConfiguration
name: Publish-AzVMDscConfiguration
description: |-
  The **Publish-AzVMDscConfiguration** cmdlet uploads a Desired State Configuration (DSC) script to Azure blob storage, which later can be applied to Azure virtual machines using the Set-AzVMDscExtension cmdlet.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Compute.dll-Help.xml
  Module Name: Az.Compute
  ms.assetid: FB9ACBA2-081E-4876-A21A-F5BA11CBEDA2
  online version: https://docs.microsoft.com/en-us/powershell/module/az.compute/publish-azvmdscconfiguration
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Compute/Compute/help/Publish-AzVMDscConfiguration.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Compute/Compute/help/Publish-AzVMDscConfiguration.md
