### YamlMime:PowershellCmdlet
summary: |-
  Gets the autoscale configuration of HDInsight cluster.
module: Az.HDInsight
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Azure.Commands.HDInsight.Models.AzureHDInsightCluster" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.HDInsight.Models.AzureHDInsightAutoscale" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: New-AzHDInsightClusterAutoscaleConfiguration
  href: ./New-AzHDInsightClusterAutoscaleConfiguration.yml
- text: Set-AzHDInsightClusterAutoscaleConfiguration
  href: ./Set-AzHDInsightClusterAutoscaleConfiguration.yml
- text: Remove-AzHDInsightClusterAutoscaleConfiguration
  href: ./Remove-AzHDInsightClusterAutoscaleConfiguration.yml
syntaxes:
- >-
  Get-AzHDInsightClusterAutoscaleConfiguration [[-ResourceGroupName] <String>] [-ClusterName] <String>

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
- >-
  Get-AzHDInsightClusterAutoscaleConfiguration [-ResourceId] <String> [-DefaultProfile <IAzureContextContainer>]

   [<CommonParameters>]
- >-
  Get-AzHDInsightClusterAutoscaleConfiguration [-InputObject] <AzureHDInsightCluster>

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
examples:
- title: 'Example 1: Get the autoscale configuration of HDInsight cluster.'
  code: |-
    PS C:\> $clusterResourceGroup="group"
    PS C:\> $clusterName="MyCluster"
    PS C:\> Get-AzHDInsightClusterAutoscaleConfiguration -ResourceGroupName $clusterResourceGroup -ClusterName $clusterName
  description: |-
    This command gets the autoscale configuration of HDInsight cluster.
  summary: ""
parameters:
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: ClusterName
  isRequired: true
  description: |+
    Gets or sets the name of the cluster.

  defaultValue: None
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with Azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.HDInsight.Models.AzureHDInsightCluster" data-throw-if-not-resolved="False" />
  name: InputObject
  isRequired: true
  description: |+
    Gets or sets the input object.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: ResourceGroupName
  description: |+
    Gets or sets the name of the resource group.

  defaultValue: None
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: ResourceId
  isRequired: true
  description: |+
    Gets or sets the resource id.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
uid: Az.HDInsight.Get-AzHDInsightClusterAutoscaleConfiguration
name: Get-AzHDInsightClusterAutoscaleConfiguration
description: |-
  The **Get-AzHDInsightClusterAutoscaleConfiguration** cmdlet gets the autoscale configuration of HDInsight cluster.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.HDInsight.dll-Help.xml
  Module Name: Az.HDInsight
  ms.assetid: 8CD55A33-5964-409A-BDA5-EDAE9A21E0C1
  online version: https://docs.microsoft.com/en-us/powershell/module/az.hdinsight/get-azhdinsightclusterautoscaleconfiguration
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/HDInsight/HDInsight/help/Get-AzHDInsightClusterAutoscaleConfiguration.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/HDInsight/HDInsight/help/Get-AzHDInsightClusterAutoscaleConfiguration.md
