### YamlMime:PowershellCmdlet
summary: |-
  Gets an application control VM/server group.
module: Az.Security
notes: |-
  ## RELATED LINKS
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Security.Models.AdaptiveApplicationControls.PSSecurityAdaptiveApplicationControls" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Get-AzSecurityAdaptiveApplicationControlGroup  -GroupName <String> -AscLocation <String> [-SubscriptionId <String>]

  [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    PS C:\> Get-AzSecurityAdaptiveApplicationControlGroup -GroupName GROUP1 -AscLocation centralus
    Id         : /subscriptions/3eeab341-f466-499c-a8be-85427e154baf7612f869/providers/Microsoft.Security/locations/centralus/applicationWhitelistings/GROUP1
    Name       : GROUP1
    Type       : Microsoft.Security/applicationWhitelistings
    Location   : centralus
    Properties : Microsoft.Azure.Commands.SecurityCenter.Models.AdaptiveApplicationControls.PSSecurityAdaptiveApplicationControlsProperties
  description: |-
    Gets an application control VM/server group.
  summary: ""
parameters:
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: AscLocation
  isRequired: true
  description: |+
    The location where ASC stores the data of the subscription. can be retrieved from Get locations.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with Azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: GroupName
  isRequired: true
  description: |+
    Name of an application control VM/server group.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: SubscriptionId
  description: |+
    Azure subscription ID.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Az.Security.Get-AzSecurityAdaptiveApplicationControlGroup
name: Get-AzSecurityAdaptiveApplicationControlGroup
description: |-
  Adaptive Application Controls are automatically calculated by Azure Security Center, use this cmdlet to get an application control VM/server group.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Security.dll-Help.xml
  Module Name: Az.Security
  online version: https://docs.microsoft.com/en-us/powershell/module/az.security/Get-AzSecurityAdaptiveApplicationControlGroup
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Security/Security/help/Get-AzSecurityAdaptiveApplicationControlGroup.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Security/Security/help/Get-AzSecurityAdaptiveApplicationControlGroup.md
