### YamlMime:PowershellCmdlet
summary: |-
  Create new recommendation configuration for iot security solution
module: Az.Security
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Security.Models.IotSecuritySolutions.PSRecommendationConfiguration" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  New-AzIotSecuritySolutionRecommendationConfigurationObject -RecommendationType <String> -Enabled <Boolean>

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    PS C:\> New-AzIotSecuritySolutionRecommendationConfigurationObject -RecommendationType "IoT_ACRAuthentication" -Enabled $false

    RecommendationType: "IoT_ACRAuthentication"
    Name: "Service prinicpal not used with ACR repository"
    Status: "Disabled"
  description: |-
    Create new recommendation configuration for recommendation type "IoT_ACRAuthentication" with status set to disable
  summary: ""
parameters:
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with Azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.Boolean" data-throw-if-not-resolved="False" />
  name: Enabled
  isRequired: true
  description: |+
    Status .

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: RecommendationType
  isRequired: true
  description: |+
    Recommendation type.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Az.Security.New-AzIotSecuritySolutionRecommendationConfigurationObject
name: New-AzIotSecuritySolutionRecommendationConfigurationObject
description: |-
  The AzIotSecuritySolutionRecommendationConfigurationObject creates a new recommendation configuration object for iot security solution.
  This way the status of a recommendation is configured, whether it is enabled or disabled.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Security.dll-Help.xml
  Module Name: Az.Security
  online version: https://docs.microsoft.com/en-us/powershell/module/az.security/New-AzIotSecuritySolutionRecommendationConfigurationObject
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Security/Security/help/New-AzIotSecuritySolutionRecommendationConfigurationObject.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Security/Security/help/New-AzIotSecuritySolutionRecommendationConfigurationObject.md
