### YamlMime:PowershellCmdlet
summary: |-
  Adds a route to a route table.
module: Az.Network
notes: ""
inputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSRouteTable" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSRouteTable" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-AzRouteConfig
  href: ./Get-AzRouteConfig.yml
- text: Get-AzRouteTable
  href: ./Get-AzRouteTable.yml
- text: New-AzRouteConfig
  href: ./New-AzRouteConfig.yml
- text: Remove-AzRouteConfig
  href: ./Remove-AzRouteConfig.yml
- text: Set-AzRouteConfig
  href: ./Set-AzRouteConfig.yml
- text: Set-AzRouteTable
  href: ./Set-AzRouteTable.yml
syntaxes:
- >-
  Add-AzRouteConfig -RouteTable <PSRouteTable> [-Name <String>] [-AddressPrefix <String>] [-NextHopType <String>]

   [-NextHopIpAddress <String>] [-DefaultProfile <IAzureContextContainer>] [-WhatIf] [-Confirm]

   [<CommonParameters>]
examples:
- title: 'Example 1: Add a route to a route table'
  code: |-
    PS C:\>$RouteTable = Get-AzRouteTable -ResourceGroupName "ResourceGroup11" -Name "RouteTable01"
    PS C:\> Add-AzRouteConfig -Name "Route13" -AddressPrefix 10.3.0.0/16 -NextHopType "VnetLocal" -RouteTable $RouteTable
  description: |-
    The first command gets a route table named RouteTable01 by using the Get-AzRouteTable cmdlet.
    The command stores the table in the $RouteTable variable.
    The second command adds a route named Route13 to the route table stored in $RouteTable.
    This route forwards packets to the local virtual network.
  summary: ""
- title: 'Example 2: Add a route to a route table by using the pipeline'
  code: |-
    PS C:\>Get-AzRouteTable -ResourceGroupName "ResourceGroup11" -Name "RouteTable01" | Add-AzRouteConfig -Name "Route02" -AddressPrefix 10.2.0.0/16 -NextHopType VnetLocal | Set-AzRouteTable
    Name              : routetable01
    ResourceGroupName : ResourceGroup11
    Location          : eastus
    Id                : /subscriptions/xxxx-xxxx-xxxx-xxxx/resourceGroups/ResourceGroup11/providers/Microsoft.Networ
                        k/routeTables/routetable01
    Etag              : W/"f13e1bc8-d41f-44d0-882d-b8b5a1134f59"
    ProvisioningState : Succeeded
    Tags              : 
    Routes            : [
                          {
                            "Name": "route07",
                            "Etag": "W/\"f13e1bc8-d41f-44d0-882d-b8b5a1134f59\"",
                            "Id": "/subscriptions/xxxx-xxxx-xxxx-xxxx/resourceGroups/ResourceGroup11/providers/Micro
                        soft.Network/routeTables/routetable01/routes/route07",
                            "AddressPrefix": "10.1.0.0/16",
                            "NextHopType": "VnetLocal",
                            "NextHopIpAddress": null, 
                            "ProvisioningState": "Succeeded"
                          },
                          {
                            "Name": "route02",
                            "Etag": "W/\"f13e1bc8-d41f-44d0-882d-b8b5a1134f59\"",
                            "Id": "/subscriptions/xxxx-xxxx-xxxx-xxxx/resourceGroups/ResourceGroup11/providers/Micro
                        soft.Network/routeTables/routetable01/routes/route02",
                            "AddressPrefix": "10.2.0.0/16",
                            "NextHopType": "VnetLocal",
                            "NextHopIpAddress": null, 
                            "ProvisioningState": "Succeeded"
                          },
                          {
                            "Name": "route13",
                            "Etag": null, 
                            "Id": null, 
                            "AddressPrefix": "10.3.0.0/16",
                            "NextHopType": "VnetLocal",
                            "NextHopIpAddress": null, 
                            "ProvisioningState": null
                          }
                        ] 
    Subnets           : []
  description: |-
    This command gets the route table named RouteTable01 by using **Get-AzRouteTable**.
    The command passes that table to the current cmdlet by using the pipeline operator.
    The current cmdlet adds the route named Route02, and then passes the result to the **Set-AzRouteTable** cmdlet, which updates the table to reflect your changes.
  summary: ""
parameters:
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: AddressPrefix
  description: |+
    Specifies the destination, in Classless Interdomain Routing (CIDR) format, to which the route applies.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  description: |+
    Specifies a name of the route to add to the route table.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: NextHopIpAddress
  description: |+
    Specifies the IP address of a virtual appliance that you add to your Azure virtual network.
    This route forwards packets to that address.
    Specify this parameter only if you specify a value of VirtualAppliance for the *NextHopType* parameter.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: NextHopType
  description: |+
    Specifies how this route forwards packets.
    The acceptable values for this parameter are:
    - Internet.
    The default Internet gateway provided by Azure. 
    - None.
    If you specify this value, the route does not forward packets. 
    - VirtualAppliance.
    A virtual appliance that you add to your Azure virtual network. 
    - VirtualNetworkGateway.
    An Azure server-to-server virtual private network gateway. 
    - VnetLocal.
    The local virtual network.
    If you have two subnets, 10.1.0.0/16 and 10.2.0.0/16 in the same virtual network, select a value of VnetLocal for each subnet to forward to the other subnet.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSRouteTable" data-throw-if-not-resolved="False" />
  name: RouteTable
  isRequired: true
  description: |+
    Specifies the route table to which this cmdlet adds a route.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs. The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Az.Network.Add-AzRouteConfig
name: Add-AzRouteConfig
description: |-
  The **Add-AzRouteConfig** cmdlet adds a route to an Azure route table.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  Module Name: Az.Network
  ms.assetid: C868DFA4-8A9D-4108-B88B-ACD7F100A63C
  online version: https://docs.microsoft.com/en-us/powershell/module/az.network/add-azrouteconfig
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Add-AzRouteConfig.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Add-AzRouteConfig.md
