### YamlMime:PowershellCmdlet
summary: |-
  Gets a route filter rule in a route filter.
module: Az.Network
notes: ""
inputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSRouteFilter" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSRouteFilterRule" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Add-AzRouteFilterRuleConfig
  href: ./Add-AzRouteFilterRuleConfig.yml
- text: New-AzRouteFilterRuleConfig
  href: ./New-AzRouteFilterRuleConfig.yml
- text: Remove-AzRouteFilterRuleConfig
  href: ./Remove-AzRouteFilterRuleConfig.yml
- text: Set-AzRouteFilterRuleConfig
  href: ./Set-AzRouteFilterRuleConfig.yml
- text: Get-AzRouteFilter
  href: ./Get-AzRouteFilter.yml
- text: New-AzRouteFilter
  href: ./New-AzRouteFilter.yml
- text: Remove-AzRouteFilter
  href: ./Remove-AzRouteFilter.yml
- text: Set-AzRouteFilter
  href: ./Set-AzRouteFilter.yml
syntaxes:
- >-
  Get-AzRouteFilterRuleConfig [-Name <String>] -RouteFilter <PSRouteFilter>

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    PS C:\> $rf = Get-AzRouteFilter -Name "MyRouteFilter" -ResourceGroupName "MyResourceGroup"
    PS C:\> Get-AzRouteFilterRuleConfig -RouteFilter $rf -Name "Rule01"
    PS C:\> Get-AzRouteFilterRuleConfig -RouteFilter $rf
  description: |-
    The first command gets the route filter named MyRouteFilter, and then stores it in the variable $rf.
    The second command gets the route filter rule named Rule01 associated with that route filter.
    The third command gets a list of route filter rules associated with that route filter.
  summary: ""
parameters:
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  description: |+
    The name of the route filter rule

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSRouteFilter" data-throw-if-not-resolved="False" />
  name: RouteFilter
  isRequired: true
  description: |+
    The RouteFilter

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Az.Network.Get-AzRouteFilterRuleConfig
name: Get-AzRouteFilterRuleConfig
description: |-
  The **Get-AzRouteFilterRuleConfig** cmdlet gets a route filter rule or a list of route filter rules in a route filter.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  Module Name: Az.Network
  online version: https://docs.microsoft.com/en-us/powershell/module/az.network/get-azroutefilterruleconfig
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Get-AzRouteFilterRuleConfig.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Get-AzRouteFilterRuleConfig.md
