### YamlMime:PowershellCmdlet
summary: |-
  Gets the SSL policy of an application gateway.
module: Az.Network
notes: |-
  * Keywords: azure, azurerm, arm, resource, management, manager, network, networking
inputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationGateway" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationGatewaySslPolicy" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: New-AzApplicationGatewaySslPolicy
  href: ./New-AzApplicationGatewaySslPolicy.yml
- text: Set-AzApplicationGatewaySslPolicy
  href: ./Set-AzApplicationGatewaySslPolicy.yml
syntaxes:
- >-
  Get-AzApplicationGatewaySslPolicy -ApplicationGateway <PSApplicationGateway>

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
examples:
- title: '1:'
  code: |-
    PS C:\>$AppGW = Get-AzApplicationGateway -Name "ApplicationGateway01" -ResourceGroupName "ResourceGroup01"
    PS C:\> $sslpolicy = Get-AzApplicationGatewaySslPolicy -ApplicationGateway $AppGW
  description: |-
    The first command gets the Application Gateway named ApplicationGateway01 and stores the result in the variable named $AppGW.
    The second command gets the ssl policy from the Application Gateway stored in the variable named $AppGW.
  summary: ""
parameters:
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationGateway" data-throw-if-not-resolved="False" />
  name: ApplicationGateway
  isRequired: true
  description: |+
    Specifies the application gateway of the SSL policy that this cmdlet gets.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
uid: Az.Network.Get-AzApplicationGatewaySslPolicy
name: Get-AzApplicationGatewaySslPolicy
description: |-
  The **Get-AzApplicationGatewaySslPolicy** cmdlet gets the SSL policy of an application gateway.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  Module Name: Az.Network
  ms.assetid: AF02FFF8-F00D-4446-968F-F3C9008C39F0
  online version: https://docs.microsoft.com/en-us/powershell/module/az.network/get-azapplicationgatewaysslpolicy
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Get-AzApplicationGatewaySslPolicy.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Get-AzApplicationGatewaySslPolicy.md
