### YamlMime:PowershellCmdlet
summary: |-
  Get a network security rule configuration for a network security group.
module: Az.Network
notes: ""
inputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSNetworkSecurityGroup" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSSecurityRule" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Add-AzNetworkSecurityRuleConfig
  href: ./Add-AzNetworkSecurityRuleConfig.yml
- text: New-AzNetworkSecurityRuleConfig
  href: ./New-AzNetworkSecurityRuleConfig.yml
- text: Remove-AzNetworkSecurityRuleConfig
  href: ./Remove-AzNetworkSecurityRuleConfig.yml
- text: Set-AzNetworkSecurityRuleConfig
  href: ./Set-AzNetworkSecurityRuleConfig.yml
syntaxes:
- >-
  Get-AzNetworkSecurityRuleConfig [-Name <String>] -NetworkSecurityGroup <PSNetworkSecurityGroup> [-DefaultRules]

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
examples:
- title: '1: Retrieving a network security rule config'
  code: |-
    Get-AzNetworkSecurityGroup -Name nsg1 -ResourceGroupName rg1 
        | Get-AzNetworkSecurityRuleConfig -Name AllowInternetOutBound -DefaultRules
  description: |-
    This command retrieves the default rule named "AllowInternetOutBound" from Azure network security group named "nsg1" in resource group "rg1"
  summary: ""
- title: '2: Retrieving a network security rule config using only the name'
  code: |-
    Get-AzNetworkSecurityGroup -Name nsg1 -ResourceGroupName rg1 
        | Get-AzNetworkSecurityRuleConfig -Name "rdp-rule"
  description: |-
    This command retrieves user defined rule named "rdp-rule" from Azure network security group named "nsg1" in resource group "rg1"
  summary: ""
parameters:
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: DefaultRules
  description: |+
    Indicates whether this cmdlet gets a user-created rule configuration or a default rule configuration.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  description: |+
    Specifies the name of the network security rule configuration to get.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSNetworkSecurityGroup" data-throw-if-not-resolved="False" />
  name: NetworkSecurityGroup
  isRequired: true
  description: |+
    Specifies a **NetworkSecurityGroup** object that contains the network security rule configuration to get.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Az.Network.Get-AzNetworkSecurityRuleConfig
name: Get-AzNetworkSecurityRuleConfig
description: |-
  The **Get-AzNetworkSecurityRuleConfig** cmdlet gets a network security rule configuration for an Azure network security group.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  Module Name: Az.Network
  ms.assetid: 5A0D9326-3A8A-4156-8372-EBA93C1BB4E4
  online version: https://docs.microsoft.com/en-us/powershell/module/az.network/get-aznetworksecurityruleconfig
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Get-AzNetworkSecurityRuleConfig.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Get-AzNetworkSecurityRuleConfig.md
