### YamlMime:PowershellCmdlet
summary: |-
  Gets the WAF configuration of an application gateway.
module: Az.Network
notes: ""
inputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationGateway" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationGatewayWebApplicationFirewallConfiguration" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-AzApplicationGateway
  href: ./Get-AzApplicationGateway.yml
- text: New-AzApplicationGatewayWebApplicationFirewallConfiguration
  href: ./New-AzApplicationGatewayWebApplicationFirewallConfiguration.yml
- text: Set-AzApplicationGatewayWebApplicationFirewallConfiguration
  href: ./Set-AzApplicationGatewayWebApplicationFirewallConfiguration.yml
syntaxes:
- >-
  Get-AzApplicationGatewayWebApplicationFirewallConfiguration -ApplicationGateway <PSApplicationGateway>

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
examples:
- title: 'Example 1: Get an application gateway web application firewall configuration'
  code: |-
    PS C:\>$AppGW = Get-AzApplicationGateway -Name "ApplicationGateway01" -ResourceGroupName "ResourceGroup01"
    PS C:\> $FirewallConfig = Get-AzApplicationGatewayWebApplicationFirewallConfiguration -ApplicationGateway $AppGW
  description: |-
    The first command gets the application gateway named ApplicationGateway01, and then stores it in the $AppGW variable.
    The second command gets the firewall configuration of the application gateway in $AppGW, and then stores it in $FirewallConfig.
  summary: ""
parameters:
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationGateway" data-throw-if-not-resolved="False" />
  name: ApplicationGateway
  isRequired: true
  description: |+
    Specifies an application gateway object.
    You can use the Get-AzApplicationGateway cmdlet to get an application gateway object.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
uid: Az.Network.Get-AzApplicationGatewayWebApplicationFirewallConfiguration
name: Get-AzApplicationGatewayWebApplicationFirewallConfiguration
description: |-
  The **Get-AzApplicationGatewayWebApplicationFirewallConfiguration** cmdlet gets the web application firewall (WAF) configuration of an application gateway.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  Module Name: Az.Network
  ms.assetid: 5D887302-7678-44C0-86F3-CEF2EF8A0991
  online version: https://docs.microsoft.com/en-us/powershell/module/az.network/get-azapplicationgatewaywebapplicationfirewallconfiguration
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Get-AzApplicationGatewayWebApplicationFirewallConfiguration.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Get-AzApplicationGatewayWebApplicationFirewallConfiguration.md
