### YamlMime:PowershellCmdlet
summary: |-
  Creates an SSL certificate for an Azure application gateway.
module: Az.Network
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationGatewaySslCertificate" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Add-AzApplicationGatewaySslCertificate
  href: ./Add-AzApplicationGatewaySslCertificate.yml
- text: Get-AzApplicationGatewaySslCertificate
  href: ./Get-AzApplicationGatewaySslCertificate.yml
- text: Remove-AzApplicationGatewaySslCertificate
  href: ./Remove-AzApplicationGatewaySslCertificate.yml
- text: Set-AzApplicationGatewaySslCertificate
  href: ./Set-AzApplicationGatewaySslCertificate.yml
syntaxes:
- >-
  New-AzApplicationGatewaySslCertificate -Name <String> [-CertificateFile <String>] [-Password <SecureString>]

   [-KeyVaultSecretId <String>] [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
examples:
- title: 'Example 1: Create an SSL certificate for an Azure application gateway.'
  code: |-
    PS C:\> $password = ConvertTo-SecureString "P@ssw0rd" -AsPlainText -Force
    PS C:\> $cert = New-AzApplicationGatewaySslCertificate -Name "Cert01" -CertificateFile "D:\cert01.pfx" -Password $password
  description: |-
    This command creates a SSL certificate named Cert01 for the default application gateway and stores the result in the variable named $Cert.
  summary: ""
- title: 'Example 2: Create an SSL certificate using KeyVault Secret (version-less secretId) and add to an application gateway.'
  code: |-
    PS C:\> $secret = Get-AzKeyVaultSecret -VaultName "keyvault01" -Name "sslCert01"
    PS C:\> $secretId = $secret.Id.Replace($secret.Version, "") # https://<keyvaultname>.vault.azure.net/secrets/
    PS C:\> $cert = New-AzApplicationGatewaySslCertificate -Name "Cert01" -KeyVaultSecretId $secretId
  description: |-
    Get the secret and create an SSL Certificate using `New-AzApplicationGatewaySslCertificate`.
    Note: As version-less secretId is provided here, Application Gateway will sync the certificate in regular intervals with the KeyVault.
  summary: ""
- title: 'Example 3: Create an SSL certificate using KeyVault Secret and add to an Application Gateway.'
  code: |-
    PS C:\> $secret = Get-AzKeyVaultSecret -VaultName "keyvault01" -Name "sslCert01"
    PS C:\> $secretId = $secret.Id # https://<keyvaultname>.vault.azure.net/secrets/<hash>
    PS C:\> $cert = New-AzApplicationGatewaySslCertificate -Name "Cert01" -KeyVaultSecretId $secretId
  description: |-
    Get the secret and create an SSL Certificate using `New-AzApplicationGatewaySslCertificate`.
    Note: If it is required that Application Gateway syncs the certificate with the KeyVault, please provide the version-less secretId.
  summary: ""
parameters:
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: CertificateFile
  description: |+
    Specifies the path of the .pfx file of the SSL certificate that this cmdlet creates.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: KeyVaultSecretId
  description: |+
    SecretId (uri) of the KeyVault Secret. Use this option when a specific version of secret needs to be used.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    Specifies the name of the SSL certificate that this cmdlet creates.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Security.SecureString" data-throw-if-not-resolved="False" />
  name: Password
  description: |+
    Specifies the password of the SSL that this cmdlet creates.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Az.Network.New-AzApplicationGatewaySslCertificate
name: New-AzApplicationGatewaySslCertificate
description: |-
  The **New-AzApplicationGatewaySslCertificate** cmdlet creates an SSL certificate for an Azure application gateway.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  Module Name: Az.Network
  ms.assetid: 6FFE1B64-C80B-423D-A043-55C90A224752
  online version: https://docs.microsoft.com/en-us/powershell/module/az.network/new-azapplicationgatewaysslcertificate
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/New-AzApplicationGatewaySslCertificate.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/New-AzApplicationGatewaySslCertificate.md
