### YamlMime:PowershellCmdlet
summary: |-
  Removes a network security rule from a network security group.
module: Az.Network
notes: ""
inputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSNetworkSecurityGroup" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSNetworkSecurityGroup" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Add-AzNetworkSecurityRuleConfig
  href: ./Add-AzNetworkSecurityRuleConfig.yml
- text: Get-AzNetworkSecurityRuleConfig
  href: ./Get-AzNetworkSecurityRuleConfig.yml
- text: New-AzNetworkSecurityGroup
  href: ./New-AzNetworkSecurityGroup.yml
- text: New-AzNetworkSecurityRuleConfig
  href: ./New-AzNetworkSecurityRuleConfig.yml
- text: Set-AzNetworkSecurityRuleConfig
  href: ./Set-AzNetworkSecurityRuleConfig.yml
syntaxes:
- >-
  Remove-AzNetworkSecurityRuleConfig [-Name <String>] -NetworkSecurityGroup <PSNetworkSecurityGroup>

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
examples:
- title: 'Example 1: Remove a network security rule configuration'
  code: |-
    PS C:\>$rule1 = New-AzNetworkSecurityRuleConfig -Name "rdp-rule" -Description "Allow RDP" -Access "Allow" -Protocol "Tcp" -Direction "Inbound" -Priority 100 -SourceAddressPrefix "Internet" -SourcePortRange * -DestinationAddressPrefix * -DestinationPortRange 3389
    PS C:\> $nsg = New-AzNetworkSecurityGroup -ResourceGroupName "TestRG" -Location "westus" -Name "NSG-FrontEnd" -SecurityRules $rule1
    PS C:\> Remove-AzNetworkSecurityRuleConfig -Name "rdp-rule" -NetworkSecurityGroup $nsg
    PS C:\> $nsg | Set-AzNetworkSecurityGroup
  description: |-
    The first command creates a network security rule configuration named rdp-rule, and then stores it in the $rule1 variable.
    The second command creates a network security group using the rule in $rule1, and then stores the network security group in the $nsg variable.
    The third command removes the network security rule configuration named rdp-rule from the network security group in $nsg.
    The forth command saves the change.
  summary: ""
parameters:
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  description: |+
    Specifies the name of the network security rule configuration that this cmdlet removes.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSNetworkSecurityGroup" data-throw-if-not-resolved="False" />
  name: NetworkSecurityGroup
  isRequired: true
  description: |+
    Specifies a **NetworkSecurityGroup** object.
    This object contains the network security rule configuration to remove.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Az.Network.Remove-AzNetworkSecurityRuleConfig
name: Remove-AzNetworkSecurityRuleConfig
description: |-
  The **Remove-AzNetworkSecurityRuleConfig** cmdlet removes a network security rule configuration from an Azure network security group.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  Module Name: Az.Network
  ms.assetid: 2E43D0D8-EF93-443B-AA8F-58C992026E95
  online version: https://docs.microsoft.com/en-us/powershell/module/az.network/remove-aznetworksecurityruleconfig
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Remove-AzNetworkSecurityRuleConfig.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Remove-AzNetworkSecurityRuleConfig.md
