### YamlMime:PowershellCmdlet
summary: |-
  Removes an inbound NAT rule configuration from a load balancer.
module: Az.Network
notes: ""
inputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSLoadBalancer" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSLoadBalancer" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Add-AzLoadBalancerInboundNatRuleConfig
  href: ./Add-AzLoadBalancerInboundNatRuleConfig.yml
- text: Get-AzLoadBalancerInboundNatRuleConfig
  href: ./Get-AzLoadBalancerInboundNatRuleConfig.yml
- text: New-AzLoadBalancerInboundNatRuleConfig
  href: ./New-AzLoadBalancerInboundNatRuleConfig.yml
- text: Set-AzLoadBalancerInboundNatRuleConfig
  href: ./Set-AzLoadBalancerInboundNatRuleConfig.yml
syntaxes:
- >-
  Remove-AzLoadBalancerInboundNatRuleConfig -LoadBalancer <PSLoadBalancer> [-Name <String>]

   [-DefaultProfile <IAzureContextContainer>] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: '1: Delete an inbound NAT rule from an Azure load balancer'
  code: |-
    $loadbalancer = Get-AzLoadBalancer -Name mylb -ResourceGroupName myrg

     Remove-AzLoadBalancerInboundNatRuleConfig -Name "myinboundnatrule" -LoadBalancer $loadbalancer
  description: |-
    The first command loads an already existing load balancer called "mylb" and stores it in the variable $load
        balancer. The second command removes the inbound NAT rule associated with this load balancer.
  summary: ""
parameters:
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSLoadBalancer" data-throw-if-not-resolved="False" />
  name: LoadBalancer
  isRequired: true
  description: |+
    Specifies the **LoadBalancer** object that contains the inbound NAT rule configuration that this cmdlet removes.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  description: |+
    Specifies the name of the inbound NAT rule configuration that this cmdlet removes.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs. The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Az.Network.Remove-AzLoadBalancerInboundNatRuleConfig
name: Remove-AzLoadBalancerInboundNatRuleConfig
description: |-
  The **Remove-AzLoadBalancerInboundNatRuleConfig** cmdlet removes an inbound network address translation (NAT) rule configuration from an Azure load balancer.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  Module Name: Az.Network
  ms.assetid: D818C404-60E4-42DB-AADF-063305D9541B
  online version: https://docs.microsoft.com/en-us/powershell/module/az.network/remove-azloadbalancerinboundnatruleconfig
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Remove-AzLoadBalancerInboundNatRuleConfig.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Remove-AzLoadBalancerInboundNatRuleConfig.md
