### YamlMime:PowershellCmdlet
summary: |-
  Removes a route filter rule from a route filter.
module: Az.Network
notes: ""
inputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSRouteFilter" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSRouteFilterRule" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Add-AzRouteFilterRuleConfig
  href: ./Add-AzRouteFilterRuleConfig.yml
- text: Get-AzRouteFilterRuleConfig
  href: ./Get-AzRouteFilterRuleConfig.yml
- text: New-AzRouteFilterRuleConfig
  href: ./New-AzRouteFilterRuleConfig.yml
- text: Set-AzRouteFilterRuleConfig
  href: ./Set-AzRouteFilterRuleConfig.yml
- text: Get-AzRouteFilter
  href: ./Get-AzRouteFilter.yml
- text: New-AzRouteFilter
  href: ./New-AzRouteFilter.yml
- text: Remove-AzRouteFilter
  href: ./Remove-AzRouteFilter.yml
- text: Set-AzRouteFilter
  href: ./Set-AzRouteFilter.yml
syntaxes:
- >-
  Remove-AzRouteFilterRuleConfig -Name <String> -RouteFilter <PSRouteFilter> [-Force]

   [-DefaultProfile <IAzureContextContainer>] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    PS C:\> $rf = Get-AzRouteFilter -Name "RouteFilter01" -ResourceGroupName "ResourceGroup01"
    PS C:\> Remove-AzRouteFilterRuleConfig -RouteFilter $rf -Name "Rule01"
  description: |-
    The first command gets a route filter named RouteFilter01 that belongs to the resource group named ResourceGroup01 and stores it in the $rf variable.
    The second command removes the route filter rule named Rule01 from the route filter stored in $rf.
  summary: ""
parameters:
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Do not ask for confirmation if you want to overwrite a resource

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    The name of the route filter rule

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSRouteFilter" data-throw-if-not-resolved="False" />
  name: RouteFilter
  isRequired: true
  description: |+
    The RouteFilter

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs. The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Az.Network.Remove-AzRouteFilterRuleConfig
name: Remove-AzRouteFilterRuleConfig
description: |-
  The **Remove-AzRouteFilterRuleConfig** cmdlet removes a route filter rule from a route filter.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  Module Name: Az.Network
  online version: https://docs.microsoft.com/en-us/powershell/module/az.network/remove-azroutefilterruleconfig
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Remove-AzRouteFilterRuleConfig.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Remove-AzRouteFilterRuleConfig.md
