### YamlMime:PowershellCmdlet
summary: |-
  Modifies the route filter rule of a route filter.
module: Az.Network
notes: ""
inputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSRouteFilter" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSRouteFilter" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Add-AzRouteFilterRuleConfig
  href: ./Add-AzRouteFilterRuleConfig.yml
- text: Get-AzRouteFilterRuleConfig
  href: ./Get-AzRouteFilterRuleConfig.yml
- text: New-AzRouteFilterRuleConfig
  href: ./New-AzRouteFilterRuleConfig.yml
- text: Remove-AzRouteFilterRuleConfig
  href: ./Remove-AzRouteFilterRuleConfig.yml
- text: Get-AzRouteFilter
  href: ./Get-AzRouteFilter.yml
- text: New-AzRouteFilter
  href: ./New-AzRouteFilter.yml
- text: Remove-AzRouteFilter
  href: ./Remove-AzRouteFilter.yml
- text: Set-AzRouteFilter
  href: ./Set-AzRouteFilter.yml
syntaxes:
- >-
  Set-AzRouteFilterRuleConfig -RouteFilter <PSRouteFilter> [-Force] -Name <String> -Access <String>

   -RouteFilterRuleType <String> -CommunityList <String[]> [-DefaultProfile <IAzureContextContainer>] [-WhatIf]

   [-Confirm] [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    PS C:\> $rf = Get-AzRouteFilter -Name "RouteFilter01" -ResourceGroupName "ResourceGroup01"
    PS C:\> $rf = Set-AzRouteFilterRuleConfig -RouteFilter $rf -Name "Rule01" -Access Deny -RouteFilterRuleType Community -CommunityList "12076:5010","12076:5040"
    PS C:\> Set-AzRouteFilter -RouteFilter $rf
  description: |-
    The first command gets the route filter named RouteFilter01 and stores it in the $rf variable.
    The second command modifies the route filter rule named Rule01 and stores updated route filter in the $rf variable.
    The third command saves updated route filter.
  summary: ""
parameters:
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Access
  isRequired: true
  description: |+
    The access type of the rule.
    Possible values are: 'Allow', 'Deny'

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: Allow, Deny
- type: <xref href="System.String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: CommunityList
  isRequired: true
  description: |+
    The list of community value that route filter will filter on

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Do not ask for confirmation if you want to overwrite a resource

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    The name of the route filter rule

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSRouteFilter" data-throw-if-not-resolved="False" />
  name: RouteFilter
  isRequired: true
  description: |+
    The RouteFilter

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: RouteFilterRuleType
  isRequired: true
  description: |+
    The route filter rule type of the rule.
    Possible values are: 'Community'

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: Community
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs. The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Az.Network.Set-AzRouteFilterRuleConfig
name: Set-AzRouteFilterRuleConfig
description: |-
  The **Set-AzRouteFilterRuleConfig** cmdlet modifies the route filter rule of a route filter.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  Module Name: Az.Network
  online version: https://docs.microsoft.com/en-us/powershell/module/az.network/set-azroutefilterruleconfig
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Set-AzRouteFilterRuleConfig.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Set-AzRouteFilterRuleConfig.md
