### YamlMime:PowershellCmdlet
summary: |-
  Adds a network interface IP configuration to a network interface.
module: Az.Network
notes: |-
  * Keywords: azure, azurerm, arm, resource, management, manager, network, networking
inputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSNetworkInterface" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="System.String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  description: ""
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSBackendAddressPool" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  description: ""
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSInboundNatRule" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  description: ""
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationGatewayBackendAddressPool" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  description: ""
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationSecurityGroup" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSNetworkInterface" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-AzNetworkInterfaceIpConfig
  href: ./Get-AzNetworkInterfaceIpConfig.yml
- text: New-AzNetworkInterfaceIpConfig
  href: ./New-AzNetworkInterfaceIpConfig.yml
- text: Remove-AzNetworkInterfaceIpConfig
  href: ./Remove-AzNetworkInterfaceIpConfig.yml
- text: Set-AzNetworkInterfaceIpConfig
  href: ./Set-AzNetworkInterfaceIpConfig.yml
syntaxes:
- >-
  Add-AzNetworkInterfaceIpConfig -Name <String> -NetworkInterface <PSNetworkInterface>

   [-PrivateIpAddressVersion <String>] [-PrivateIpAddress <String>] [-Primary] [-Subnet <PSSubnet>]

   [-PublicIpAddress <PSPublicIpAddress>] [-LoadBalancerBackendAddressPool <PSBackendAddressPool[]>]

   [-LoadBalancerInboundNatRule <PSInboundNatRule[]>]

   [-ApplicationGatewayBackendAddressPool <PSApplicationGatewayBackendAddressPool[]>]

   [-ApplicationSecurityGroup <PSApplicationSecurityGroup[]>] [-DefaultProfile <IAzureContextContainer>]

   [<CommonParameters>]
- >-
  Add-AzNetworkInterfaceIpConfig -Name <String> -NetworkInterface <PSNetworkInterface>

   [-PrivateIpAddressVersion <String>] [-PrivateIpAddress <String>] [-Primary] [-SubnetId <String>]

   [-PublicIpAddressId <String>] [-LoadBalancerBackendAddressPoolId <String[]>]

   [-LoadBalancerInboundNatRuleId <String[]>] [-ApplicationGatewayBackendAddressPoolId <String[]>]

   [-ApplicationSecurityGroupId <String[]>] [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
examples:
- title: 'Example 1: Add a new IP configuration with an application security group'
  code: |-
    $subnet = New-AzVirtualNetworkSubnetConfig -Name MySubnet -AddressPrefix 10.0.1.0/24
    $vnet = New-AzvirtualNetwork -Name MyVNET -ResourceGroupName MyResourceGroup -Location "West US" -AddressPrefix 10.0.0.0/16 -Subnet $subnet

    $nic = New-AzNetworkInterface -Name MyNetworkInterface -ResourceGroupName MyResourceGroup -Location "West US" -Subnet $vnet.Subnets[0]

    $asg = New-AzApplicationSecurityGroup -ResourceGroupName MyResourceGroup -Name MyASG -Location "West US"

    $nic | Set-AzNetworkInterfaceIpConfig -Name $nic.IpConfigurations[0].Name -Subnet $vnet.Subnets[0] -ApplicationSecurityGroup $asg | Set-AzNetworkInterface

    $nic | Add-AzNetworkInterfaceIpConfig -Name MyNewIpConfig -Subnet $vnet.Subnets[0] -ApplicationSecurityGroup $asg | Set-AzNetworkInterface
  description: |-
    In this example, we create a new network interface MyNetworkInterface that belongs to a subnet in the new virtual network MyVNET. We also create an empty application security group MyASG to associate with the IP configurations in the network interface. Once both objects are created, we link the default IP configuration to the MyASG object. At last, we create a new IP configuration in the network interface also linked to the application security group object.
  summary: ""
parameters:
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationGatewayBackendAddressPool" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: ApplicationGatewayBackendAddressPool
  description: |+
    Specifies a collection of application gateway backend address pool references to which this network interface IP configuration belongs.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: ApplicationGatewayBackendAddressPoolId
  description: |+
    Specifies a collection of application gateway backend address pool references to which this network interface IP configuration belongs.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationSecurityGroup" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: ApplicationSecurityGroup
  description: |+
    Specifies a collection of application security group references to which this network interface IP configuration belongs.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: ApplicationSecurityGroupId
  description: |+
    Specifies a collection of application security group references to which this network interface IP configuration belongs.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSBackendAddressPool" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: LoadBalancerBackendAddressPool
  description: |+
    Specifies a collection of load balancer backend address pool references to which this network interface IP configuration belongs.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: LoadBalancerBackendAddressPoolId
  description: |+
    Specifies a collection of load balancer backend address pool references to which this network interface IP configuration belongs.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSInboundNatRule" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: LoadBalancerInboundNatRule
  description: |+
    Specifies a collection of load balancer inbound network address translation (NAT) rule references to which this network interface IP configuration belongs.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: LoadBalancerInboundNatRuleId
  description: |+
    Specifies a collection of load balancer inbound NAT rule references to which this network interface IP configuration belongs.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    Specifies the name of the network interface IP configuration.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSNetworkInterface" data-throw-if-not-resolved="False" />
  name: NetworkInterface
  isRequired: true
  description: |+
    Specifies a **NetworkInterface** object.
    This cmdlet adds a network interface IP configuration to the object that this parameter specifies.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: Primary
  description: ""
  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: PrivateIpAddress
  description: |+
    Specifies the static IP address of the network interface IP configuration.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: PrivateIpAddressVersion
  description: |+
    Specifies the IP address version of a network interface IP configuration.
    The acceptable values for this parameter are:
    - IPv4
    - IPv6

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: IPv4, IPv6
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSPublicIpAddress" data-throw-if-not-resolved="False" />
  name: PublicIpAddress
  description: |+
    Specifies a **PublicIPAddress** object.
    This cmdlet creates a reference to a public IP Address to associate with this network interface IP configuration.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: PublicIpAddressId
  description: |+
    This cmdlet creates a reference to a public IP Address to associate with this network interface IP configuration.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSSubnet" data-throw-if-not-resolved="False" />
  name: Subnet
  description: |+
    Specifies a **Subnet** object.
    This cmdlet creates a reference to a subnet in which this network interface IP configuration is created.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: SubnetId
  description: |+
    This cmdlet creates a reference to a subnet in which this network interface IP configuration is created.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Az.Network.Add-AzNetworkInterfaceIpConfig
name: Add-AzNetworkInterfaceIpConfig
description: |-
  The **Add-AzNetworkInterfaceIpConfig** cmdlet adds a network interface IP configuration to an Azure network interface.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  Module Name: Az.Network
  ms.assetid: 7610228A-61F9-41B8-A42A-CD7C793BB33F
  online version: https://docs.microsoft.com/en-us/powershell/module/az.network/add-aznetworkinterfaceipconfig
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Add-AzNetworkInterfaceIpConfig.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Add-AzNetworkInterfaceIpConfig.md
