### YamlMime:PowershellCmdlet
summary: |-
  Gets an ExpressRoute circuit connection configuration associated with Private Peering of ExpressRouteCircuit.
module: Az.Network
notes: ""
inputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSExpressRouteCircuit" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSExpressRouteCircuitConnection" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-AzExpressRouteCircuit
  href: Get-AzExpressRouteCircuit.yml
- text: Add-AzExpressRouteCircuitConnectionConfig
  href: Add-AzExpressRouteCircuitConnectionConfig.yml
- text: Remove-AzExpressRouteCircuitConnectionConfig
  href: Remove-AzExpressRouteCircuitConnectionConfig.yml
syntaxes:
- >-
  Get-AzExpressRouteCircuitConnectionConfig [[-Name] <String>] [-ExpressRouteCircuit] <PSExpressRouteCircuit>

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
examples:
- title: 'Example 1: Display the circuit connection configuration for an ExpressRoute circuit'
  code: |-
    $circuit_init = Get-AzExpressRouteCircuit -Name $initiatingCircuitName -ResourceGroupName $rg
    Get-AzExpressRouteCircuitConnectionConfig -Name $circuitConnectionName -ExpressRouteCircuit $circuit_init
  description: ""
  summary: ""
- title: 'Example 2: Get circuit connection resource associated with an ExpressRoute Circuit using piping'
  code: |-
    Get-AzExpressRouteCircuit -Name $initiatingCircuitName -ResourceGroupName $rg|Get-AzExpressRouteCircuitConnectionConfig -Name $circuitConnectionName
  description: ""
  summary: ""
parameters:
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSExpressRouteCircuit" data-throw-if-not-resolved="False" />
  name: ExpressRouteCircuit
  isRequired: true
  description: |+
    The ExpressRoute circuit object containing the circuit connection configuration.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  description: |+
    The name of the circuit connection configuration to be retrieved.

  defaultValue: None
  position: "0"
  aliases: ""
  parameterValueGroup: ""
uid: Az.Network.Get-AzExpressRouteCircuitConnectionConfig
name: Get-AzExpressRouteCircuitConnectionConfig
description: |-
  The **Get-AzExpressRouteCircuitConnectionConfig** cmdlet retrieves the configuration of a circuit connection
  associated with Private Peering for an ExpressRoute circuit.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  Module Name: Az.Network
  ms.assetid: 59692f1f-9f1e-4a3c-8200-312c3806a9b7
  online version: https://docs.microsoft.com/en-us/powershell/module/az.network/get-azexpressroutecircuitconnectionconfig
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Get-AzExpressRouteCircuitConnectionConfig.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Get-AzExpressRouteCircuitConnectionConfig.md
