### YamlMime:PowershellCmdlet
summary: |-
  Gets one or more inbound NAT pool configurations from a load balancer.
module: Az.Network
notes: ""
inputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSLoadBalancer" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSInboundNatPool" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Add-AzLoadBalancerInboundNatPoolConfig
  href: ./Add-AzLoadBalancerInboundNatPoolConfig.yml
- text: New-AzLoadBalancerInboundNatPoolConfig
  href: ./New-AzLoadBalancerInboundNatPoolConfig.yml
- text: Remove-AzLoadBalancerInboundNatPoolConfig
  href: ./Remove-AzLoadBalancerInboundNatPoolConfig.yml
- text: Set-AzLoadBalancerInboundNatPoolConfig
  href: ./Set-AzLoadBalancerInboundNatPoolConfig.yml
syntaxes:
- >-
  Get-AzLoadBalancerInboundNatPoolConfig -LoadBalancer <PSLoadBalancer> [-Name <String>]

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
examples:
- title: '1: Get'
  code: |-
    PS C:\> $slb = Get-AzLoadBalancer -Name "MyLoadBalancer" -ResourceGroupName "MyResourceGroup"
    PS C:\> $slb | Get-AzLoadBalancerInboundNatPoolConfig -Name myInboundNatPool
  description: ""
  summary: ""
parameters:
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSLoadBalancer" data-throw-if-not-resolved="False" />
  name: LoadBalancer
  isRequired: true
  description: ""
  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  description: ""
  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Az.Network.Get-AzLoadBalancerInboundNatPoolConfig
name: Get-AzLoadBalancerInboundNatPoolConfig
description: |-
  The **Get-AzLoadBalancerInboundNatPoolConfig** cmdlet gets one or more inbound NAT pool configurations from a load balancer.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  Module Name: Az.Network
  ms.assetid: 614B0634-154A-449A-83E7-051DEF5A3BEE
  online version: https://docs.microsoft.com/en-us/powershell/module/az.network/get-azloadbalancerinboundnatpoolconfig
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Get-AzLoadBalancerInboundNatPoolConfig.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Get-AzLoadBalancerInboundNatPoolConfig.md
