### YamlMime:PowershellCmdlet
summary: |-
  Gets a subnet in a virtual network.
module: Az.Network
notes: ""
inputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSVirtualNetwork" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSSubnet" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Add-AzVirtualNetworkSubnetConfig
  href: ./Add-AzVirtualNetworkSubnetConfig.yml
- text: New-AzVirtualNetworkSubnetConfig
  href: ./New-AzVirtualNetworkSubnetConfig.yml
- text: Remove-AzVirtualNetworkSubnetConfig
  href: ./Remove-AzVirtualNetworkSubnetConfig.yml
- text: Set-AzVirtualNetworkSubnetConfig
  href: ./Set-AzVirtualNetworkSubnetConfig.yml
syntaxes:
- >-
  Get-AzVirtualNetworkSubnetConfig [-Name <String>] -VirtualNetwork <PSVirtualNetwork>

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
examples:
- title: '1: Get a subnet in a virtual network'
  code: |-
    New-AzResourceGroup -Name TestResourceGroup -Location centralus
        $frontendSubnet = New-AzVirtualNetworkSubnetConfig -Name frontendSubnet 
        -AddressPrefix "10.0.1.0/24"
        $virtualNetwork = New-AzVirtualNetwork -Name MyVirtualNetwork -ResourceGroupName 
        TestResourceGroup -Location centralus -AddressPrefix "10.0.0.0/16" -Subnet $frontendSubnet
        Get-AzVirtualNetworkSubnetConfig -Name frontendSubnet -VirtualNetwork $virtualNetwork
  description: |-
    This example creates a resource group and a virtual network with a single subnet in that resource group. It then retrieves data about that subnet.
  summary: ""
parameters:
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  description: |+
    Specifies the name of the subnet configuration that this cmdlet gets.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSVirtualNetwork" data-throw-if-not-resolved="False" />
  name: VirtualNetwork
  isRequired: true
  description: |+
    Specifies the **VirtualNetwork** object that contains the subnet configuration that this cmdlet gets.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Az.Network.Get-AzVirtualNetworkSubnetConfig
name: Get-AzVirtualNetworkSubnetConfig
description: |-
  The **Get-AzVirtualNetworkSubnetConfig** cmdlet gets one or more subnet configurations in an Azure virtual network.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  Module Name: Az.Network
  ms.assetid: 7688CE56-0A25-4409-9676-BF1B67C3F05F
  online version: https://docs.microsoft.com/en-us/powershell/module/az.network/get-azvirtualnetworksubnetconfig
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Get-AzVirtualNetworkSubnetConfig.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Get-AzVirtualNetworkSubnetConfig.md
