### YamlMime:PowershellCmdlet
summary: |-
  Gets an application security group.
module: Az.Network
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationSecurityGroup" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: New-AzApplicationSecurityGroup
  href: ./New-AzApplicationSecurityGroup.yml
- text: Remove-AzApplicationSecurityGroup
  href: ./Remove-AzApplicationSecurityGroup.yml
- text: Get-AzNetworkSecurityRuleConfig
  href: ./Get-AzNetworkSecurityRuleConfig.yml
- text: Get-AzNetworkInterfaceIpConfig
  href: ./Get-AzNetworkInterfaceIpConfig.yml
syntaxes:
- >-
  Get-AzApplicationSecurityGroup [-ResourceGroupName <String>] [-Name <String>]

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
examples:
- title: 'Example 1: Retrieve all application security groups.'
  code: |-
    PS C:\> Get-AzApplicationSecurityGroup

    ProvisioningState : Succeeded
    ResourceGroupName : MyResourceGroup
    Location          : southcentralus
    ResourceGuid      :
    Type              : Microsoft.Network/applicationSecurityGroups
    Tag               : {}
    TagsTable         :
    Name              : MyApplicationSecurityGroup1
    Etag              : W/"00000000-0000-0000-0000-000000000000"
    Id                : /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/MyResourceGroup/providers/Microsof
                        t.Network/applicationSecurityGroups/MyApplicationSecurityGroup1

    ProvisioningState : Succeeded
    ResourceGroupName : MyResourceGroup
    Location          : southcentralus
    ResourceGuid      :
    Type              : Microsoft.Network/applicationSecurityGroups
    Tag               : {}
    TagsTable         :
    Name              : MyApplicationSecurityGroup2
    Etag              : W/"00000000-0000-0000-0000-000000000000"
    Id                : /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/MyResourceGroup/providers/Microsof
                        t.Network/applicationSecurityGroups/MyApplicationSecurityGroup2
  description: |-
    The command above returns the all application security groups in the subscription.
  summary: ""
- title: 'Example 2: Retrieve application security groups in a resource group.'
  code: |-
    PS C:\> Get-AzApplicationSecurityGroup -ResourceGroupName MyResourceGroup

    ProvisioningState : Succeeded
    ResourceGroupName : MyResourceGroup
    Location          : southcentralus
    ResourceGuid      :
    Type              : Microsoft.Network/applicationSecurityGroups
    Tag               : {}
    TagsTable         :
    Name              : MyApplicationSecurityGroup1
    Etag              : W/"00000000-0000-0000-0000-000000000000"
    Id                : /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/MyResourceGroup/providers/Microsof
                        t.Network/applicationSecurityGroups/MyApplicationSecurityGroup1

    ProvisioningState : Succeeded
    ResourceGroupName : MyResourceGroup
    Location          : southcentralus
    ResourceGuid      :
    Type              : Microsoft.Network/applicationSecurityGroups
    Tag               : {}
    TagsTable         :
    Name              : MyApplicationSecurityGroup2
    Etag              : W/"00000000-0000-0000-0000-000000000000"
    Id                : /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/MyResourceGroup/providers/Microsof
                        t.Network/applicationSecurityGroups/MyApplicationSecurityGroup2
  description: |-
    The command above returns all application security groups that belong to the resource group MyResourceGroup.
  summary: ""
- title: 'Example 3: Retrieve a specific application security group.'
  code: |-
    PS C:\> Get-AzApplicationSecurityGroup -ResourceGroupName MyResourceGroup -Name MyApplicationSecurityGroup1

    ProvisioningState : Succeeded
    ResourceGroupName : MyResourceGroup
    Location          : southcentralus
    ResourceGuid      :
    Type              : Microsoft.Network/applicationSecurityGroups
    Tag               : {}
    TagsTable         :
    Name              : MyApplicationSecurityGroup1
    Etag              : W/"00000000-0000-0000-0000-000000000000"
    Id                : /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/MyResourceGroup/providers/Microsof
                        t.Network/applicationSecurityGroups/MyApplicationSecurityGroup1
  description: |-
    The command above returns the application security group MyApplicationSecurityGroup under the resource group MyResourceGroup.
  summary: ""
- title: 'Example 4: Retrieve application security groups using filtering.'
  code: |-
    PS C:\> Get-AzApplicationSecurityGroup -Name MyApplicationSecurityGroup*

    ProvisioningState : Succeeded
    ResourceGroupName : MyResourceGroup
    Location          : southcentralus
    ResourceGuid      :
    Type              : Microsoft.Network/applicationSecurityGroups
    Tag               : {}
    TagsTable         :
    Name              : MyApplicationSecurityGroup1
    Etag              : W/"00000000-0000-0000-0000-000000000000"
    Id                : /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/MyResourceGroup/providers/Microsof
                        t.Network/applicationSecurityGroups/MyApplicationSecurityGroup1

    ProvisioningState : Succeeded
    ResourceGroupName : MyResourceGroup
    Location          : southcentralus
    ResourceGuid      :
    Type              : Microsoft.Network/applicationSecurityGroups
    Tag               : {}
    TagsTable         :
    Name              : MyApplicationSecurityGroup2
    Etag              : W/"00000000-0000-0000-0000-000000000000"
    Id                : /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/MyResourceGroup/providers/Microsof
                        t.Network/applicationSecurityGroups/MyApplicationSecurityGroup2
  description: |-
    The command above returns all application security groups that start with "MyApplicationSecurityGroup".
  summary: ""
parameters:
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  description: |+
    The resource name.

  defaultValue: None
  acceptWildcardCharacters: true
  pipelineInput: true
  position: Named
  aliases: ResourceName
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: ResourceGroupName
  description: |+
    The resource group name.

  defaultValue: None
  acceptWildcardCharacters: true
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Az.Network.Get-AzApplicationSecurityGroup
name: Get-AzApplicationSecurityGroup
description: |-
  The **Get-AzApplicationSecurityGroup** cmdlet gets an application security group.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  Module Name: Az.Network
  online version: https://docs.microsoft.com/en-us/powershell/module/az.network/get-azapplicationsecuritygroup
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Get-AzApplicationSecurityGroup.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Get-AzApplicationSecurityGroup.md
