### YamlMime:PowershellCmdlet
summary: |-
  Invoke network configuration diagnostic session for specified network profiles on target resource.
module: Az.Network
notes: |-
  Keywords: azure, azurerm, arm, resource, management, manager, network, networking, watcher, diagnostic, profile
inputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSNetworkWatcher" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSNetworkConfigurationDiagnosticResponse" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: New-AzNetworkWatcher
  href: ./New-AzNetworkWatcher.yml
- text: Get-AzNetworkWatcher
  href: ./Get-AzNetworkWatcher.yml
- text: Remove-AzNetworkWatcher
  href: ./Remove-AzNetworkWatcher.yml
- text: Get-AzNetworkWatcherNextHop
  href: ./Get-AzNetworkWatcherNextHop.yml
- text: Get-AzNetworkWatcherSecurityGroupView
  href: ./Get-AzNetworkWatcherSecurityGroupView.yml
- text: Get-AzNetworkWatcherTopology
  href: ./Get-AzNetworkWatcherTopology.yml
- text: Start-AzNetworkWatcherResourceTroubleshooting
  href: ./Start-AzNetworkWatcherResourceTroubleshooting.yml
- text: New-AzNetworkWatcherPacketCapture
  href: ./New-AzNetworkWatcherPacketCapture.yml
- text: New-AzPacketCaptureFilterConfig
  href: ./New-AzPacketCaptureFilterConfig.yml
- text: Get-AzNetworkWatcherPacketCapture
  href: ./Get-AzNetworkWatcherPacketCapture.yml
- text: Remove-AzNetworkWatcherPacketCapture
  href: ./Remove-AzNetworkWatcherPacketCapture.yml
- text: Stop-AzNetworkWatcherPacketCapture
  href: ./Stop-AzNetworkWatcherPacketCapture.yml
- text: New-AzNetworkWatcherProtocolConfiguration
  href: ./New-AzNetworkWatcherProtocolConfiguration.yml
- text: Test-AzNetworkWatcherIPFlow
  href: ./Test-AzNetworkWatcherIPFlow.yml
- text: Test-AzNetworkWatcherConnectivity
  href: ./Test-AzNetworkWatcherConnectivity.yml
- text: Stop-AzNetworkWatcherConnectionMonitor
  href: ./Stop-AzNetworkWatcherConnectionMonitor.yml
- text: Start-AzNetworkWatcherConnectionMonitor
  href: ./Start-AzNetworkWatcherConnectionMonitor.yml
- text: Set-AzNetworkWatcherConnectionMonitor
  href: ./Set-AzNetworkWatcherConnectionMonitor.yml
- text: Set-AzNetworkWatcherConfigFlowLog
  href: ./Set-AzNetworkWatcherConfigFlowLog.yml
- text: Remove-AzNetworkWatcherConnectionMonitor
  href: ./Remove-AzNetworkWatcherConnectionMonitor.yml
- text: New-AzNetworkWatcherConnectionMonitor
  href: ./New-AzNetworkWatcherConnectionMonitor.yml
- text: Get-AzNetworkWatcherTroubleshootingResult
  href: ./Get-AzNetworkWatcherTroubleshootingResult.yml
- text: Get-AzNetworkWatcherReachabilityReport
  href: ./Get-AzNetworkWatcherReachabilityReport.yml
- text: Get-AzNetworkWatcherReachabilityProvidersList
  href: ./Get-AzNetworkWatcherReachabilityProvidersList.yml
- text: Get-AzNetworkWatcherFlowLogStatus
  href: ./Get-AzNetworkWatcherFlowLogStatus.yml
- text: Get-AzNetworkWatcherConnectionMonitorReport
  href: ./Get-AzNetworkWatcherConnectionMonitorReport.yml
- text: Get-AzNetworkWatcherConnectionMonitor
  href: ./Get-AzNetworkWatcherConnectionMonitor.yml
syntaxes:
- >-
  Invoke-AzNetworkWatcherNetworkConfigurationDiagnostic -NetworkWatcher <PSNetworkWatcher>

   -TargetResourceId <String> [-VerbosityLevel <String>]

   -Profile <System.Collections.Generic.List`1[Microsoft.Azure.Commands.Network.Models.PSNetworkConfigurationDiagnosticProfile]>

   [-AsJob] [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
- >-
  Invoke-AzNetworkWatcherNetworkConfigurationDiagnostic -NetworkWatcherName <String> -ResourceGroupName <String>

   -TargetResourceId <String> [-VerbosityLevel <String>]

   -Profile <System.Collections.Generic.List`1[Microsoft.Azure.Commands.Network.Models.PSNetworkConfigurationDiagnosticProfile]>

   [-AsJob] [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
- >-
  Invoke-AzNetworkWatcherNetworkConfigurationDiagnostic -Location <String> -TargetResourceId <String>

   [-VerbosityLevel <String>]

   -Profile <System.Collections.Generic.List`1[Microsoft.Azure.Commands.Network.Models.PSNetworkConfigurationDiagnosticProfile]>

   [-AsJob] [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
- >-
  Invoke-AzNetworkWatcherNetworkConfigurationDiagnostic -ResourceId <String> -TargetResourceId <String>

   [-VerbosityLevel <String>]

   -Profile <System.Collections.Generic.List`1[Microsoft.Azure.Commands.Network.Models.PSNetworkConfigurationDiagnosticProfile]>

   [-AsJob] [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
examples:
- title: 'Example 1: Invoke network configuration diagnostic session for VM and specified network profile'
  code: |-
    PS C:\> $profile = New-AzNetworkWatcherNetworkConfigurationDiagnosticProfile -Direction Inbound -Protocol Tcp -Source 10.1.1.4 -Destination * -DestinationPort 50
    PS C:\> Invoke-AzNetworkWatcherNetworkConfigurationDiagnostic -Location eastus -TargetResourceId /subscriptions/61cc8a98-a8be-4bfe-a04e-0b461f93fe35/resourceGroups/NwRgEastUS/providers/Microsoft.Compute/virtualMachines/vm1 -Profile $profile

    Results : [
                {
                  "Profile": {
                    "Direction": "Inbound",
                    "Protocol": "Tcp",
                    "Source": "10.1.1.4",
                    "Destination": "*",
                    "DestinationPort": "50"
                  },
                  "NetworkSecurityGroupResult": {
                    "SecurityRuleAccessResult": "Allow",
                    "EvaluatedNetworkSecurityGroups": [
                      {
                        "NetworkSecurityGroupId": "/subscriptions/61cc8a98-a8be-4bfe-a04e-0b461f93fe35/resourceGroups/clean
              upservice/providers/Microsoft.Network/networkSecurityGroups/rg-cleanupservice-nsg1",
                        "MatchedRule": {
                          "RuleName": "UserRule_Cleanuptool-Allow-4001",
                          "Action": "Allow"
                        },
                        "RulesEvaluationResult": [
                          {
                            "Name": "UserRule_Cleanuptool-Allow-100",
                            "ProtocolMatched": true,
                            "SourceMatched": false,
                            "SourcePortMatched": true,
                            "DestinationMatched": true,
                            "DestinationPortMatched": false
                          },
  description: ""
  summary: ""
parameters:
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: AsJob
  description: |+
    Run cmdlet in the background

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with Azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Location
  isRequired: true
  description: |+
    Location of the network watcher.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSNetworkWatcher" data-throw-if-not-resolved="False" />
  name: NetworkWatcher
  isRequired: true
  description: |+
    The network watcher resource.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: NetworkWatcherName
  isRequired: true
  description: |+
    The name of network watcher.

  defaultValue: None
  position: Named
  aliases: Name
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Azure.Commands.Network.Models.PSNetworkConfigurationDiagnosticProfile" data-throw-if-not-resolved="False" /><span>]</span>
  name: Profile
  isRequired: true
  description: |+
    List of network configuration diagnostic profiles.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: ResourceGroupName
  isRequired: true
  description: |+
    The name of the network watcher resource group.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: ResourceId
  isRequired: true
  description: |+
    Resource ID.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: TargetResourceId
  isRequired: true
  description: |+
    The ID of the target resource to perform network configuration diagnostic.
    Valid options are VM, NetworkInterface, VMSS/NetworkInterface and Application Gateway.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: VerbosityLevel
  description: |+
    Verbosity level.
    Accepted values are 'Normal', 'Minimum', 'Full'.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Az.Network.Invoke-AzNetworkWatcherNetworkConfigurationDiagnostic
name: Invoke-AzNetworkWatcherNetworkConfigurationDiagnostic
description: |-
  The Invoke-AzNetworkWatcherNetworkConfigurationDiagnostic cmdlet invoke network configuration diagnostic session for specified network profiles on target resource.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  Module Name: Az.Network
  online version: https://docs.microsoft.com/en-us/powershell/module/az.network/invoke-aznetworkwatchernetworkconfigurationdiagnostic
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Invoke-AzNetworkWatcherNetworkConfigurationDiagnostic.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Invoke-AzNetworkWatcherNetworkConfigurationDiagnostic.md
