### YamlMime:PowershellCmdlet
summary: |-
  Creates an authentication certificate for an application gateway.
module: Az.Network
notes: |-
  * Keywords: azure, azurerm, arm, resource, management, manager, network, networking
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationGatewayAuthenticationCertificate" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Add-AzApplicationGatewayAuthenticationCertificate
  href: ./Add-AzApplicationGatewayAuthenticationCertificate.yml
- text: Get-AzApplicationGatewayAuthenticationCertificate
  href: ./Get-AzApplicationGatewayAuthenticationCertificate.yml
- text: Remove-AzApplicationGatewayAuthenticationCertificate
  href: ./Remove-AzApplicationGatewayAuthenticationCertificate.yml
- text: Set-AzApplicationGatewayAuthenticationCertificate
  href: ./Set-AzApplicationGatewayAuthenticationCertificate.yml
syntaxes:
- >-
  New-AzApplicationGatewayAuthenticationCertificate -Name <String> -CertificateFile <String>

   [-DefaultProfile <IAzureContextContainer>] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: 'Example 1: Create an authentication certificate'
  code: |-
    PS C:\> $cert = New-AzApplicationGatewayAuthenticationCertificate -Name "cert01" -CertificateFile "C:\cert.cer"
  description: |-
    The first command creates authentication certificate named cert01.
  summary: ""
parameters:
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: CertificateFile
  isRequired: true
  description: |+
    Specifies the path of the authentication certificate.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    Specifies a name for the authentication certificate.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Az.Network.New-AzApplicationGatewayAuthenticationCertificate
name: New-AzApplicationGatewayAuthenticationCertificate
description: |-
  The **New-AzApplicationGatewayAuthenticationCertificate** cmdlet creates an authentication certificate for an Azure application gateway.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  Module Name: Az.Network
  ms.assetid: 4736FA0D-222D-4D69-BCBD-72036303A20E
  online version: https://docs.microsoft.com/en-us/powershell/module/az.network/new-azapplicationgatewayauthenticationcertificate
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/New-AzApplicationGatewayAuthenticationCertificate.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/New-AzApplicationGatewayAuthenticationCertificate.md
