### YamlMime:PowershellCmdlet
summary: |-
  Updates a route configuration for a route table.
module: Az.Network
notes: ""
inputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSRouteTable" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSRouteTable" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Add-AzRouteConfig
  href: ./Add-AzRouteConfig.yml
- text: Get-AzRouteConfig
  href: ./Get-AzRouteConfig.yml
- text: New-AzRouteConfig
  href: ./New-AzRouteConfig.yml
- text: Remove-AzRouteConfig
  href: ./Remove-AzRouteConfig.yml
syntaxes:
- >-
  Set-AzRouteConfig -RouteTable <PSRouteTable> [-Name <String>] [-AddressPrefix <String>] [-NextHopType <String>]

   [-NextHopIpAddress <String>] [-DefaultProfile <IAzureContextContainer>] [-WhatIf] [-Confirm]

   [<CommonParameters>]
examples:
- title: 'Example 1: Modify a route'
  code: |-
    PS C:\>Get-AzRouteTable -ResourceGroupName "ResourceGroup11" -Name "RouteTable01" | Set-AzRouteConfig -Name "Route02" -AddressPrefix 10.4.0.0/16 -NextHopType VnetLocal | Set-AzRouteTable
    Name              : Routetable01
    ResourceGroupName : ResourceGroup11
    Location          : eastus
    Id                : /subscriptions/xxxx-xxxx-xxxx-xxxx/resourceGroups/ResourceGroup11/providers/Microsoft.Networ
                        k/routeTables/RouteTable01
    Etag              : W/"58c2922e-9efe-4554-a457-956ef44bc718"
    ProvisioningState : Succeeded
    Tags              : 
    Routes            : [
                          {
                            "Name": "Route07",
                            "Etag": "W/\"58c2922e-9efe-4554-a457-956ef44bc718\"",
                            "Id": "/subscriptions/xxxx-xxxx-xxxx-xxxx/resourceGroups/ResourceGroup11/providers/Micro
                        soft.Network/routeTables/Routetable01/routes/Route07",
                            "AddressPrefix": "10.1.0.0/16",
                            "NextHopType": "VnetLocal",
                            "NextHopIpAddress": null, 
                            "ProvisioningState": "Succeeded"
                          },
                          {
                            "Name": "route02",
                            "Etag": "W/\"58c2922e-9efe-4554-a457-956ef44bc718\"",
                            "Id": "/subscriptions/xxxx-xxxx-xxxx-xxxx/resourceGroups/ResourceGroup11/providers/Micro
                        soft.Network/routeTables/routetable01/routes/route02",
                            "AddressPrefix": "10.4.0.0/16",
                            "NextHopType": "VnetLocal",
                            "NextHopIpAddress": null, 
                            "ProvisioningState": "Succeeded"
                          }
                        ] 
    Subnets           : []
  description: |-
    This command gets the route table named RouteTable01 by using the Get-AzRouteTable cmdlet.
    The command passes that table to the current cmdlet by using the pipeline operator.
    The current cmdlet modifies the route named Route02, and then passes the result to the **Set-AzRouteTable** cmdlet, which updates the table to reflect your changes.
  summary: ""
parameters:
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: AddressPrefix
  description: |+
    Specifies the destination, in Classless Interdomain Routing (CIDR) format, to which the route applies.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  description: |+
    Specifies the name of the route that this cmdlet modifies.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: NextHopIpAddress
  description: |+
    Specifies the IP address of a virtual appliance that you add to your Azure virtual network.
    This route forwards packets to that address.
    Specify this parameter only if you specify a value of VirtualAppliance for the *NextHopType* parameter.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: NextHopType
  description: |+
    Specifies how this route forwards packets.
    The acceptable values for this parameter are:
    - Internet.
    The default Internet gateway provided by Azure. 
    - None.
    If you specify this value, the route does not forward packets. 
    - VirtualAppliance.
    A virtual appliance that you add to your Azure virtual network. 
    - VirtualNetworkGateway.
    An Azureserver-to-server virtual private network gateway. 
    - VnetLocal.
    The local virtual network.
    If you have two subnets, 10.1.0.0/16 and 10.2.0.0/16 in the same virtual network, select a value of VnetLocal for each subnet to forward to the other subnet.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSRouteTable" data-throw-if-not-resolved="False" />
  name: RouteTable
  isRequired: true
  description: |+
    Specifies the route table with which this route is associated.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs. The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Az.Network.Set-AzRouteConfig
name: Set-AzRouteConfig
description: |-
  The **Set-AzRouteConfig** cmdlet updates a route configuration for a route table.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  Module Name: Az.Network
  ms.assetid: 6E967F9C-949E-4485-9B57-FC4F523D5DC9
  online version: https://docs.microsoft.com/en-us/powershell/module/az.network/set-azrouteconfig
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Set-AzRouteConfig.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Set-AzRouteConfig.md
