### YamlMime:PowershellCmdlet
summary: |-
  Updates the inheritance of Main site Access Restiction config to SCM Site for an Azure Web App.
module: Az.Websites
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.WebApps.Models.PSAccessRestrictionConfig" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-AzWebAppAccessRestrictionConfig
  href: ./Get-AzWebAppAccessRestrictionConfig.yml
- text: Add-AzWebAppAccessRestrictionRule
  href: ./Add-AzWebAppAccessRestrictionRule.yml
- text: Remove-AzWebAppAccessRestrictionRule
  href: ./Remove-AzWebAppAccessRestrictionRule.yml
syntaxes:
- >-
  Update-AzWebAppAccessRestrictionConfig [-ResourceGroupName] <String> [-Name] <String>

   [-ScmSiteUseMainSiteRestrictionConfig] [-SlotName <String>] [-PassThru]

   [-DefaultProfile <IAzureContextContainer>] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Update-AzWebAppAccessRestrictionConfig [-PassThru] -InputObject <PSAccessRestrictionConfig>

   [-DefaultProfile <IAzureContextContainer>] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: 'Example 1: Update a Web App SCM Site to use Access Restrictions from Main Site'
  code: |-
    PS C:\>Set-AzWebAppAccessRestriction -ResourceGroupName "Default-Web-WestUS" -Name "ContosoSite" -ScmSiteUseMainSiteRestrictionConfig
  description: |-
    This command updates a Web App named ContosoSite that belongs to the resource group Default-Web-WestUS to use access restriction config of main site on the scm site.
  summary: ""
parameters:
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.WebApps.Models.PSAccessRestrictionConfig" data-throw-if-not-resolved="False" />
  name: InputObject
  isRequired: true
  description: |+
    The access restriction config object

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    WebApp Name

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: PassThru
  description: |+
    Return the access restriction config object.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: ResourceGroupName
  isRequired: true
  description: |+
    Resource Group Name

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: ScmSiteUseMainSiteRestrictionConfig
  isRequired: true
  description: |+
    Scm site inherits rules set on Main site.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: SlotName
  description: |+
    Deployment Slot name.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs. The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Az.Websites.Update-AzWebAppAccessRestrictionConfig
name: Update-AzWebAppAccessRestrictionConfig
description: |-
  The **Update-AzWebAppAccessRestrictionConfig** cmdlet updates Access Restriction config for an Azure Web App.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Websites.dll-Help.xml
  Module Name: Az.Websites
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Websites/Websites/help/Update-AzWebAppAccessRestrictionConfig.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Websites/Websites/help/Update-AzWebAppAccessRestrictionConfig.md
