### YamlMime:PowershellCmdlet
summary: |-
  Get or list app configuration stores.
module: Az.AppConfiguration
notes: |-
  ALIASES

  COMPLEX PARAMETER PROPERTIES

  To create the parameters described below, construct a hash table containing the appropriate properties. For information on hash tables, run Get-Help about_Hash_Tables.


  INPUTOBJECT <IAppConfigurationIdentity>: Identity Parameter
    - `[ConfigStoreName <String>]`: The name of the configuration store.
    - `[GroupName <String>]`: The name of the private link resource group.
    - `[Id <String>]`: Resource identity path
    - `[PrivateEndpointConnectionName <String>]`: Private endpoint connection name
    - `[ResourceGroupName <String>]`: The name of the resource group to which the container registry belongs.
    - `[SubscriptionId <String>]`: The Microsoft Azure subscription ID.
inputs:
- name: <xref href="Microsoft.Azure.PowerShell.Cmdlets.AppConfiguration.Models.IAppConfigurationIdentity" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.PowerShell.Cmdlets.AppConfiguration.Models.Api20200601.IConfigurationStore" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- Get-AzAppConfigurationStore [-SubscriptionId <String[]>] [-DefaultProfile <PSObject>] [<CommonParameters>]
- >-
  Get-AzAppConfigurationStore -Name <String> -ResourceGroupName <String> [-SubscriptionId <String[]>]

   [-DefaultProfile <PSObject>] [<CommonParameters>]
- >-
  Get-AzAppConfigurationStore -InputObject <IAppConfigurationIdentity> [-DefaultProfile <PSObject>]

   [<CommonParameters>]
- >-
  Get-AzAppConfigurationStore -ResourceGroupName <String> [-SubscriptionId <String[]>]

   [-DefaultProfile <PSObject>] [<CommonParameters>]
examples:
- title: 'Example 1: List all app configuration stores under a subscription'
  code: |-
    PS C:\> Get-AzAppConfigurationStore

    Location Name               Type
    -------- ----               ----
    eastus   appconfig-test01   Microsoft.AppConfiguration/configurationStores
    eastus   contoso-app-config Microsoft.AppConfiguration/configurationStores
  description: |-
    This command lists all app configuration stores under a subscription.
  summary: ""
- title: 'Example 2: List all app configuration stores under a resource group'
  code: |-
    PS C:\> Get-AzAppConfigurationStore -ResourceGroupName azpwsh-manual-test

    Location Name             Type
    -------- ----             ----
    eastus   appconfig-test01 Microsoft.AppConfiguration/configurationStores
    eastus   appconfig-test02 Microsoft.AppConfiguration/configurationStores
  description: |-
    This command lists all app configuration stores under a resource group.
  summary: ""
- title: 'Example 3: Get an app configuration store by name'
  code: |-
    PS C:\> Get-AzAppConfigurationStore -ResourceGroupName azpwsh-manual-test -Name appconfig-test01

    Location Name             Type
    -------- ----             ----
    eastus   appconfig-test01 Microsoft.AppConfiguration/configurationStores
  description: |-
    This command gets an app configuration store by name.
  summary: ""
- title: 'Example 4: Get an app configuration store by pipeline'
  code: |-
    PS C:\> Get-AzAppConfigurationStore -ResourceGroupName azpwsh-manual-test -Name appconfig-test01 | Get-AzAppConfigurationStore

    Location Name             Type
    -------- ----             ----
    eastus   appconfig-test01 Microsoft.AppConfiguration/configurationStores
  description: |-
    This command gets an app configuration store by pipeline.
  summary: ""
parameters:
- type: <xref href="System.Management.Automation.PSObject" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with Azure.

  defaultValue: None
  position: Named
  aliases: AzureRMContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.PowerShell.Cmdlets.AppConfiguration.Models.IAppConfigurationIdentity" data-throw-if-not-resolved="False" />
  name: InputObject
  isRequired: true
  description: |+
    Identity Parameter
    To construct, see NOTES section for INPUTOBJECT properties and create a hash table.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    The name of the configuration store.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: ResourceGroupName
  isRequired: true
  description: |+
    The name of the resource group to which the container registry belongs.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: SubscriptionId
  description: |+
    The Microsoft Azure subscription ID.

  defaultValue: (Get-AzContext).Subscription.Id
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Az.AppConfiguration.Get-AzAppConfigurationStore
name: Get-AzAppConfigurationStore
description: |-
  Get or list app configuration stores.
metadata:
  external help file: ""
  Module Name: Az.AppConfiguration
  online version: https://docs.microsoft.com/en-us/powershell/module/az.appconfiguration/get-azappconfigurationstore
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/AppConfiguration/help/Get-AzAppConfigurationStore.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/AppConfiguration/help/Get-AzAppConfigurationStore.md
