### YamlMime:PowershellCmdlet
summary: |-
  Regenerates an access key for the specified configuration store.
module: Az.AppConfiguration
notes: |-
  ALIASES

  COMPLEX PARAMETER PROPERTIES

  To create the parameters described below, construct a hash table containing the appropriate properties. For information on hash tables, run Get-Help about_Hash_Tables.


  INPUTOBJECT <IAppConfigurationIdentity>: Identity Parameter
    - `[ConfigStoreName <String>]`: The name of the configuration store.
    - `[GroupName <String>]`: The name of the private link resource group.
    - `[Id <String>]`: Resource identity path
    - `[PrivateEndpointConnectionName <String>]`: Private endpoint connection name
    - `[ResourceGroupName <String>]`: The name of the resource group to which the container registry belongs.
    - `[SubscriptionId <String>]`: The Microsoft Azure subscription ID.
inputs:
- name: <xref href="Microsoft.Azure.PowerShell.Cmdlets.AppConfiguration.Models.IAppConfigurationIdentity" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.PowerShell.Cmdlets.AppConfiguration.Models.Api20200601.IApiKey" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  New-AzAppConfigurationStoreKey -Name <String> -ResourceGroupName <String> -Id <String>

   [-SubscriptionId <String>] [-DefaultProfile <PSObject>] [-Confirm] [-WhatIf] [<CommonParameters>]
- >-
  New-AzAppConfigurationStoreKey -InputObject <IAppConfigurationIdentity> -Id <String>

   [-DefaultProfile <PSObject>] [-Confirm] [-WhatIf] [<CommonParameters>]
examples:
- title: 'Example 1: Regenerate key of an app configuration store'
  code: |-
    PS C:\> $keys= Get-AzAppConfigurationStoreKey -Name appconfig-test01 -ResourceGroupName azpwsh-manual-test
    PS C:\> New-AzAppConfigurationStoreKey -Name appconfig-test01 -ResourceGroupName azpwsh-manual-test -Id $keys[0].id

    ConnectionString                                                                                                                     LastModified        Name      ReadOnly Value
    ----------------                                                                                                                     ------------        ----      -------- -----
    Endpoint=https://appconfig-test01.azconfig.io;Id=09pv-l0-s0:opFCQMC6+9485xJgN5Ws;Secret=GcoE9e9t7GLRNJ910M46IrbHO/Vg0tt4HujRdsaCoTY= 5/8/2020 5:47:15 AM Secondary False    GcoE9e9t7GLRNJ910M46IrbHO/Vg0tt4HujRdsaCoTY=
  description: |-
    This command regenerate key of an app configuration store.
  summary: ""
- title: 'Example 2: Regenerate key of an app configuration store by object'
  code: |-
    PS C:\> $app= New-AzAppConfigurationStore -Name appconfig-test10 -ResourceGroupName azpwsh-manual-test
    PS C:\> $keys= Get-AzAppConfigurationStoreKey -Name appconfig-test01 -ResourceGroupName azpwsh-manual-test
    PS C:\> New-AzAppConfigurationStoreKey -InputObject $app -Id $keys[0].id
    ConnectionString                                                                                                                     LastModified        Name      ReadOnly Value
    ----------------                                                                                                                     ------------        ----      -------- -----
    Endpoint=https://appconfig-test01.azconfig.io;Id=09pv-l0-s0:opFCQMC6+9485xJgN5Ws;Secret=GcoE9e9t7GLRNJ910M46IrbHO/Vg0tt4HujRdsaCoTY= 5/8/2020 5:47:15 AM Secondary False    GcoE9e9t7GLRNJ910M46IrbHO/Vg0tt4HujRdsaCoTY=
  description: |-
    This command regenerate key of an app configuration store by object.
  summary: ""
parameters:
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.PSObject" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with Azure.

  defaultValue: None
  position: Named
  aliases: AzureRMContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Id
  isRequired: true
  description: |+
    The id of the key to regenerate.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.PowerShell.Cmdlets.AppConfiguration.Models.IAppConfigurationIdentity" data-throw-if-not-resolved="False" />
  name: InputObject
  isRequired: true
  description: |+
    Identity Parameter
    To construct, see NOTES section for INPUTOBJECT properties and create a hash table.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    The name of the configuration store.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: ResourceGroupName
  isRequired: true
  description: |+
    The name of the resource group to which the container registry belongs.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: SubscriptionId
  description: |+
    The Microsoft Azure subscription ID.

  defaultValue: (Get-AzContext).Subscription.Id
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Az.AppConfiguration.New-AzAppConfigurationStoreKey
name: New-AzAppConfigurationStoreKey
description: |-
  Regenerates an access key for the specified configuration store.
metadata:
  external help file: ""
  Module Name: Az.AppConfiguration
  online version: https://docs.microsoft.com/en-us/powershell/module/az.appconfiguration/new-azappconfigurationstorekey
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/AppConfiguration/help/New-AzAppConfigurationStoreKey.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/AppConfiguration/help/New-AzAppConfigurationStoreKey.md
