### YamlMime:PowershellCmdlet
summary: |-
  Removes a DNS record from a local record set object.
module: Az.Dns
notes: ""
inputs:
- name: <xref href="Microsoft.Azure.Commands.Dns.DnsRecordSet" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="System.UInt16" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="System.Byte" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Dns.DnsRecordSet" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Add-AzDnsRecordConfig
  href: ./Add-AzDnsRecordConfig.yml
- text: Get-AzDnsRecordSet
  href: ./Get-AzDnsRecordSet.yml
- text: Set-AzDnsRecordSet
  href: ./Set-AzDnsRecordSet.yml
syntaxes:
- >-
  Remove-AzDnsRecordConfig -RecordSet <DnsRecordSet> -Ipv4Address <String>

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
- >-
  Remove-AzDnsRecordConfig -RecordSet <DnsRecordSet> -Ipv6Address <String>

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
- >-
  Remove-AzDnsRecordConfig -RecordSet <DnsRecordSet> -Nsdname <String> [-DefaultProfile <IAzureContextContainer>]

   [<CommonParameters>]
- >-
  Remove-AzDnsRecordConfig -RecordSet <DnsRecordSet> -Exchange <String> -Preference <UInt16>

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
- >-
  Remove-AzDnsRecordConfig -RecordSet <DnsRecordSet> -Ptrdname <String>

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
- >-
  Remove-AzDnsRecordConfig -RecordSet <DnsRecordSet> -Value <String> [-DefaultProfile <IAzureContextContainer>]

   [<CommonParameters>]
- >-
  Remove-AzDnsRecordConfig -RecordSet <DnsRecordSet> -Priority <UInt16> -Target <String> -Port <UInt16>

   -Weight <UInt16> [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
- >-
  Remove-AzDnsRecordConfig -RecordSet <DnsRecordSet> -Cname <String> [-DefaultProfile <IAzureContextContainer>]

   [<CommonParameters>]
- >-
  Remove-AzDnsRecordConfig -RecordSet <DnsRecordSet> -CaaFlags <Byte> -CaaTag <String> -CaaValue <String>

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
examples:
- title: 'Example 1: Remove an A record from a record set'
  code: |-
    PS C:\> $RecordSet = Get-AzDnsRecordSet -Name "www" -RecordType A -ResouceGroupName "MyResourceGroup" -ZoneName "myzone.com"
    PS C:\> Remove-AzDnsRecordConfig -RecordSet $RecordSet -Ipv4Address 1.2.3.4
    PS C:\> Set-AzDnsRecordSet -RecordSet $RecordSet

    # The above sequence can also be piped:

    PS C:\> Get-AzDnsRecordSet -Name "www" -RecordType A -ResouceGroupName "MyResourceGroup" -ZoneName "myzone.com" | Remove-AzDnsRecordConfig -Ipv4Address 1.2.3.4 | Set-AzDnsRecordSet
  description: |-
    This example removes an A record from an existing record set.
    If this is the only record in the record set, the result will be an empty record set.
    To remove a record set entirely, see Remove-AzDnsRecordSet.
  summary: ""
- title: 'Example 2: Remove an AAAA record from a record set'
  code: |-
    PS C:\> $RecordSet = Get-AzDnsRecordSet -Name "www" -RecordType AAAA -ResouceGroupName "MyResourceGroup" -ZoneName "myzone.com"
    PS C:\> Remove-AzDnsRecordConfig -RecordSet $RecordSet -Ipv6Address 2001:DB80:4009:1803::1005
    PS C:\> Set-AzDnsRecordSet -RecordSet $RecordSet

    # The above sequence can also be piped:

    PS C:\> Get-AzDnsRecordSet -Name "www" -RecordType AAAA -ResouceGroupName "MyResourceGroup" -ZoneName "myzone.com" | Remove-AzDnsRecordConfig -Ipv6Address 2001:DB80:4009:1803::1005 | Set-AzDnsRecordSet
  description: |-
    This example removes an AAAA record from an existing record set.
    If this is the only record in the record set, the result will be an empty record set.
    To remove a record set entirely, see Remove-AzDnsRecordSet.
  summary: ""
- title: 'Example 3: Remove a CNAME record from a record set'
  code: |-
    PS C:\> $RecordSet = Get-AzDnsRecordSet -Name "www" -RecordType CNAME -ResouceGroupName "MyResourceGroup" -ZoneName "myzone.com"
    PS C:\> Remove-AzDnsRecordConfig -RecordSet $RecordSet -Cname contoso.com
    PS C:\> Set-AzDnsRecordSet -RecordSet $RecordSet

    # The above sequence can also be piped:

    PS C:\> Get-AzDnsRecordSet -Name "www" -RecordType CNAME -ResouceGroupName "MyResourceGroup" -ZoneName "myzone.com" | Remove-AzDnsRecordConfig -Cname contoso.com | Set-AzDnsRecordSet
  description: |-
    This example removes a CNAME record from an existing record set.
    Because a CNAME record set can contain at most one record, the result is an empty record set.
  summary: ""
- title: 'Example 4: Remove an MX record from a record set'
  code: |-
    PS C:\> $RecordSet = Get-AzDnsRecordSet -Name "@" -RecordType MX -ResouceGroupName "MyResourceGroup" -ZoneName "myzone.com"
    PS C:\> Remove-AzDnsRecordConfig -Exchange mail.microsoft.com -Preference 5 -RecordSet $RecordSet
    PS C:\> Set-AzDnsRecordSet -RecordSet $RecordSet

    # The above sequence can also be piped:

    PS C:\> Get-AzDnsRecordSet -Name "@" -RecordType MX -ResouceGroupName "MyResourceGroup" -ZoneName "myzone.com" | Remove-AzDnsRecordConfig -Exchange mail.microsoft.com -Preference 5 | Set-AzDnsRecordSet
  description: |-
    This example removes an MX record from an existing record set.
    The record name "@" indicates a record set at the zone apex.
    If this is the only record in the record set, the result is an empty record set.
    To remove a record set entirely, see Remove-AzDnsRecordSet.
  summary: ""
- title: 'Example 5: Remove an NS record from a record set'
  code: |-
    PS C:\> $RecordSet = Get-AzDnsRecordSet -Name "abc" -RecordType NS -ResouceGroupName "MyResourceGroup" -ZoneName "myzone.com"
    PS C:\> Remove-AzDnsRecordConfig -Nsdname ns1.myzone.com -RecordSet $RecordSet
    PS C:\> Set-AzDnsRecordSet -RecordSet $RecordSet

    # The above sequence can also be piped:

    PS C:\> Get-AzDnsRecordSet -Name "abc" -RecordType NS -ResouceGroupName "MyResourceGroup" -ZoneName "myzone.com" | Remove-AzDnsRecordConfig -Nsdname "ns1.myzone.com" | Set-AzDnsRecordSet
  description: |-
    This example removes an NS record from an existing record set.
    If this is the only record in the record set, the result is an empty record set.
    To remove a record set entirely, see Remove-AzDnsRecordSet.
  summary: ""
- title: 'Example 6: Remove a PTR record from a record set'
  code: |-
    PS C:\> $RecordSet = Get-AzDnsRecordSet -Name "4" -RecordType PTR -ResouceGroupName "MyResourceGroup" -ZoneName 3.2.1.in-addr.arpa
    PS C:\> Remove-AzDnsRecordConfig -Ptrdname www.contoso.com -RecordSet $RecordSet
    PS C:\> Set-AzDnsRecordSet -RecordSet $RecordSet

    # The above sequence can also be piped:

    PS C:\> Get-AzDnsRecordSet -Name "4" -RecordType PTR -ResouceGroupName "MyResourceGroup" -ZoneName "3.2.1.in-addr.arpa" | Remove-AzDnsRecordConfig -Ptrdname www.contoso.com | Set-AzDnsRecordSet
  description: |-
    This example removes a PTR record from an existing record set.
    If this is the only record in the record set, the result is an empty record set.
    To remove a record set entirely, see Remove-AzDnsRecordSet.
  summary: ""
- title: 'Example 7: Remove an SRV record from a record set'
  code: |-
    PS C:\> $RecordSet = Get-AzDnsRecordSet -Name "_sip._tcp" -RecordType SRV -ResouceGroupName "MyResourceGroup" -ZoneName "myzone.com"
    PS C:\> Remove-AzDnsRecordConfig -RecordSet $RecordSet -Priority 0 -Weight 5 -Port 8080 -Target target.example.com
    PS C:\> Set-AzDnsRecordSet -RecordSet $RecordSet

    # The above sequence can also be piped:

    PS C:\> Get-AzDnsRecordSet -Name "_sip._tcp" -RecordType SRV -ResouceGroupName "MyResourceGroup" -ZoneName "myzone.com" | Remove-AzDnsRecordConfig -Priority 0 -Weight 5 -Port 8080 -Target target.example.com  | Set-AzDnsRecordSet
  description: |-
    This example removes an SRV record from an existing record set.
    If this is the only record in the record set, the result is an empty record set.
    To remove a record set entirely, see Remove-AzDnsRecordSet.
  summary: ""
- title: 'Example 8: Remove a TXT record from a record set'
  code: |-
    PS C:\> $RecordSet = Get-AzDnsRecordSet -Name "text" -RecordType TXT -ResouceGroupName "MyResourceGroup" -ZoneName "myzone.com"
    PS C:\> Remove-AzDnsRecordConfig -RecordSet $RecordSet -Value "This is a TXT Record"
    PS C:\> Set-AzDnsRecordSet -RecordSet $RecordSet

    # The above sequence can also be piped:

    PS C:\> Get-AzDnsRecordSet -Name "text" -RecordType TXT -ResouceGroupName "MyResourceGroup" -ZoneName "myzone.com" | Remove-AzDnsRecordConfig -Value "This is a TXT Record"  | Set-AzDnsRecordSet
  description: |-
    This example removes a TXT record from an existing record set.
    If this is the only record in the record set, the result is an empty record set.
    To remove a record set entirely, see Remove-AzDnsRecordSet.
  summary: ""
parameters:
- type: <xref href="System.Byte" data-throw-if-not-resolved="False" />
  name: CaaFlags
  isRequired: true
  description: |+
    The flags for the CAA record to add. Must be a number between 0 and 255.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: CaaTag
  isRequired: true
  description: |+
    The tag field of the CAA record to add.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: CaaValue
  isRequired: true
  description: |+
    The value field for the CAA record to add.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Cname
  isRequired: true
  description: |+
    Specifies the domain name for a canonical name (CNAME) record.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with azure

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Exchange
  isRequired: true
  description: |+
    Specifies the mail exchange server name for a mail exchange (MX) record.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Ipv4Address
  isRequired: true
  description: |+
    Specifies an IPv4 address for an A record.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Ipv6Address
  isRequired: true
  description: |+
    Specifies an IPv6 address for an AAAA record.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Nsdname
  isRequired: true
  description: |+
    Specifies the name server for a name server (NS) record.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.UInt16" data-throw-if-not-resolved="False" />
  name: Port
  isRequired: true
  description: |+
    Specifies the port for a service (SRV) record.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.UInt16" data-throw-if-not-resolved="False" />
  name: Preference
  isRequired: true
  description: |+
    Specifies the preference for an MX record.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.UInt16" data-throw-if-not-resolved="False" />
  name: Priority
  isRequired: true
  description: |+
    Specifies the priority for an SRV record.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Ptrdname
  isRequired: true
  description: |+
    Specifies the target domain name of a pointer (PTR) record.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Dns.DnsRecordSet" data-throw-if-not-resolved="False" />
  name: RecordSet
  isRequired: true
  description: |+
    Specifies the **RecordSet** object that contains the record to remove.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Target
  isRequired: true
  description: |+
    Specifies the target for an SRV record.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Value
  isRequired: true
  description: |+
    Specifies the value for a TXT record.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.UInt16" data-throw-if-not-resolved="False" />
  name: Weight
  isRequired: true
  description: |+
    Specifies the weight for an SRV record.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Az.Dns.Remove-AzDnsRecordConfig
name: Remove-AzDnsRecordConfig
description: |-
  The **Remove-AzDnsRecordConfig** cmdlet removes a Domain Name System (DNS) record from a record set.
  The **RecordSet** object is an offline object, and changes to it do not change the DNS responses until after you run the Set-AzDnsRecordSet cmdlet to persist the change to the Microsoft Azure DNS service.
  To remove a record, all the fields for that record type must match exactly.
  You cannot add or remove SOA records.
  SOA records are automatically created when a DNS zone is created and automatically deleted when the DNS zone is deleted.
  You can pass the **RecordSet** object to this cmdlet as a parameter or by using the pipeline operator.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Dns.dll-Help.xml
  Module Name: Az.Dns
  ms.assetid: D1A2326C-CD41-45A6-B37A-FC6176193B01
  online version: https://docs.microsoft.com/en-us/powershell/module/az.dns/remove-azdnsrecordconfig
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Dns/Dns/help/Remove-AzDnsRecordConfig.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Dns/Dns/help/Remove-AzDnsRecordConfig.md
