### YamlMime:PowershellCmdlet
summary: |-
  Gets the log of a deployment script execution.
module: Az.Resources
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Azure.Commands.ResourceManager.Cmdlets.SdkModels.PsDeploymentScript" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.ResourceManager.Cmdlets.SdkModels.PsDeploymentScriptLog" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Get-AzDeploymentScriptLog [-ResourceGroupName] <String> [-Name] <String> [[-Tail] <Int32>]

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
- >-
  Get-AzDeploymentScriptLog [-DeploymentScriptResourceId] <String> [[-Tail] <Int32>]

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
- >-
  Get-AzDeploymentScriptLog [-DeploymentScriptObject] <PsDeploymentScript> [[-Tail] <Int32>]

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    PS C:\> Get-AzDeploymentScriptLog -Name MyDeploymentScript -ResourceGroupName DS-TestRg
  description: |-
    Gets the log of a deployment script with the name MyDeploymentScript in resource group DS-TestRG.
  summary: ""
- title: Example 2
  code: |-
    PS C:\> Get-AzDeploymentScriptLog -Name MyDeploymentScript -ResourceGroupName DS-TestRg -Tail 3
  description: |-
    Gets the last 3 lines of the log of a deployment script with the name MyDeploymentScript in resource group DS-TestRG.
  summary: ""
- title: Example 3
  code: |-
    PS C:\> $ds = Get-AzDeploymentScript -Name MyDeploymentScript -ResourceGroupName DS-TestRg
    PS C:\> Get-AzDeploymentScriptLog -DeploymentScriptInputObject $ds
  description: |-
    The first command gets a deployment script with the name MyDeploymentScript in resource group DS-TestRG.
    The second command gets the log of given deployment script.
  summary: ""
parameters:
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with Azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.ResourceManager.Cmdlets.SdkModels.PsDeploymentScript" data-throw-if-not-resolved="False" />
  name: DeploymentScriptObject
  isRequired: true
  description: |+
    The deployment script PowerShell object.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: DeploymentScriptInputObject
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: DeploymentScriptResourceId
  isRequired: true
  description: |+
    The fully qualified resource Id of the deployment script.
    Example: /subscriptions/{subId}/resourceGroups/{rgName}/providers/Microsoft.Resources/deploymentScripts/{deploymentScriptName}

  defaultValue: None
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    The name of the deployment script.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: ResourceGroupName
  isRequired: true
  description: |+
    The name of the resource group.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Int32" data-throw-if-not-resolved="False" />
  name: Tail
  description: |+
    Limit output to last n lines

  defaultValue: None
  position: "2"
  aliases: ""
  parameterValueGroup: ""
uid: Az.Resources.Get-AzDeploymentScriptLog
name: Get-AzDeploymentScriptLog
description: |-
  The **Get-AzDeploymentScriptLog** cmdlet gets the log of a deployment script execution.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.ResourceManager.dll-Help.xml
  Module Name: Az.Resources
  online version: https://docs.microsoft.com/en-us/powershell/module/az.resources/get-azdeploymentscriptlog
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Resources/Resources/help/Get-AzDeploymentScriptLog.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Resources/Resources/help/Get-AzDeploymentScriptLog.md
