### YamlMime:PowershellCmdlet
summary: |-
  Gets the Azure Site Recovery vault settings file.
module: Az.RecoveryServices
notes: ""
inputs:
- name: <xref href="Microsoft.Azure.Commands.RecoveryServices.ARSVault" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.RecoveryServices.VaultSettingsFilePath" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-AzRecoveryServicesVault
  href: ./Get-AzRecoveryServicesVault.yml
- text: New-AzRecoveryServicesVault
  href: ./New-AzRecoveryServicesVault.yml
- text: Remove-AzRecoveryServicesVault
  href: ./Remove-AzRecoveryServicesVault.yml
syntaxes:
- >-
  Get-AzRecoveryServicesVaultSettingsFile [-Vault] <ARSVault> [[-Path] <String>] -SiteIdentifier <String>

   -Certificate <String> -SiteFriendlyName <String> [-SiteRecovery] [-DefaultProfile <IAzureContextContainer>]

   [<CommonParameters>]
- >-
  Get-AzRecoveryServicesVaultSettingsFile [-Vault] <ARSVault> [[-Path] <String>] -Certificate <String>

   [-SiteRecovery] [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
- >-
  Get-AzRecoveryServicesVaultSettingsFile [-Vault] <ARSVault> [[-Path] <String>] -Certificate <String> [-Backup]

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
examples:
- title: 'Example 1: Register a Windows Server or DPM machine for Azure Backup'
  code: |-
    PS C:\> $Vault01 = Get-AzRecoveryServicesVault -Name "TestVault"
    PS C:\> $CredsPath = "C:\Downloads"
    PS C:\> $Credsfilename = Get-AzRecoveryServicesVaultSettingsFile -Backup -Vault $Vault01 -Path $CredsPath
  description: |-
    The first command gets the vault named TestVault, and then stores it in the $Vault01 variable.
    The second command sets the $CredsPath variable to C:\Downloads.
    The last command gets the vault credentials file for $Vault01 using the credentials in $CredsPath for Azure Backup.
  summary: ""
- title: 'Example 2:'
  code: |-
    PS C:\> $Credsfilename = Get-AzRecoveryServicesVaultSettingsFile -SiteIdentifier -Vault $Vault01
  description: |-
    The command gets the vault credentials file for $Vault01 of vault type siteRecovery.
  summary: ""
- title: 'Example 3: Register a Windows Server or DPM machine for Azure Backup'
  code: |-
    PS C:\> $Credsfilename = Get-AzRecoveryServicesVaultSettingsFile -SiteIdentifier -Vault $Vault01
  description: |-
    The command gets the vault credentials file for $Vault01.
  summary: ""
parameters:
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: Backup
  isRequired: true
  description: |+
    Indicates the vault credentials file is applicable to Azure Backup.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Certificate
  isRequired: true
  description: |+
    {{Fill Certificate Description}}

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Path
  description: |+
    Specifies the path to the Azure Site Recovery vault settings file.
    You can download this file from the Azure Site Recovery vault portal and store it locally.

  defaultValue: None
  position: "2"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: SiteFriendlyName
  isRequired: true
  description: |+
    Specifies the site friendly name.
    Use this parameter if you are downloading the vault credentials for a Hyper-V site.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: SiteIdentifier
  isRequired: true
  description: |+
    Specifies the site identifier.
    Use this parameter if you are downloading the vault credentials for a Hyper-V site.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: SiteRecovery
  description: |+
    Indicates the vault credentials file is applicable to Azure Site Recovery.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.RecoveryServices.ARSVault" data-throw-if-not-resolved="False" />
  name: Vault
  isRequired: true
  description: |+
    Specifies the Azure Site Recovery vault object.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  parameterValueGroup: ""
uid: Az.RecoveryServices.Get-AzRecoveryServicesVaultSettingsFile
name: Get-AzRecoveryServicesVaultSettingsFile
description: |-
  The **Get-AzRecoveryServicesVaultSettingsFile** cmdlet gets the settings file for an Azure Site Recovery vault.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.RecoveryServices.dll-Help.xml
  Module Name: Az.RecoveryServices
  ms.assetid: 56074606-28A6-4F91-A56C-4C8A9A31543F
  online version: https://docs.microsoft.com/en-us/powershell/module/az.recoveryservices/get-azrecoveryservicesvaultsettingsfile
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesVaultSettingsFile.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesVaultSettingsFile.md
