### YamlMime:PowershellCmdlet
summary: |-
  Deploys a DSC Node configuration in Automation.
module: Az.Automation
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Azure.Commands.Automation.Model.NodeConfigurationDeployment" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Automation.Model.NodeConfigurationDeployment" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Start-AzAutomationDscCompilationJob
  href: ./Start-AzAutomationDscCompilationJob.yml
- text: Import-AzAutomationDscNodeConfiguration
  href: ./Import-AzAutomationDscNodeConfiguration.yml
- text: Stop-AzAutomationDscNodeConfigurationDeployment
  href: ./Stop-AzAutomationDscNodeConfigurationDeployment.yml
- text: Get-AzAutomationDscNodeConfigurationDeployment
  href: ./Get-AzAutomationDscNodeConfigurationDeployment.yml
- text: Get-AzAutomationDscNodeConfigurationDeploymentSchedule
  href: ./Get-AzAutomationDscNodeConfigurationDeploymentSchedule.yml
- text: New-AzAutomationSchedule
  href: ./New-AzAutomationSchedule.yml
syntaxes:
- >-
  Start-AzAutomationDscNodeConfigurationDeployment [-NodeConfigurationName] <String> [-NodeName] <String[][]>

   [-Schedule <Schedule>] [-Force] [-ResourceGroupName] <String> [-AutomationAccountName] <String>

   [-DefaultProfile <IAzureContextContainer>] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Start-AzAutomationDscNodeConfigurationDeployment [-NodeConfigurationName] <String> [-NodeName] <String[][]>

   -InputObject <NodeConfigurationDeployment> [-ResourceGroupName] <String> [-AutomationAccountName] <String>

   [-DefaultProfile <IAzureContextContainer>] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: 'Example 1: Deploy an Azure DSC node configuration in Automation'
  code: |-
    PS C:\> $pilot = @("WebServerPilot1", "WebServerPilot2")
    PS C:\> $prod = @("WebServerProd1", "WebServerProd2")
    PS C:\> $nodes = @($pilot, $prod)
    PS C:\> Start-AzAutomationDscNodeConfigurationDeployment `
                -NodeConfigurationName "Config01.Node1" `
                -AutomationAccountName "Contoso01"  `
                -ResourceGroupName "ResourceGroup01" `
                -NodeName $nodes `

    Starting a node configuration deployment.
    Starting a node configuration deployment. It will override any existing node configurations assigned to the node.
    [Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"): Yes

    ResourceGroupName     : ResourceGroup01
    AutomationAccountName : Contoso01
    JobId                 : 35b14eb4-52b7-4a1d-ad62-8e9f84adc657
    Job                   : Microsoft.Azure.Commands.Automation.Model.Job
    JobStatus             : New
    NodeStatus            :
    NodeConfigurationName : Config01.Node1
    JobSchedule           :
    JobScheduleId         : 00000000-0000-0000-0000-000000000000
  description: |-
    The above command deploys the DSC node configuration named "Config01.Node1" to the given two-dimensional array of Node Names. The deployment happens in a staged manner.
  summary: ""
- title: 'Example 2: Schedule an Azure DSC node configuration deployment in Automation'
  code: |-
    PS C:\> $sched = New-AzAutomationSchedule -AutomationAccountName "Contoso01" `
                -ResourceGroupName "ResourceGroup01" `
                -Name "TestSchedule" `
                -StartTime "23:00" `
                -OneTime
    PS C:\> $pilot = @("WebServerPilot1", "WebServerPilot2")
    PS C:\> $prod = @("WebServerProd1", "WebServerProd2")
    PS C:\> $nodes = @($pilot, $prod)
    PS C:\> Start-AzAutomationDscNodeConfigurationDeployment `
                -NodeConfigurationName "Config01.Node1" `
                -AutomationAccountName "Contoso01"  `
                -ResourceGroupName "ResourceGroup01" `
                -NodeName $nodes `
                -Schedule $sched

    Starting a node configuration deployment.
    Starting a node configuration deployment. It will override any existing node configurations assigned to the node.
    [Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"): Y

    ResourceGroupName     : ResourceGroup01
    AutomationAccountName : Contoso01
    JobId                 : 00000000-0000-0000-0000-000000000000
    Job                   :
    JobStatus             :
    NodeStatus            :
    NodeConfigurationName : Config01.Node1
    JobSchedule           : Microsoft.Azure.Commands.Automation.Model.JobSchedule
    JobScheduleId         : 2b1d7738-093d-4ff7-b87b-e4b2321319e5
  description: |-
    The above command schedules a deployment of a DSC node configuration named "Config01.Node1" to the given two-dimensional array of Node Names. The deployment happens in a staged manner and will be executed based on the schedule.
  summary: ""
parameters:
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: AutomationAccountName
  isRequired: true
  description: |+
    Specifies the name of the Automation account that contains the DSC configuration that this cmdlet compiles.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with azure

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    ps_force

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Automation.Model.NodeConfigurationDeployment" data-throw-if-not-resolved="False" />
  name: InputObject
  isRequired: true
  description: |+
    Input object for Piping

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: NodeConfigurationName
  isRequired: true
  description: |+
    Specifies the name of the DSC node configuration that this cmdlet deploys.

  defaultValue: None
  pipelineInput: true
  position: "2"
  aliases: Name
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" /><span>[</span><xref href="][" data-throw-if-not-resolved="False" /><span>]</span>
  name: NodeName
  isRequired: true
  description: |+
    Specifies the names of the nodes to which the Node Configuration would be deployed to.

  defaultValue: None
  position: "3"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: ResourceGroupName
  isRequired: true
  description: |+
    Specifies the name of a resource group in which this cmdlet compiles a configuration.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Automation.Model.Schedule" data-throw-if-not-resolved="False" />
  name: Schedule
  description: |+
    Automation Schedule object to schedule the deployment job.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Az.Automation.Start-AzAutomationDscNodeConfigurationDeployment
name: Start-AzAutomationDscNodeConfigurationDeployment
description: |-
  The **Start-AzAutomationDscNodeConfigurationDeployment** cmdlet deploys a Desired State Configuration (DSC) node configuration in Azure Automation.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Automation.dll-Help.xml
  Module Name: Az.Automation
  ms.assetid: 32CF9BF7-519F-4B5D-9F2B-3CC556A77A48
  online version: https://docs.microsoft.com/en-us/powershell/module/az.automation/start-azautomationdscnodeconfigurationdeployment
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Automation/Automation/help/Start-AzAutomationDscNodeConfigurationDeployment.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Automation/Automation/help/Start-AzAutomationDscNodeConfigurationDeployment.md
