### YamlMime:PowershellCmdlet
summary: |-
  Creates a new configuration for a sql virtual machine.
module: Az.SqlVirtualMachine
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.SqlVirtualMachine.SqlVirtualMachine.Model.AzureSqlVMModel" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  New-AzSqlVMConfig [-LicenseType] <String> [-Offer <String>] [-Sku <String>] [-SqlManagementType <String>]

   [-Tag <Hashtable>] [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    PS C:\> $config = New-AzSqlVMConfig -LicenseType "PAYG"
    PS C:\> New-AzSqlVM -ResourceGroupName "ResourceGroup01" -Name "vm" -SqlVM $config
    Name ResourceGroupName  LicenseType Sku       Offer          SqlManagementType
    ---- -----------------  ----------- ---       -----          -----------------
    vm   ResourceGroup01	PAYG        Developer SQL2017-WS2016 Full
  description: |-
    Creates a local configurable object of sql virtual machine that can be used in order to create an Azure sql virtual machine.
  summary: ""
parameters:
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with Azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: LicenseType
  isRequired: true
  description: |+
    SQL virtual machine license type.

  defaultValue: None
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Offer
  description: |+
    SQL virtual machine offer.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Sku
  description: |+
    SQL virtual machine edition type.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: SqlManagementType
  description: |+
    SQL virtual machine management type.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Hashtable" data-throw-if-not-resolved="False" />
  name: Tag
  description: |+
    The tags to associate with the SQL virtual machine

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Az.SqlVirtualMachine.New-AzSqlVMConfig
name: New-AzSqlVMConfig
description: |-
  The New-AzSqlVMConfig cmdlet creates a new configuration object for a sql virtual machine.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.SqlVirtualMachine.dll-Help.xml
  Module Name: Az.SqlVirtualMachine
  online version: https://docs.microsoft.com/en-us/powershell/module/az.sqlvirtualmachine/new-azsqlvmconfig
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/SqlVirtualMachine/SqlVirtualMachine/help/New-AzSqlVMConfig.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/SqlVirtualMachine/SqlVirtualMachine/help/New-AzSqlVMConfig.md
