### YamlMime:PowershellCmdlet
summary: |-
  Get application insights api keys for an application insights resource
module: Az.ApplicationInsights
notes: ""
inputs:
- name: <xref href="Microsoft.Azure.Commands.ApplicationInsights.Models.PSApplicationInsightsComponent" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.ApplicationInsights.Models.PSApiKey" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Get-AzApplicationInsightsApiKey [-ResourceGroupName] <String> [-Name] <String> [[-ApiKeyId] <String>]

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
- >-
  Get-AzApplicationInsightsApiKey [-ApplicationInsightsComponent] <PSApplicationInsightsComponent>

   [[-ApiKeyId] <String>] [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
- >-
  Get-AzApplicationInsightsApiKey [-ResourceId] <String> [[-ApiKeyId] <String>]

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
examples:
- title: Example 1 Get Api Keys for an application insights resource
  code: |-
    PS C:\>  Get-AzApplicationInsightsApiKey -ResourceGroupName "testGroup" -Name "test"

    Id                                   Description Permissions                       CreatedDate                   ApiKey
    --                                   ----------- -----------                       -----------                   ------
    7c4c61dc-b392-4aa4-992f-ee92b84e5dee test1 ReadTelemetry                     Wed, 18 Oct 2017 23:36:40 GMT
    63657030-dea6-4c52-82f4-6f5128cb92cb test2  {ReadTelemetry, WriteAnnotations} Wed, 18 Oct 2017 21:46:41 GMT
    82549f39-f3ae-492e-8f94-f7aada75fa57 test3  ReadTelemetry                     Wed, 18 Oct 2017 22:30:23 GMT
  description: |-
    Get application insights api keys for resource "test" in resource group "testGroup".
  summary: ""
- title: Example 2 Get specific API key for an application insights resource
  code: |-
    PS C:\>  Get-AzApplicationInsightsApiKey -ResourceGroupName "testGroup" -Name "test"  -ApiKeyId 
    7c4c61dc-b392-4aa4-992f-ee92b84e5dee
    ApiKey      :
    CreatedDate : Wed, 18 Oct 2017 23:36:40 GMT
    Id          : 7c4c61dc-b392-4aa4-992f-ee92b84e5dee
    Permissions : {ReadTelemetry}
    Description : test1
  description: |-
    Get specific application insights api key that id is "dd173f38-4fd1-4c75-8af5-9
    9c29aa0f867" for resource "test" in resource group "testGroup".
  summary: ""
parameters:
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: ApiKeyId
  description: |+
    Application Insights Api Key Id.

  defaultValue: None
  position: "2"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.ApplicationInsights.Models.PSApplicationInsightsComponent" data-throw-if-not-resolved="False" />
  name: ApplicationInsightsComponent
  isRequired: true
  description: |+
    Application Insights Component Object.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    Application Insights Component Name.

  defaultValue: None
  position: "1"
  aliases: ApplicationInsightsComponentName, ComponentName
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: ResourceGroupName
  isRequired: true
  description: |+
    Resource Group Name.

  defaultValue: None
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: ResourceId
  isRequired: true
  description: |+
    Application Insights Component Resource Id.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
uid: Az.ApplicationInsights.Get-AzApplicationInsightsApiKey
name: Get-AzApplicationInsightsApiKey
description: |-
  Get application insights api keys for an application insights resource
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.ApplicationInsights.dll-Help.xml
  Module Name: Az.ApplicationInsights
  online version: https://docs.microsoft.com/en-us/powershell/module/az.applicationinsights/get-azapplicationinsightsapikey
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/ApplicationInsights/ApplicationInsights/help/Get-AzApplicationInsightsApiKey.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/ApplicationInsights/ApplicationInsights/help/Get-AzApplicationInsightsApiKey.md
