### YamlMime:PowershellCmdlet
summary: |-
  Cancel a running deployment at tenant scope
module: Az.Resources
notes: ""
inputs:
- name: <xref href="Microsoft.Azure.Commands.ResourceManager.Cmdlets.SdkModels.PSDeployment" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.Boolean" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Stop-AzTenantDeployment [-Name] <String> [-PassThru] [-ApiVersion <String>] [-Pre]

   [-DefaultProfile <IAzureContextContainer>] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Stop-AzTenantDeployment -Id <String> [-PassThru] [-ApiVersion <String>] [-Pre]

   [-DefaultProfile <IAzureContextContainer>] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Stop-AzTenantDeployment -InputObject <PSDeployment> [-PassThru] [-ApiVersion <String>] [-Pre]

   [-DefaultProfile <IAzureContextContainer>] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    PS C:\>Stop-AzTenantDeployment -Name "deployment01"
  description: |-
    This command cancels a running deployment "deployment01" at the current tenant scope.
  summary: ""
- title: Example 2
  code: |-
    PS C:\>Get-AzTenantDeployment -Name "deployment01" | Stop-AzTenantDeployment
  description: |-
    This command gets the deployment "deployment01" at the current tenant scope and cancels it.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ApiVersion
  description: |+
    When set, indicates the version of the resource provider API to use.
    If not specified, the API version is automatically determined as the latest available.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with Azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Id
  isRequired: true
  description: |+
    The fully qualified resource Id of the deployment.
    example: /providers/Microsoft.Resources/deployments/{deploymentName}

  defaultValue: None
  position: Named
  aliases: DeploymentId, ResourceId
  parameterValueGroup: ""
- type: <xref href="PSDeployment" data-throw-if-not-resolved="False" />
  name: InputObject
  isRequired: true
  description: |+
    The deployment object.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    The name of the deployment.

  defaultValue: None
  position: "0"
  aliases: DeploymentName
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: PassThru
  description: |+
    {{ Fill PassThru Description }}

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Pre
  description: |+
    When set, indicates that the cmdlet should use pre-release API versions when automatically determining which version to use.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Az.Resources.Stop-AzTenantDeployment
name: Stop-AzTenantDeployment
description: |-
  The **Stop-AzTenantDeployment** cmdlet cancels a deployment that has started but not completed at the current tenant scope.
  To stop a deployment, the deployment must have an incomplete provisioning state, such as Provisioning, and not a completed state, such as Provisioned or Failed.

  To create a deployment at tenant scope, use the New-AzTenantDeployment cmdlet.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.ResourceManager.dll-Help.xml
  Module Name: Az.Resources
  online version: https://docs.microsoft.com/en-us/powershell/module/az.resources/stop-aztenantdeployment
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Resources/Resources/help/Stop-AzTenantDeployment.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Resources/Resources/help/Stop-AzTenantDeployment.md
