### YamlMime:PowershellCmdlet
summary: |-
  Gets DSC configurations from Automation.
module: Az.Automation
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Automation.Model.DscConfiguration" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Export-AzAutomationDscConfiguration
  href: ./Export-AzAutomationDscConfiguration.yml
- text: Import-AzAutomationDscConfiguration
  href: ./Import-AzAutomationDscConfiguration.yml
syntaxes:
- >-
  Get-AzAutomationDscConfiguration [-ResourceGroupName] <String> [-AutomationAccountName] <String>

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
- >-
  Get-AzAutomationDscConfiguration [-Name] <String> [-ResourceGroupName] <String>

   [-AutomationAccountName] <String> [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
examples:
- title: 'Example 1: Get all DSC configurations'
  code: |-
    PS C:\>Get-AzAutomationDscConfiguration -ResourceGroupName "ResourceGroup03" -AutomationAccountName "Contoso17"
  description: |-
    This command gets metadata for all DSC configurations in the Automation account named Contoso17.
  summary: ""
- title: 'Example 2: Get a DSC configuration by name'
  code: |-
    PS C:\>Get-AzAutomationDscConfiguration -ResourceGroupName "ResourceGroup03" -AutomationAccountName "Contoso17" -Name "ContosoConfiguration"
  description: |-
    This command gets metadata for a DSC configuration named MyConfiguration in the Automation account named Contoso17.
  summary: ""
parameters:
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: AutomationAccountName
  isRequired: true
  description: |+
    Specifies the name of the Automation account that contains DSC configurations that this cmdlet gets.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with azure

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    Specifies the name of the DSC configuration that this cmdlet gets.

  defaultValue: None
  pipelineInput: true
  position: "2"
  aliases: ConfigurationName
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: ResourceGroupName
  isRequired: true
  description: |+
    Specifies the name of a resource group for which this cmdlet gets DSC configurations.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
uid: Az.Automation.Get-AzAutomationDscConfiguration
name: Get-AzAutomationDscConfiguration
description: |-
  The **Get-AzAutomationDscConfiguration** cmdlet gets APS Desired State Configuration (DSC) configurations from Azure Automation.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Automation.dll-Help.xml
  Module Name: Az.Automation
  ms.assetid: BBD37C4B-BB6F-4560-BDEE-F0440EC1938A
  online version: https://docs.microsoft.com/en-us/powershell/module/az.automation/get-azautomationdscconfiguration
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Automation/Automation/help/Get-AzAutomationDscConfiguration.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Automation/Automation/help/Get-AzAutomationDscConfiguration.md
