### YamlMime:PowershellCmdlet
summary: |-
  Removes metadata from DSC node configurations in Automation.
module: Az.Automation
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.Void" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-AzAutomationDscNodeConfiguration
  href: ./Get-AzAutomationDscNodeConfiguration.yml
- text: Import-AzAutomationDscNodeConfiguration
  href: ./Import-AzAutomationDscNodeConfiguration.yml
- text: Azure Automation Cmdlets
  href: /powershell/module/Az.Automation/
syntaxes:
- >-
  Remove-AzAutomationDscNodeConfiguration [-Name] <String> [-Force] [-IgnoreNodeMappings]

   [-ResourceGroupName] <String> [-AutomationAccountName] <String> [-DefaultProfile <IAzureContextContainer>]

   [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    Remove-AzAutomationDscNodeConfiguration -AutomationAccountName 'AutomationAccount01' -IgnoreNodeMappings -Name 'Configuration01' -ResourceGroupName myresourcegroup
  description: ""
  summary: |+
    Removes metadata from DSC node configurations in Automation. (autogenerated)

    <!-- Aladdin Generated Example -->
parameters:
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: AutomationAccountName
  isRequired: true
  description: |+
    Specifies the name of an Automation account that contains the DSC node configurations for which this cmdlet removes metadata.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with azure

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    ps_force

  defaultValue: None
  position: "3"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: IgnoreNodeMappings
  description: |+
    Indicates that this cmdlet ignores node mappings.

  defaultValue: None
  position: "4"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    Specifies the name of the DSC node configuration for which this cmdlet removes metadata.

  defaultValue: None
  pipelineInput: true
  position: "2"
  aliases: NodeConfigurationName
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: ResourceGroupName
  isRequired: true
  description: |+
    Specifies the name of a resource group.
    This cmdlet removes metadata for DSC node configurations in the resource group that this parameter specifies.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Az.Automation.Remove-AzAutomationDscNodeConfiguration
name: Remove-AzAutomationDscNodeConfiguration
description: |-
  The **Remove-AzAutomationDscNodeConfiguration** cmdlet removes metadata from APS Desired State Configuration (DSC) node configurations in Azure Automation.
  Automation stores DSC node configuration as a Managed Object Format (MOF) configuration document.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Automation.dll-Help.xml
  Module Name: Az.Automation
  ms.assetid: 6C6C7142-31CD-4245-BC55-CB7916EA12E0
  online version: https://docs.microsoft.com/en-us/powershell/module/az.automation/remove-azautomationdscnodeconfiguration
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Automation/Automation/help/Remove-AzAutomationDscNodeConfiguration.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Automation/Automation/help/Remove-AzAutomationDscNodeConfiguration.md
