### YamlMime:PowershellCmdlet
summary: |-
  Updates the artifacts source.
module: Az.DeploymentManager
notes: ""
inputs:
- name: <xref href="Microsoft.Azure.Commands.DeploymentManager.Models.PSArtifactSource" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.DeploymentManager.Models.PSArtifactSource" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Set-AzDeploymentManagerArtifactSource [-InputObject] <PSArtifactSource>

   [-DefaultProfile <IAzureContextContainer>] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    PS C:\> Get-AzDeploymentManagerArtifactSource -InputObject $artifactSourceObject
  description: |-
    This command updates an artifact source whose name and ResourceGroup match the Name and ResourceGroupName properties of the $artifactSourceObject, respectively.
    The artifact source would be updated to the properties set in the $artifactSourceObject.
  summary: ""
parameters:
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with Azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.DeploymentManager.Models.PSArtifactSource" data-throw-if-not-resolved="False" />
  name: InputObject
  isRequired: true
  description: |+
    The artifact source object.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Az.DeploymentManager.Set-AzDeploymentManagerArtifactSource
name: Set-AzDeploymentManagerArtifactSource
description: |-
  The **Set-AzDeploymentManagerArtifactSource** cmdlet updates an artifact source with the specified artifact source object.
  The cmdlet returns the updated ArtifactSource object.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.DeploymentManager.dll-Help.xml
  Module Name: Az.DeploymentManager
  online version: https://docs.microsoft.com/en-us/powershell/module/az.deploymentmanager/set-azdeploymentmanagerartifactsource
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/DeploymentManager/DeploymentManager/help/Set-AzDeploymentManagerArtifactSource.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/DeploymentManager/DeploymentManager/help/Set-AzDeploymentManagerArtifactSource.md
