### YamlMime:PowershellCmdlet
summary: |-
  Gets metadata for DSC node configurations in Automation.
module: Az.Automation
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Automation.Model.CompilationJob" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Import-AzAutomationDscNodeConfiguration
  href: ./Import-AzAutomationDscNodeConfiguration.yml
syntaxes:
- >-
  Get-AzAutomationDscNodeConfiguration [-RollupStatus <String>] [-ResourceGroupName] <String>

   [-AutomationAccountName] <String> [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
- >-
  Get-AzAutomationDscNodeConfiguration -Name <String> [-ResourceGroupName] <String>

   [-AutomationAccountName] <String> [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
- >-
  Get-AzAutomationDscNodeConfiguration -ConfigurationName <String> [-RollupStatus <String>]

   [-ResourceGroupName] <String> [-AutomationAccountName] <String> [-DefaultProfile <IAzureContextContainer>]

   [<CommonParameters>]
examples:
- title: 'Example 1: Get all DSC node configurations'
  code: |-
    PS C:\>Get-AzAutomationDscNodeConfiguration -ResourceGroupName "ResourceGroup03" -AutomationAccountName "Contoso17"
  description: |-
    This command gets metadata for all DSC node configurations in the Automation account named Contoso17.
  summary: ""
- title: 'Example 2: Get all DSC node configurations for a DSC configuration'
  code: |-
    PS C:\>Get-AzAutomationDscNodeConfiguration -ResourceGroupName "ResourceGroup03" -AutomationAccountName "Contoso17" -ConfigurationName "ContosoConfiguration"
  description: |-
    This command gets metadata for all DSC node configurations in the Automation account named Contoso17 that the DSC configuration named ContosoConfiguration generated.
  summary: ""
- title: 'Example 3: Get a DSC node configuration by name'
  code: |-
    PS C:\>Get-AzAutomationDscNodeConfiguration -ResourceGroupName "ResourceGroup03" -AutomationAccountName "Contoso17" -Name "ContosoConfiguration.webserver"
  description: |-
    This command gets metadata for a DSC node configuration with the name ContosoConfiguration.webserver in the Automation account named Contoso17.
  summary: ""
parameters:
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: AutomationAccountName
  isRequired: true
  description: |+
    Specifies the name of an Automation account that contains the DSC node configurations for which this cmdlet gets metadata.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: ConfigurationName
  isRequired: true
  description: |+
    Specifies the name of DSC configuration for which this cmdlet gets node configuration metadata.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with azure

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    Specifies the name of the DSC node configuration for which this cmdlet gets metadata.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: NodeConfigurationName
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: ResourceGroupName
  isRequired: true
  description: |+
    Specifies the name of a resource group.
    This cmdlet gets metadata for DSC node configurations in the resource group that this parameter specifies.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: RollupStatus
  description: |+
    Specifies the rollup status of DSC node configurations that this cmdlet gets.
    Valid values are: 
    - Bad 
    - Good

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: Good, Bad
uid: Az.Automation.Get-AzAutomationDscNodeConfiguration
name: Get-AzAutomationDscNodeConfiguration
description: |-
  The **Get-AzAutomationDscNodeConfiguration** cmdlet gets metadata for APS Desired State Configuration (DSC) node configurations in Azure Automation.
  Automation stores DSC node configuration as a Managed Object Format (MOF) configuration document.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Automation.dll-Help.xml
  Module Name: Az.Automation
  ms.assetid: 89C931AE-DA81-47A7-80E4-159C36497DA0
  online version: https://docs.microsoft.com/en-us/powershell/module/az.automation/get-azautomationdscnodeconfiguration
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Automation/Automation/help/Get-AzAutomationDscNodeConfiguration.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Automation/Automation/help/Get-AzAutomationDscNodeConfiguration.md
