### YamlMime:PowershellCmdlet
summary: |-
  Updates or creates the Azure Advisor Configuration.
module: Az.Advisor
notes: ""
inputs:
- name: <xref href="Microsoft.Azure.Commands.Advisor.Cmdlets.Models.PsAzureAdvisorConfigurationData" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Advisor.Cmdlets.Models.PsAzureAdvisorConfigurationData" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Set-AzAdvisorConfiguration [-Exclude] [[-ResourceGroupName] <String>]

   [[-InputObject] <PsAzureAdvisorConfigurationData>] [-DefaultProfile <IAzureContextContainer>] [-WhatIf]

   [-Confirm] [<CommonParameters>]
- >-
  Set-AzAdvisorConfiguration [-Exclude] [-LowCpuThreshold] <Int32>

   [[-InputObject] <PsAzureAdvisorConfigurationData>] [-DefaultProfile <IAzureContextContainer>] [-WhatIf]

   [-Confirm] [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    PS C:\> Set-AzAdvisorConfiguration -LowCpuThreshold 10
    Id         : /subscriptions/{user_subscription}/resourceGroups/resourceGroupName1/providers/Microsoft.Advisor/configurations/{user_subscription}
    Name       : {user_subscription}
    Properties : additionalProperties : null
                 exclude :  False
                 lowCpuThreshold : 10

    Type       : Microsoft.Advisor/Configurations
  description: |-
    Updates the configuration(lowCpuThreshold) for subscription level Configuration.
  summary: ""
- title: Example 2
  code: |-
    PS C:\> Set-AzAdvisorConfiguration -LowCpuThreshold 15 -Exclude 
    Id         : /subscriptions/{user_subscription}/resourceGroups/resourceGroupName1/providers/Microsoft.Advisor/configurations/{user_subscription}
    Name       : {user_subscription}
    Properties : additionalProperties : null
                 exclude :  True
                 lowCpuThreshold : 15

    Type       : Microsoft.Advisor/Configurations
  description: |-
    Updates the configuration(lowCpuThreshold, exclude) for subscription level Configuration and excludes from the recommendation generation.
  summary: ""
- title: Example 3
  code: |-
    PS C:\> Set-AzAdvisorConfiguration -ResourceGroupName resourceGroupName1 -Exclude

    Id         : /subscriptions/{user_subscription}/resourceGroups/resourceGroupName1/providers/Microsoft.Advisor/configurations/{user_subscription}-resourceGroupName1
    Name       : {user_subscription}-resourceGroupName1
    Properties : additionalProperties : null
                 exclude :  True
                 lowCpuThreshold : null

    Type       : Microsoft.Advisor/Configurations
  description: |-
    Updates the configuration(exclude) for resourceGroupName1 to be excluded in the recommendation generation.
  summary: ""
- title: Example 4
  code: |-
    PS C:\> Get-AzAdvisorConfiguration | Set-AzAdvisorConfiguration -LowCpuThreshold 20
    Id         : /subscriptions/{user_subscription}/resourceGroups/resourceGroupName1/providers/Microsoft.Advisor/configurations/{user_subscription}
    Name       : {user_subscription}
    Properties : additionalProperties : null
                 exclude :  False
                 lowCpuThreshold : 20

    Type       : Microsoft.Advisor/Configurations
  description: |-
    Updates the configuration for the given recommendation passed on from the pipeline.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with Azure.

  defaultValue: None
  position: Named
  aliases: AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Exclude
  description: |+
    Exclude from the recommendation generation. If not specified exclude property will be set to false.

  defaultValue: None
  position: "2"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="PsAzureAdvisorConfigurationData" data-throw-if-not-resolved="False" />
  name: InputObject
  description: |+
    The powershell object type PsAzureAdvisorConfigurationData returned by Get-AzAdvisorConfiguration call.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: LowCpuThreshold
  isRequired: true
  description: |+
    Value for Low Cpu threshold.

  defaultValue: None
  position: "0"
  aliases: ""
  parameterValueGroup: 0, 5, 10, 15, 20
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ResourceGroupName
  description: |+
    Resource Group name for the configuration.

  defaultValue: None
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Az.Advisor.Set-AzAdvisorConfiguration
name: Set-AzAdvisorConfiguration
description: |-
  Used to update the configuration of the Azure Advisor. Two types of Configuration are present: Subscription level configuration and ResourceGroup level configuration. 

  Subscription level configuration: There can be only one Configuration for this type for a subscription. LowCpuThreshold and Exclude properties can be updated using this cmdlet.
  ResourceGroup level configuration: There can be only one configuration for each ResourceGroup. Only Exclude property can be updated using this cmdlet.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Advisor.dll-Help.xml
  Module Name: Az.Advisor
  online version: https://docs.microsoft.com/en-us/powershell/module/az.advisor/set-azadvisorConfiguration
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Advisor/Advisor/help/Set-AzAdvisorConfiguration.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Advisor/Advisor/help/Set-AzAdvisorConfiguration.md
