### YamlMime:PowershellCmdlet
summary: |-
  Create a new application insights resource
module: Az.ApplicationInsights
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.ApplicationInsights.Models.PSApplicationInsightsComponent" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  New-AzApplicationInsights [-ResourceGroupName] <String> [-Name] <String> [-Location] <String> [-Kind <String>]

   [-Tag <Hashtable>] [-DefaultProfile <IAzureContextContainer>] [[-RetentionInDays] <Int32>]

   [[-PublicNetworkAccessForIngestion] <String>] [[-PublicNetworkAccessForQuery] <String>] [-WhatIf] [-Confirm]

   [<CommonParameters>]
examples:
- title: Example 1 Create a new application insights resource
  code: |-
    PS C:\>  New-AzApplicationInsights -Kind java -ResourceGroupName testgroup -Name test1027 -location eastus
    Id                 : /subscriptions/{subid}/resourceGroups/testgroup/providers/microsoft.insights/components/test1027
    ResourceGroupName  : testgroup
    Name               : test1027
    Kind               : web
    Location           : eastus
    Type               : microsoft.insights/components
    AppId              : 8323fb13-32aa-46af-b467-8355cf4f8f98
    ApplicationType    : web
    Tags               : {}
    CreationDate       : 10/27/2017 4:56:40 PM
    FlowType           :
    HockeyAppId        :
    HockeyAppToken     :
    InstrumentationKey : 083112ed-ed9b-464e-a9b0-8cf126fbfced
    ProvisioningState  : Succeeded
    RequestSource      : AzurePowerShell
    SamplingPercentage :
    TenantId           : {subid}
    PublicNetworkAccessForIngestion : Enabled
    PublicNetworkAccessForQuery     : Enabled
    PrivateLinkScopedResources      :
  description: |-
    Add a new application insights resource named as "test" in resource group "testgroup" with kind "java"
  summary: ""
parameters:
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Kind
  description: |+
    Application kind.

  defaultValue: web
  position: Named
  aliases: ApplicationKind
  parameterValueGroup: web, other, Node.js, java
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Location
  isRequired: true
  description: |+
    Application Insights Resource Location.

  defaultValue: None
  position: "2"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    Application Insights Resource Name.

  defaultValue: None
  position: "1"
  aliases: ApplicationInsightsComponentName, ComponentName
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: PublicNetworkAccessForIngestion
  description: |+
    The network access type for accessing Application Insights ingestion. Value should be 'Enabled' or 'Disabled'

  defaultValue: None
  position: "4"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: PublicNetworkAccessForQuery
  description: |+
    The network access type for accessing Application Insights query. Value should be 'Enabled' or 'Disabled'

  defaultValue: None
  position: "5"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: ResourceGroupName
  isRequired: true
  description: |+
    Resource Group Name.

  defaultValue: None
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Nullable`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="System.Int32" data-throw-if-not-resolved="False" /><span>]</span>
  name: RetentionInDays
  description: |+
    Retention In Days, 90 by default.

  defaultValue: None
  position: "3"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Hashtable" data-throw-if-not-resolved="False" />
  name: Tag
  description: |+
    Component Tags.

  defaultValue: None
  position: Named
  aliases: Tags
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs. The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Az.ApplicationInsights.New-AzApplicationInsights
name: New-AzApplicationInsights
description: |-
  Create a new application insights resource
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.ApplicationInsights.dll-Help.xml
  Module Name: Az.ApplicationInsights
  online version: https://docs.microsoft.com/en-us/powershell/module/az.applicationinsights/new-azapplicationinsights
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/ApplicationInsights/ApplicationInsights/help/New-AzApplicationInsights.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/ApplicationInsights/ApplicationInsights/help/New-AzApplicationInsights.md
