### YamlMime:PowershellCmdlet
summary: |-
  Creates an IP configuration for a network interface of a VMSS.
module: Az.Compute
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="System.String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  description: ""
- name: <xref href="System.Int32" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetIpTag" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetIPConfiguration" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Add-AzVmssNetworkInterfaceConfiguration
  href: ./Add-AzVmssNetworkInterfaceConfiguration.yml
syntaxes:
- >-
  New-AzVmssIpConfig [[-Name] <String>] [[-Id] <String>] [[-SubnetId] <String>]

   [[-ApplicationGatewayBackendAddressPoolsId] <String[]>] [[-LoadBalancerBackendAddressPoolsId] <String[]>]

   [[-LoadBalancerInboundNatPoolsId] <String[]>] [-Primary] [-PrivateIPAddressVersion <String>]

   [-PublicIPAddressConfigurationName <String>] [-PublicIPAddressConfigurationIdleTimeoutInMinutes <Int32>]

   [-DnsSetting <String>] [-IpTag <VirtualMachineScaleSetIpTag[]>] [-PublicIPPrefix <String>]

   [-PublicIPAddressVersion <String>] [-DefaultProfile <IAzureContextContainer>] [-WhatIf] [-Confirm]

   [<CommonParameters>]
examples:
- title: 'Example 1: Create an IP configuration object for a VMSS interface'
  code: |-
    PS C:\> $IPConfiguration = New-AzVmssIPConfig -Name "ContosoVmssInterface02" -SubnetId $SubnetId
  description: |-
    This command creates an IP configuration object named ContosoVmssInterface02.
    The command uses a previously defined subnet ID stored in $SubnetId.
    The command stores the configuration settings in the $IPConfiguration variable for later use with **Add-AzVmssNetworkInterfaceConfiguration**.
  summary: ""
- title: 'Example 2: Create an IP configuration object that includes NAT pool settings'
  code: |-
    PS C:\> $IPConfiguration = New-AzVmssIPConfig -Name "ContosoVmssInterface03" -LoadBalancerInboundNatPoolsId $expectedLb.InboundNatPools[0].Id -LoadBalancerBackendAddressPoolsId $expectedLb.BackendAddressPools[0].Id -SubnetId $SubnetId
  description: |-
    This command creates an IP configuration object named ContosoVmssInterface03, and then stores it in the $IPConfiguration variable for later use.
    The command uses a previously defined subnet ID stored in $SubnetId.
    The command stores the configuration settings in the $IPConfiguration variable for later use.
    The command specifies values for the *LoadBalancerInboundNatPoolsId* and *LoadBalancerBackendAddressPoolsId* parameters.
  summary: ""
parameters:
- type: <xref href="System.String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: ApplicationGatewayBackendAddressPoolsId
  description: |+
    Specifies an array of references to backend address pools of load balancers.
    A scale set can reference backend address pools of one public and one internal load balancer.
    Multiple scale sets cannot use the same load balancer.

  defaultValue: None
  pipelineInput: true
  position: "3"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: DnsSetting
  description: |+
    The dns settings to be applied on the publicIP addresses.
    The domain name label of the Dns settings to be applied on the publicIP addresses.
    The concatenation of the domain name label and vm index will be the domain name labels of the Public IP Address resources that will be created.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: PublicIPAddressDomainNameLabel
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Id
  description: |+
    Specifies an ID.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetIpTag" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: IpTag
  description: |+
    Specifies an array of Ip Tag objects.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: LoadBalancerBackendAddressPoolsId
  description: |+
    Specifies an array of references to incoming network address translation (NAT) pools of the load balancers.
    A scale set can reference incoming NAT pools of one public and one internal load balancer.
    Multiple scale sets cannot use the same load balancer.

  defaultValue: None
  pipelineInput: true
  position: "4"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: LoadBalancerInboundNatPoolsId
  description: |+
    Specifies an array of references to incoming NAT pools of the load balancers.
    A scale set can reference incoming NAT pools of one public and one internal load balancer.
    Multiple scale sets cannot use the same load balancer.

  defaultValue: None
  pipelineInput: true
  position: "5"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  description: |+
    Specifies the name of the IP configuration.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: Primary
  description: |+
    Specifies the primary IP Configuration in case the network interface has more than one IP Configuration.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: PrivateIPAddressVersion
  description: |+
    Specify the IP configuration for private IP address.  Default is taken as IPv4.  Possible values are: 'IPv4' and 'IPv6'.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Int32" data-throw-if-not-resolved="False" />
  name: PublicIPAddressConfigurationIdleTimeoutInMinutes
  description: |+
    The idle timeout of the public IP address.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: PublicIPAddressIdleTimeoutInMinutes
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: PublicIPAddressConfigurationName
  description: |+
    The publicIP address configuration name.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: PublicIPAddressName
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: PublicIPAddressVersion
  description: |+
    Specify the IP configuration for public IP address.  Default is taken as IPv4.  Possible values are: 'IPv4' and 'IPv6'.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: PublicIPPrefix
  description: |+
    The ID of Public IP Prefix

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: SubnetId
  description: |+
    Specifies the subnet ID in which the configuration creates  the VMSS network interface.

  defaultValue: None
  pipelineInput: true
  position: "2"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs. The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Az.Compute.New-AzVmssIpConfig
name: New-AzVmssIpConfig
description: |-
  The **New-AzVmssIpConfig** cmdlet creates an IP configuration object for a network interface of a Virtual Machine Scale Set (VMSS).
  Specify the configuration from this cmdlet as the *IPConfiguration* parameter of the Add-AzVmssNetworkInterfaceConfiguration cmdlet.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Compute.dll-Help.xml
  Module Name: Az.Compute
  ms.assetid: 92F192A5-F75E-4EFE-B2D2-B0DF0B78D3B5
  online version: https://docs.microsoft.com/en-us/powershell/module/az.compute/new-azvmssipconfig
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Compute/Compute/help/New-AzVmssIpConfig.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Compute/Compute/help/New-AzVmssIpConfig.md
