### YamlMime:PowershellCmdlet
summary: |-
  Adds back-end HTTP settings to an application gateway.
module: Az.Network
notes: ""
inputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationGateway" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationGateway" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-AzApplicationGatewayBackendHttpSetting
  href: ./Get-AzApplicationGatewayBackendHttpSetting.yml
- text: New-AzApplicationGatewayBackendHttpSetting
  href: ./New-AzApplicationGatewayBackendHttpSetting.yml
- text: Remove-AzApplicationGatewayBackendHttpSetting
  href: ./Remove-AzApplicationGatewayBackendHttpSetting.yml
- text: Set-AzApplicationGatewayBackendHttpSetting
  href: ./Set-AzApplicationGatewayBackendHttpSetting.yml
syntaxes:
- >-
  Add-AzApplicationGatewayBackendHttpSetting -ApplicationGateway <PSApplicationGateway> -Name <String>

   -Port <Int32> -Protocol <String> -CookieBasedAffinity <String> [-RequestTimeout <Int32>]

   [-ConnectionDraining <PSApplicationGatewayConnectionDraining>] [-ProbeId <String>]

   [-Probe <PSApplicationGatewayProbe>]

   [-AuthenticationCertificates <PSApplicationGatewayAuthenticationCertificate[]>]

   [-TrustedRootCertificate <PSApplicationGatewayTrustedRootCertificate[]>] [-PickHostNameFromBackendAddress]

   [-HostName <String>] [-AffinityCookieName <String>] [-Path <String>]

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
examples:
- title: 'Example 1: Add back-end HTTP settings to an application gateway'
  code: |-
    PS C:\>$AppGw = Get-AzApplicationGateway -Name "ApplicationGateway01" -ResourceGroupName "ResourceGroup01"
    PS C:\> $AppGw = Add-AzApplicationGatewayBackendHttpSetting -ApplicationGateway $AppGw -Name "Setting02" -Port 88 -Protocol "HTTP" -CookieBasedAffinity "Disabled"
  description: |-
    The first command gets the application gateway named ApplicationGateway01 that belongs to the resource group named ResourceGroup01 and stores it in the $AppGw variable.The second command adds back-end HTTP settings to the application gateway, setting the port to 88 and the protocol to HTTP and names the settings Setting02.
  summary: ""
parameters:
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: AffinityCookieName
  description: |+
    Cookie name to use for the affinity cookie

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationGateway" data-throw-if-not-resolved="False" />
  name: ApplicationGateway
  isRequired: true
  description: |+
    Specifies the name of application gateway for which this cmdlet adds settings.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationGatewayAuthenticationCertificate" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: AuthenticationCertificates
  description: |+
    Specifies authentication certificates for the application gateway.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationGatewayConnectionDraining" data-throw-if-not-resolved="False" />
  name: ConnectionDraining
  description: |+
    Connection draining of the backend http settings resource.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: CookieBasedAffinity
  isRequired: true
  description: |+
    Specifies whether cookie-based affinity should be enabled or disabled for the backend server pool.
    The acceptable values for this parameter are: Disabled, Enabled.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: Enabled, Disabled
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: HostName
  description: |+
    Sets host header to be sent to the backend servers.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    Specifies the name of the back-end HTTP settings which this cmdlet adds.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Path
  description: |+
    Path which should be used as a prefix for all HTTP requests.
    If no value is provided for this parameter, then no path will be prefixed.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: PickHostNameFromBackendAddress
  description: |+
    Flag if host header should be picked from the host name of the backend server.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Int32" data-throw-if-not-resolved="False" />
  name: Port
  isRequired: true
  description: |+
    Specifies the port of the back-end server pool.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationGatewayProbe" data-throw-if-not-resolved="False" />
  name: Probe
  description: |+
    Specifies a probe to associate with a back-end server.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: ProbeId
  description: |+
    Specifies the ID of the probe to associate with the back-end server.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Protocol
  isRequired: true
  description: |+
    Specifies the protocol for communication between application gateway and back-end servers.
    The acceptable values for this parameter are: Http and Https.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: Http, Https
- type: <xref href="System.Int32" data-throw-if-not-resolved="False" />
  name: RequestTimeout
  description: |+
    Specifies the request time-out value.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationGatewayTrustedRootCertificate" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: TrustedRootCertificate
  description: |+
    Application gateway Trusted Root Certificates

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Az.Network.Add-AzApplicationGatewayBackendHttpSetting
name: Add-AzApplicationGatewayBackendHttpSetting
description: |-
  The Add-AzApplicationGatewayBackendHttpSetting cmdlet adds back-end HTTP settings to an application gateway.
  Back-end HTTP settings are applied to all back-end servers in the pool.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  Module Name: Az.Network
  online version: https://docs.microsoft.com/en-us/powershell/module/az.network/add-azapplicationgatewaybackendhttpsetting
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Add-AzApplicationGatewayBackendHttpSetting.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Add-AzApplicationGatewayBackendHttpSetting.md
