### YamlMime:PowershellCmdlet
summary: |-
  Gets the rewrite rule set of an application gateway.
module: Az.Network
notes: ""
inputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationGateway" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationGatewayRewriteRuleSet" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Add-AzApplicationGatewayRewriteRuleSet
  href: ./Add-AzApplicationGatewayRewriteRuleSet.yml
- text: New-AzApplicationGatewayRewriteRuleSet
  href: ./New-AzApplicationGatewayRewriteRuleSet.yml
- text: Remove-AzApplicationGatewayRewriteRuleSet
  href: ./Remove-AzApplicationGatewayRewriteRuleSet.yml
- text: Set-AzApplicationGatewayRewriteRuleSet
  href: ./Set-AzApplicationGatewayRewriteRuleSet.yml
- text: New-AzApplicationGatewayRewriteRule
  href: ./New-AzApplicationGatewayRewriteRule.yml
- text: New-AzApplicationGatewayRewriteRuleActionSet
  href: ./New-AzApplicationGatewayRewriteRuleActionSet.yml
- text: New-AzApplicationGatewayRewriteRuleHeaderConfiguration
  href: ./New-AzApplicationGatewayRewriteRuleHeaderConfiguration.yml
syntaxes:
- >-
  Get-AzApplicationGatewayRewriteRuleSet [-Name <String>] -ApplicationGateway <PSApplicationGateway>

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
examples:
- title: 'Example 1 : Get a specific rewrite rule set'
  code: |-
    PS C:\> $AppGW = Get-AzApplicationGateway -Name "ApplicationGateway01" -ResourceGroupName "ResourceGroup01"
    PS C:\> $Rule = Get-AzApplicationGatewayRewriteRuleSet -Name "RuleSet01" -ApplicationGateway $AppGW
  description: |-
    The first command gets the Application Gateway named ApplicationGateway01 and stores the result in the variable named $AppGW.
    The second command gets the rewrite rule set named RuleSet01 from the Application Gateway stored in the variable named $AppGW.
  summary: ""
parameters:
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationGateway" data-throw-if-not-resolved="False" />
  name: ApplicationGateway
  isRequired: true
  description: |+
    The applicationGateway

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with Azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  description: |+
    The name of the application gateway RewriteRuleSet

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Az.Network.Get-AzApplicationGatewayRewriteRuleSet
name: Get-AzApplicationGatewayRewriteRuleSet
description: |-
  Gets the rewrite rule set of an application gateway.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  Module Name: Az.Network
  online version: https://docs.microsoft.com/en-us/powershell/module/az.network/get-azapplicationgatewayrewriteruleset
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Get-AzApplicationGatewayRewriteRuleSet.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Get-AzApplicationGatewayRewriteRuleSet.md
