### YamlMime:PowershellCmdlet
summary: |-
  Gets a front-end IP configuration in a load balancer.
module: Az.Network
notes: ""
inputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSLoadBalancer" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSFrontendIPConfiguration" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Add-AzLoadBalancerFrontendIpConfig
  href: ./Add-AzLoadBalancerFrontendIpConfig.yml
- text: Get-AzLoadBalancer
  href: ./Get-AzLoadBalancer.yml
- text: New-AzLoadBalancerFrontendIpConfig
  href: ./New-AzLoadBalancerFrontendIpConfig.yml
- text: Remove-AzLoadBalancerFrontendIpConfig
  href: ./Remove-AzLoadBalancerFrontendIpConfig.yml
- text: Set-AzLoadBalancerFrontendIpConfig
  href: ./Set-AzLoadBalancerFrontendIpConfig.yml
syntaxes:
- >-
  Get-AzLoadBalancerFrontendIpConfig -LoadBalancer <PSLoadBalancer> [-Name <String>]

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
examples:
- title: 'Example 1: Get a front-end IP configuration in a load balancer'
  code: |-
    PS C:\>$slb = Get-AzLoadBalancer -Name "MyLoadBalancer" -ResourceGroupName "MyResourceGroup"
    PS C:\> Get-AzLoadBalancerFrontendIpConfig -Name "MyFrontEnd" -LoadBalancer $slb
  description: |-
    The first command gets the load balancer named MyLoadBalancer, and then stores it in the variable $slb.
    The second command gets the front end IP configuration associated with that load balancer.
  summary: ""
parameters:
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSLoadBalancer" data-throw-if-not-resolved="False" />
  name: LoadBalancer
  isRequired: true
  description: |+
    Specifies the load balancer that is associated with the front-end IP configuration to get.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  description: |+
    Specifies the name of the load balancer that contains the front-end IP configuration to get.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Az.Network.Get-AzLoadBalancerFrontendIpConfig
name: Get-AzLoadBalancerFrontendIpConfig
description: |-
  The **Get-AzLoadBalancerFrontendIpConfig** cmdlet gets a front-end IP configuration or a list of front-end IP configurations in a load balancer.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  Module Name: Az.Network
  ms.assetid: 6BEED413-E2E4-4557-BD31-2A655E790C1D
  online version: https://docs.microsoft.com/en-us/powershell/module/az.network/get-azloadbalancerfrontendipconfig
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Get-AzLoadBalancerFrontendIpConfig.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Get-AzLoadBalancerFrontendIpConfig.md
