### YamlMime:PowershellCmdlet
summary: |-
  Creates a request routing rule for an application gateway.
module: Az.Network
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationGatewayRewriteRuleSet" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Add-AzApplicationGatewayRewriteRuleSet
  href: ./Add-AzApplicationGatewayRewriteRuleSet.yml
- text: Get-AzApplicationGatewayRewriteRuleSet
  href: ./Get-AzApplicationGatewayRewriteRuleSet.yml
- text: Remove-AzApplicationGatewayRewriteRuleSet
  href: ./Remove-AzApplicationGatewayRewriteRuleSet.yml
- text: Set-AzApplicationGatewayRewriteRuleSet
  href: ./Set-AzApplicationGatewayRewriteRuleSet.yml
- text: New-AzApplicationGatewayRewriteRule
  href: ./New-AzApplicationGatewayRewriteRule.yml
- text: New-AzApplicationGatewayRewriteRuleActionSet
  href: ./New-AzApplicationGatewayRewriteRuleActionSet.yml
- text: New-AzApplicationGatewayRewriteRuleHeaderConfiguration
  href: ./New-AzApplicationGatewayRewriteRuleHeaderConfiguration.yml
syntaxes:
- >-
  New-AzApplicationGatewayRewriteRuleSet -Name <String>

   -RewriteRule <System.Collections.Generic.List`1[Microsoft.Azure.Commands.Network.Models.PSApplicationGatewayRewriteRule]>

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    PS C:\> $ruleset = New-AzApplicationGatewayRewriteRuleSet -Name ruleset1 -RewriteRule $rule
  description: |-
    This command creates a rewrite rule set named ruleset1 and stores the result in the variable named $ruleset.
  summary: ""
parameters:
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with Azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    The name of the RewriteRuleSet

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Azure.Commands.Network.Models.PSApplicationGatewayRewriteRule" data-throw-if-not-resolved="False" /><span>]</span>
  name: RewriteRule
  isRequired: true
  description: |+
    List of rewrite rules

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Az.Network.New-AzApplicationGatewayRewriteRuleSet
name: New-AzApplicationGatewayRewriteRuleSet
description: |-
  **The New-AzApplicationGatewayRewriteRuleSet** cmdlet creates a rewrite rule set for an Azure application gateway.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  Module Name: Az.Network
  online version: https://docs.microsoft.com/en-us/powershell/module/az.network/new-azapplicationgatewayrewriteruleset
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/New-AzApplicationGatewayRewriteRuleSet.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/New-AzApplicationGatewayRewriteRuleSet.md
