### YamlMime:PowershellCmdlet
summary: |-
  Updates a subnet configuration for a virtual network.
module: Az.Network
notes: ""
inputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSVirtualNetwork" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSNetworkSecurityGroup" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSRouteTable" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="System.String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  description: ""
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSServiceEndpointPolicy" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  description: ""
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSDelegation" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Network.Models.PSVirtualNetwork" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Add-AzVirtualNetworkSubnetConfig
  href: ./Add-AzVirtualNetworkSubnetConfig.yml
- text: Get-AzVirtualNetworkSubnetConfig
  href: ./Get-AzVirtualNetworkSubnetConfig.yml
- text: New-AzVirtualNetworkSubnetConfig
  href: ./New-AzVirtualNetworkSubnetConfig.yml
- text: Remove-AzVirtualNetworkSubnetConfig
  href: ./Remove-AzVirtualNetworkSubnetConfig.yml
syntaxes:
- >-
  Set-AzVirtualNetworkSubnetConfig -Name <String> -VirtualNetwork <PSVirtualNetwork> -AddressPrefix <String[]>

   [-NetworkSecurityGroup <PSNetworkSecurityGroup>] [-RouteTable <PSRouteTable>] [-InputObject <PSNatGateway>]

   [-ServiceEndpoint <String[]>] [-ServiceEndpointPolicy <PSServiceEndpointPolicy[]>]

   [-Delegation <PSDelegation[]>] [-PrivateEndpointNetworkPoliciesFlag <String>]

   [-PrivateLinkServiceNetworkPoliciesFlag <String>] [-DefaultProfile <IAzureContextContainer>]

   [<CommonParameters>]
- >-
  Set-AzVirtualNetworkSubnetConfig -Name <String> -VirtualNetwork <PSVirtualNetwork> -AddressPrefix <String[]>

   [-NetworkSecurityGroupId <String>] [-RouteTableId <String>] [-ResourceId <String>]

   [-ServiceEndpoint <String[]>] [-ServiceEndpointPolicy <PSServiceEndpointPolicy[]>]

   [-Delegation <PSDelegation[]>] [-PrivateEndpointNetworkPoliciesFlag <String>]

   [-PrivateLinkServiceNetworkPoliciesFlag <String>] [-DefaultProfile <IAzureContextContainer>]

   [<CommonParameters>]
examples:
- title: '1: Modify the address prefix of a subnet'
  code: |-
    New-AzResourceGroup -Name TestResourceGroup -Location centralus

    $frontendSubnet = New-AzVirtualNetworkSubnetConfig -Name frontendSubnet -AddressPrefix "10.0.1.0/24"

    $virtualNetwork = New-AzVirtualNetwork -Name MyVirtualNetwork -ResourceGroupName TestResourceGroup    
        -Location centralus -AddressPrefix "10.0.0.0/16" -Subnet $frontendSubnet

    Set-AzVirtualNetworkSubnetConfig -Name frontendSubnet -VirtualNetwork $virtualNetwork -AddressPrefix "10.0.3.0/23"

    $virtualNetwork | Set-AzVirtualNetwork
  description: |-
    This example creates a virtual network with one subnet. Then is calls 
        Set-AzVirtualNetworkSubnetConfig to modify the AddressPrefix of the subnet. This 
        only impacts the in-memory representation of the virtual network. 
        Set-AzVirtualNetwork is then called to modify the virtual network in Azure.
  summary: ""
- title: '2: Add a network security group to a subnet'
  code: |-
    New-AzResourceGroup -Name TestResourceGroup -Location centralus

    $frontendSubnet = New-AzVirtualNetworkSubnetConfig -Name frontendSubnet -AddressPrefix "10.0.1.0/24"

    $virtualNetwork = New-AzVirtualNetwork -Name MyVirtualNetwork -ResourceGroupName TestResourceGroup 
        -Location centralus -AddressPrefix "10.0.0.0/16" -Subnet $frontendSubnet

    $rdpRule = New-AzNetworkSecurityRuleConfig -Name rdp-rule -Description "Allow RDP" -Access Allow 
        -Protocol Tcp -Direction Inbound -Priority 100 -SourceAddressPrefix Internet -SourcePortRange * -DestinationAddressPrefix * -DestinationPortRange 3389

    $networkSecurityGroup = New-AzNetworkSecurityGroup -ResourceGroupName 
        TestResourceGroup -Location centralus -Name "NSG-FrontEnd" -SecurityRules $rdpRule

    Set-AzVirtualNetworkSubnetConfig -Name frontendSubnet -VirtualNetwork $virtualNetwork -AddressPrefix 
        "10.0.1.0/24" -NetworkSecurityGroup $networkSecurityGroup

    $virtualNetwork | Set-AzVirtualNetwork
  description: |-
    This example creates a resource group with one virtual network containing just one 
        subnet. It then creates a network security group with an allow rule for RDP traffic. The 
        Set-AzVirtualNetworkSubnetConfig cmdlet is used to modify the in-memory 
        representation of the frontend subnet so that it points to the newly created network 
        security group. The Set-AzVirtualNetwork cmdlet is then called to write the modified 
        state back to the service.
  summary: ""
- title: '3: Attach a Nat Gateway to a subnet'
  code: |-
    $pip = New-AzPublicIpAddress -Name "pip" -ResourceGroupName "natgateway_test" `
       -Location "eastus2" -Sku "Standard" -IdleTimeoutInMinutes 4 -AllocationMethod "static"

    $natGateway = New-AzNatGateway -ResourceGroupName "natgateway_test" -Name "nat_gateway" `
       -IdleTimeoutInMinutes 4 -Sku "Standard" -Location "eastus2" -PublicIpAddress $pip

    $frontendSubnet = New-AzVirtualNetworkSubnetConfig -Name frontendSubnet -AddressPrefix "10.0.1.0/24" 

    $virtualNetwork = New-AzVirtualNetwork -Name MyVirtualNetwork -ResourceGroupName TestResourceGroup 
        -Location centralus -AddressPrefix "10.0.0.0/16" -Subnet $frontendSubnet

    Set-AzVirtualNetworkSubnetConfig -Name frontendSubnet -VirtualNetwork $virtualNetwork -InputObject $natGateway 

    $virtualNetwork | Set-AzVirtualNetwork
  description: ""
  summary: ""
parameters:
- type: <xref href="System.String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: AddressPrefix
  isRequired: true
  description: |+
    Specifies a range of IP addresses for a subnet configuration.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSDelegation" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: Delegation
  description: |+
    List of services that have permission to perform operations on this subnet.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSNatGateway" data-throw-if-not-resolved="False" />
  name: InputObject
  description: |+
    Specifies the nat gateway associated with the subnet configuration.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: NatGateway
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    Specifies the name of a subnet configuration that this cmdlet configures.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSNetworkSecurityGroup" data-throw-if-not-resolved="False" />
  name: NetworkSecurityGroup
  description: |+
    Specifies a **NetworkSecurityGroup** object.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: NetworkSecurityGroupId
  description: |+
    Specifies the ID of a network security group.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: PrivateEndpointNetworkPoliciesFlag
  description: |+
    Configure to enable or disable applying network policies on private endpoint in the subnet.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: PrivateLinkServiceNetworkPoliciesFlag
  description: |+
    Configure to enable or disable applying network policies on private link service in the subnet.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: ResourceId
  description: |+
    Specifies the Id of NAT Gateway resource associated with the subnet configuration.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: NatGatewayId
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSRouteTable" data-throw-if-not-resolved="False" />
  name: RouteTable
  description: |+
    Specifies the route table object that is associated with the network security group.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: RouteTableId
  description: |+
    Specifies the ID of the route table object that is associated with the network security group.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: ServiceEndpoint
  description: |+
    Service Endpoint Value

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSServiceEndpointPolicy" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: ServiceEndpointPolicy
  description: |+
    Service Endpoint Policies

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Network.Models.PSVirtualNetwork" data-throw-if-not-resolved="False" />
  name: VirtualNetwork
  isRequired: true
  description: |+
    Specifies the **VirtualNetwork** object that contains the subnet configuration.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Az.Network.Set-AzVirtualNetworkSubnetConfig
name: Set-AzVirtualNetworkSubnetConfig
description: |-
  The **Set-AzVirtualNetworkSubnetConfig** cmdlet updates a subnet configuration for a virtual network.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Network.dll-Help.xml
  Module Name: Az.Network
  ms.assetid: D1D51DEF-05DE-45C4-9013-A02A5B248EAC
  online version: https://docs.microsoft.com/en-us/powershell/module/az.network/set-azvirtualnetworksubnetconfig
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Set-AzVirtualNetworkSubnetConfig.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/Set-AzVirtualNetworkSubnetConfig.md
