### YamlMime:PowershellCmdlet
summary: ""
module: Az.Websites
notes: ""
inputs:
- name: <xref href="System.Int32" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="System.DateTime" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Azure.Commands.WebApps.Models.PSSite" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Azure.Management.WebSites.Models.DatabaseBackupSetting" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.WebApps.Cmdlets.WebApps.AzureWebAppBackupConfiguration" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-AzWebAppBackupConfiguration
  href: ./Get-AzWebAppBackupConfiguration.yml
syntaxes:
- >-
  Edit-AzWebAppBackupConfiguration [-FrequencyInterval] <Int32> [-FrequencyUnit] <String>

   [-RetentionPeriodInDays] <Int32> [[-StartTime] <DateTime>] [-KeepAtLeastOneBackup]

   [-ResourceGroupName] <String> [-Name] <String> [[-Slot] <String>] [-DefaultProfile <IAzureContextContainer>]

   [-StorageAccountUrl] <String> [[-Databases] <DatabaseBackupSetting[]>] [<CommonParameters>]
- >-
  Edit-AzWebAppBackupConfiguration [-FrequencyInterval] <Int32> [-FrequencyUnit] <String>

   [-RetentionPeriodInDays] <Int32> [[-StartTime] <DateTime>] [-KeepAtLeastOneBackup] [-WebApp] <PSSite>

   [-DefaultProfile <IAzureContextContainer>] [-StorageAccountUrl] <String>

   [[-Databases] <DatabaseBackupSetting[]>] [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    <!-- Aladdin Generated Example --> 
    Edit-AzWebAppBackupConfiguration -FrequencyInterval <Int32> -FrequencyUnit <String> -KeepAtLeastOneBackup -Name IpRule -ResourceGroupName MyResourceGroup -RetentionPeriodInDays <Int32> -StartTime 2016-11-30T22:00:00Z -StorageAccountUrl 'https://storageaccount.file.core.windows.net'
  description: ""
  summary: |+
    The Edit-AzWebAppBackupConfiguration cmdlet edits the current configuration backup for an Azure Web App. (autogenerated)

parameters:
- type: <xref href="Microsoft.Azure.Management.WebSites.Models.DatabaseBackupSetting" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: Databases
  description: |+
    Databases of type DatabaseBackupSetting[]

  defaultValue: None
  pipelineInput: true
  position: "8"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.Int32" data-throw-if-not-resolved="False" />
  name: FrequencyInterval
  isRequired: true
  description: |+
    Frequency Interval

  defaultValue: None
  pipelineInput: true
  position: "4"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: FrequencyUnit
  isRequired: true
  description: |+
    Frequency Unit

  defaultValue: None
  pipelineInput: true
  position: "5"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: KeepAtLeastOneBackup
  description: |+
    Keep At Least One Backup Option

  defaultValue: None
  pipelineInput: true
  position: "9"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    WebApp Name

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: ResourceGroupName
  isRequired: true
  description: |+
    Resource Group Name

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Int32" data-throw-if-not-resolved="False" />
  name: RetentionPeriodInDays
  isRequired: true
  description: |+
    Retention Period In Days

  defaultValue: None
  pipelineInput: true
  position: "6"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Slot
  description: |+
    WebApp Slot Name

  defaultValue: None
  pipelineInput: true
  position: "2"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.DateTime" data-throw-if-not-resolved="False" />
  name: StartTime
  description: |+
    StartTime in UTC

  defaultValue: None
  pipelineInput: true
  position: "7"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: StorageAccountUrl
  isRequired: true
  description: |+
    Storage Account Url

  defaultValue: None
  pipelineInput: true
  position: "3"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.WebApps.Models.PSSite" data-throw-if-not-resolved="False" />
  name: WebApp
  isRequired: true
  description: |+
    WebApp Object

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
uid: Az.Websites.Edit-AzWebAppBackupConfiguration
name: Edit-AzWebAppBackupConfiguration
description: |-
  The **Edit-AzWebAppBackupConfiguration** cmdlet edits the current configuration backup for an Azure Web App.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Websites.dll-Help.xml
  Module Name: Az.Websites
  ms.assetid: BFC38930-DBB4-4EBB-8E29-73B901FAF486
  online version: https://docs.microsoft.com/en-us/powershell/module/az.websites/edit-azwebappbackupconfiguration
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Websites/Websites/help/Edit-AzWebAppBackupConfiguration.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Websites/Websites/help/Edit-AzWebAppBackupConfiguration.md
