### YamlMime:PowershellCmdlet
summary: |-
  Adds a Private DNS record to a local record set object.
module: Az.PrivateDns
notes: ""
inputs:
- name: <xref href="Microsoft.Azure.Commands.PrivateDns.Models.PSPrivateDnsRecordSet" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.PrivateDns.Models.PSPrivateDnsRecordSet" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Add-AzPrivateDnsRecordConfig -RecordSet <PSPrivateDnsRecordSet> -Ipv4Address <String>

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
- >-
  Add-AzPrivateDnsRecordConfig -RecordSet <PSPrivateDnsRecordSet> -Ipv6Address <String>

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
- >-
  Add-AzPrivateDnsRecordConfig -RecordSet <PSPrivateDnsRecordSet> -Exchange <String> -Preference <UInt16>

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
- >-
  Add-AzPrivateDnsRecordConfig -RecordSet <PSPrivateDnsRecordSet> -Ptrdname <String>

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
- >-
  Add-AzPrivateDnsRecordConfig -RecordSet <PSPrivateDnsRecordSet> -Value <String>

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
- >-
  Add-AzPrivateDnsRecordConfig -RecordSet <PSPrivateDnsRecordSet> -Priority <UInt16> -Target <String>

   -Port <UInt16> -Weight <UInt16> [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
- >-
  Add-AzPrivateDnsRecordConfig -RecordSet <PSPrivateDnsRecordSet> -Cname <String>

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
examples:
- title: 'Example 1: Add an A record to a record set'
  code: |-
    PS C:\> $RecordSet = Get-AzPrivateDnsRecordSet -Name www -RecordType A -ResourceGroupName MyResourceGroup -ZoneName myzone.com
    PS C:\> Add-AzPrivateDnsRecordConfig -RecordSet $RecordSet -Ipv4Address 1.2.3.4
    PS C:\> Set-AzPrivateDnsRecordSet -RecordSet $RecordSet

    # You can also pipe the above sequence:

    PS C:\> Get-AzPrivateDnsRecordSet -Name www -RecordType A -ResourceGroupName MyResourceGroup -ZoneName myzone.com | Add-AzPrivateDnsRecordConfig -Ipv4Address 1.2.3.4 | Set-AzPrivateDnsRecordSet

    Id                : /subscriptions/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/myresourcegroup/providers/Micros
                        oft.Network/privateDnsZones/myzone.com/A/www
    Name              : www
    ZoneName          : myzone.com
    ResourceGroupName : MyResourceGroup
    Ttl               : 3600
    Etag              : xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    RecordType        : A
    Records           : {1.2.3.4}
    Metadata          :
    IsAutoRegistered  :
  description: |-
    This example adds an A record to an existing record set.
  summary: ""
- title: 'Example 2: Add an AAAA record to a record set'
  code: |-
    PS C:\> $RecordSet = Get-AzPrivateDnsRecordSet -Name www -RecordType AAAAA -ResourceGroupName MyResourceGroup -ZoneName myzone.com
    PS C:\> Add-AzPrivateDnsRecordConfig -RecordSet $RecordSet -Ipv6Address 2001:DB80:4009:1803::1005
    PS C:\> Set-AzPrivateDnsRecordSet -RecordSet $RecordSet

    # You can also pipe the above sequence:

    PS C:\> Get-AzPrivateDnsRecordSet -Name www -RecordType AAAAA -ResourceGroupName MyResourceGroup -ZoneName myzone.com | Add-AzPrivateDnsRecordConfig -Ipv6Address 2001:DB80:4009:1803::1005 | Set-AzPrivateDnsRecordSet

    Id                : /subscriptions/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/myresourcegroup/providers/Micros
                        oft.Network/privateDnsZones/myzone.com/AAAA/www
    Name              : www
    ZoneName          : myzone.com
    ResourceGroupName : MyResourceGroup
    Ttl               : 3600
    Etag              : xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    RecordType        : AAAA
    Records           : {2001:DB80:4009:1803::1005}
    Metadata          :
    IsAutoRegistered  :
  description: |-
    This example adds an AAAAA record to an existing record set.
  summary: ""
- title: 'Example 3: Add a CNAME record to a record set'
  code: |-
    PS C:\> $RecordSet = Get-AzPrivateDnsRecordSet -Name www -RecordType CNAME -ResourceGroupName MyResourceGroup -ZoneName myzone.com
    PS C:\> Add-AzPrivateDnsRecordConfig -RecordSet $RecordSet -Cname contoso.com
    PS C:\> Set-AzPrivateDnsRecordSet -RecordSet $RecordSet

    # You can also pipe the above sequence:

    PS C:\> Get-AzPrivateDnsRecordSet -Name www -RecordType CNAME -ResourceGroupName MyResourceGroup -ZoneName myzone.com | Add-AzPrivateDnsRecordConfig -Cname contoso.com | Set-AzPrivateDnsRecordSet

    Id                : /subscriptions/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/myresourcegroup/providers/Micros
                        oft.Network/privateDnsZones/myzone.com/CNAME/www
    Name              : www
    ZoneName          : myzone.com
    ResourceGroupName : MyResourceGroup
    Ttl               : 3600
    Etag              : xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    RecordType        : CNAME
    Records           : {www.contoso.com}
    Metadata          :
    IsAutoRegistered  :
  description: |-
    This example adds a CNAME record to an existing record set.
  summary: ""
- title: 'Example 4: Add a MX record to a record set'
  code: |-
    PS C:\> $RecordSet = Get-AzPrivateDnsRecordSet -Name @ -RecordType MX -ResourceGroupName MyResourceGroup -ZoneName myzone.com
    PS C:\> Add-AzPrivateDnsRecordConfig -Exchange mail.microsoft.com -Preference 5 -RecordSet $RecordSet
    PS C:\> Set-AzPrivateDnsRecordSet -RecordSet $RecordSet

    # You can also pipe the above sequence:

    PS C:\> Get-AzPrivateDnsRecordSet -Name "@" -RecordType MX -ResourceGroupName MyResourceGroup -ZoneName myzone.com | Add-AzPrivateDnsRecordConfig -Exchange mail.microsoft.com -Preference 5 | Set-AzPrivateDnsRecordSet

    Id                : /subscriptions/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/myresourcegroup/providers/Micros
                        oft.Network/privateDnsZones/myzone.com/MX/www
    Name              : www
    ZoneName          : myzone.com
    ResourceGroupName : MyResourceGroup
    Ttl               : 3600
    Etag              : xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    RecordType        : MX
    Records           : {[5,mail.microsoft.com]}
    Metadata          :
    IsAutoRegistered  :
  description: |-
    This example adds a MX record to an existing record set.
  summary: ""
- title: 'Example 5: Add a PTR record to a record set'
  code: |-
    PS C:\> $RecordSet = Get-AzPrivateDnsRecordSet -Name 4 -RecordType PTR -ResourceGroupName MyResourceGroup -ZoneName 3.2.1.in-addr.arpa
    PS C:\> Add-AzPrivateDnsRecordConfig -Ptrdname www.contoso.com -RecordSet $RecordSet
    PS C:\> Set-AzPrivateDnsRecordSet -RecordSet $RecordSet

    # You can also pipe the above sequence:

    PS C:\> Get-AzPrivateDnsRecordSet -Name 4 -RecordType PTR -ResourceGroupName MyResourceGroup -ZoneName 3.2.1.in-addr.arpa | Add-AzPrivateDnsRecordConfig -Ptrdname www.contoso.com | Set-AzPrivateDnsRecordSet

    Id                : /subscriptions/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/myresourcegroup/providers/Micros
                        oft.Network/privateDnsZones/3.2.1.in-addr.arpa/PTR/4
    Name              : 4
    ZoneName          : 3.2.1.in-addr.arpa
    ResourceGroupName : MyResourceGroup
    Ttl               : 3600
    Etag              : xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    RecordType        : PTR
    Records           : {www.contoso.com}
    Metadata          :
    IsAutoRegistered  :
  description: |-
    This example adds a PTR record to an existing record set.
  summary: ""
- title: 'Example 6: Add a SRV record to a record set'
  code: |-
    PS C:\> $RecordSet = Get-AzPrivateDnsRecordSet -Name _sip._tcp -RecordType SRV -ResourceGroupName MyResourceGroup-ZoneName myzone.com
    PS C:\> Add-AzPrivateDnsRecordConfig -Priority 0 -Weight 5 -Port 8080 -Target target.example.com
    PS C:\> Set-AzPrivateDnsRecordSet -RecordSet $RecordSet

    # You can also pipe the above sequence:

    PS C:\> Get-AzPrivateDnsRecordSet -Name _sip._tcp -RecordType SRV -ResourceGroupName MyResourceGroup -ZoneName myzone.com | Add-AzPrivateDnsRecordConfig -Priority 0 -Weight 5 -Port 8080 -Target target.example.com | Set-AzPrivateDnsRecordSet

    Id                : /subscriptions/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/myresourcegroup/providers/Micros
                        oft.Network/privateDnsZones/myzone.com/SRV/_sip._tcp
    Name              : _sip._tcp
    ZoneName          : myzone.com
    ResourceGroupName : MyResourceGroup
    Ttl               : 3600
    Etag              : xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    RecordType        : SRV
    Records           : {[0,5,8080,sipservice.contoso.com]}
    Metadata          :
    IsAutoRegistered  :
  description: |-
    This example adds a SRV record to an existing record set.
  summary: ""
- title: 'Example 7: Add a TXT record to a record set'
  code: |-
    PS C:\> $RecordSet = Get-AzPrivateDnsRecordSet -Name text -RecordType TXT -ResourceGroupName MyResourceGroup -ZoneName myzone.com
    PS C:\> Add-AzPrivateDnsRecordConfig -RecordSet $RecordSet -Value "This is a TXT Record"
    PS C:\> Set-AzPrivateDnsRecordSet -RecordSet $RecordSet

    # You can also pipe the above sequence:

    PS C:\> Get-AzPrivateDnsRecordSet -Name text -RecordType TXT -ResourceGroupName MyResourceGroup -ZoneName myzone.com | Add-AzPrivateDnsRecordConfig -Value "This is a TXT Record" | Set-AzPrivateDnsRecordSet

    Id                : /subscriptions/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/myresourcegroup/providers/Micros
                        oft.Network/privateDnsZones/myzone.com/TXT/text
    Name              : text
    ZoneName          : myzone.com
    ResourceGroupName : MyResourceGroup
    Ttl               : 3600
    Etag              : xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    RecordType        : TXT
    Records           : {This is a TXT Record}
    Metadata          :
    IsAutoRegistered  :
  description: |-
    This example adds a TXT record to an existing record set.
  summary: ""
parameters:
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Cname
  isRequired: true
  description: |+
    The canonical name for the CNAME record to add.
    Must not be relative to the name of the zone.
    Must not have a terminating dot

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with Azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Exchange
  isRequired: true
  description: |+
    The mail exchange host for the MX record to add.
    Must not be relative to the name of the zone.
    Must not have a terminating dot

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Ipv4Address
  isRequired: true
  description: |+
    The IPv4 address for the A record to add.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Ipv6Address
  isRequired: true
  description: |+
    The IPv6 address for the AAAA record to add.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.UInt16" data-throw-if-not-resolved="False" />
  name: Port
  isRequired: true
  description: |+
    The port number for the SRV record to add.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.UInt16" data-throw-if-not-resolved="False" />
  name: Preference
  isRequired: true
  description: |+
    The preference value for the MX record to add.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.UInt16" data-throw-if-not-resolved="False" />
  name: Priority
  isRequired: true
  description: |+
    The priority value SRV record to add.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Ptrdname
  isRequired: true
  description: |+
    The target host for the PTR record to add.
    Must not be relative to the name of the zone.
    Must not have a terminating dot

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.PrivateDns.Models.PSPrivateDnsRecordSet" data-throw-if-not-resolved="False" />
  name: RecordSet
  isRequired: true
  description: |+
    The record set in which to add the record.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Target
  isRequired: true
  description: |+
    The target host for the SRV record to add.
    Must not be relative to the name of the zone.
    Must not have a terminating dot

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Value
  isRequired: true
  description: |+
    The text value for the TXT record to add.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.UInt16" data-throw-if-not-resolved="False" />
  name: Weight
  isRequired: true
  description: |+
    The weight value for the SRV record to add.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Az.PrivateDns.Add-AzPrivateDnsRecordConfig
name: Add-AzPrivateDnsRecordConfig
description: |-
  The Add-AzPrivateDnsRecordConfig cmdlet adds a Private Domain Name System (DNS) record to a RecordSet object. The RecordSet object is an offline object, and changes to it do not change the Private DNS responses until after you run the Set-AzPrivateDnsRecordSet cmdlet to persist the change to the Microsoft Azure Private DNS service. SOA records are created when a Private DNS zone is created, and are removed when the Private DNS zone is deleted. You cannot add or remove SOA records, but you can edit them. You can pass the RecordSet object to this cmdlet as a parameter or by using the pipeline operator.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.PrivateDns.dll-Help.xml
  Module Name: Az.PrivateDns
  online version: https://docs.microsoft.com/en-us/powershell/module/az.privatedns/add-azprivatednsrecordconfig
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/PrivateDns/PrivateDns/help/Add-AzPrivateDnsRecordConfig.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/PrivateDns/PrivateDns/help/Add-AzPrivateDnsRecordConfig.md
