### YamlMime:PowershellCmdlet
summary: |-
  Get the Azure Advisor configurations for the given subscription or resource group.
module: Az.Advisor
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Advisor.Cmdlets.Models.PsAzureAdvisorConfigurationData" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Get-AzAdvisorConfiguration [-ResourceGroupName <String>] [-DefaultProfile <IAzureContextContainer>]

   [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    PS C:\>$data = Get-AzAdvisorConfiguration
    Id         : /subscriptions/{user_subscription}/providers/Microsoft.Advisor/configurations/{user_subscription}
    Name       : {user_subscription}
    Properties : Microsoft.Azure.Commands.Advisor.Cmdlets.Models.PsAzureAdvisorConfigurationProperties
    Type       : Microsoft.Advisor/Configurations

    Id         : /subscriptions/{user_subscription}/providers/Microsoft.Advisor/configurations/{user_subscription}-{resourceGroupName}
    Name       : {user_subscription}-{resourceGroupName}
    Properties : Microsoft.Azure.Commands.Advisor.Cmdlets.Models.PsAzureAdvisorConfigurationProperties
    Type       : Microsoft.Advisor/Configurations

    PS C:\>$data[0].Properties
    AdditionalProperties :
    Exclude              : False
    LowCpuThreshold      : 20

    PS C:\>$data[1].Properties
    AdditionalProperties :
    Exclude              : True
    LowCpuThreshold      : null
  description: |-
    Retrieves a list of Azure Advisor Configuration(s).
  summary: ""
parameters:
- type: <xref href="IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with Azure.

  defaultValue: None
  position: Named
  aliases: AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ResourceGroupName
  description: |+
    Resource Group name of the configuration

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Az.Advisor.Get-AzAdvisorConfiguration
name: Get-AzAdvisorConfiguration
description: |-
  The configurations associated with a subscription have two types:

  Subscription level configuration: There can be only one configuration of this type for a subscription. LowCpuThreshold and Exclude are the only property of this type of configuration.

  ResourceGroup level configuration: There can be only one configuration for each ResourceGroup in a subscription. Exclude is the only property of this type of configuration.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Advisor.dll-Help.xml
  Module Name: Az.Advisor
  online version: https://docs.microsoft.com/en-us/powershell/module/az.advisor/get-azadvisorconfiguration
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Advisor/Advisor/help/Get-AzAdvisorConfiguration.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Advisor/Advisor/help/Get-AzAdvisorConfiguration.md
