### YamlMime:PowershellCmdlet
summary: |-
  Get Service Fabric application type version details.
module: Az.ServiceFabric
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.ServiceFabric.Models.PSApplicationTypeVersion" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Get-AzServiceFabricApplicationTypeVersion [-ResourceGroupName] <String> [-ClusterName] <String>

   [-Name] <String> [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
- >-
  Get-AzServiceFabricApplicationTypeVersion [-ResourceGroupName] <String> [-ClusterName] <String>

   [-Name] <String> [-Version] <String> [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
- >-
  Get-AzServiceFabricApplicationTypeVersion -ResourceId <String> [-DefaultProfile <IAzureContextContainer>]

   [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    PS C:\> $resourceGroupName = "testRG"
    PS C:\> $clusterName = "testCluster"
    PS C:\> $appTypeName = "testAppType"
    PS C:\> $appTypeName = "v1"
    PS C:\> Get-AzServiceFabricApplicationTypeVersion -ResourceGroupName $resourceGroupName -ClusterName $clusterName -Name $appTypeName -Version
  description: |-
    This example gets the application type "testAppType" with version "v1", if it doesn't find the resource it will throw an exception.
  summary: ""
- title: Example 2
  code: |-
    PS C:\> $resourceGroupName = "testRG"
    PS C:\> $clusterName = "testCluster"
    PS C:\> $appTypeName = "testAppType"
    PS C:\> Get-AzServiceFabricApplicationTypeVersion -ResourceGroupName $resourceGroupName -ClusterName $clusterName -Name $appTypeName
  description: |-
    This example gets a list of the application type versions defined under the specified cluster and type.
  summary: ""
parameters:
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: ClusterName
  isRequired: true
  description: |+
    Specify the name of the cluster.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with Azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    Specify the name of the application type.

  defaultValue: None
  pipelineInput: true
  position: "2"
  aliases: ApplicationTypeName
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: ResourceGroupName
  isRequired: true
  description: |+
    Specify the name of the resource group.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: ResourceId
  isRequired: true
  description: |+
    Arm ResourceId of the application type version.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Version
  isRequired: true
  description: |+
    Specify the version of the application type.

  defaultValue: None
  pipelineInput: true
  position: "3"
  aliases: ApplicationTypeVersion
  parameterValueGroup: ""
uid: Az.ServiceFabric.Get-AzServiceFabricApplicationTypeVersion
name: Get-AzServiceFabricApplicationTypeVersion
description: |-
  Use this cmdlet to get the application type version details in the specified resource group and cluster.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.ServiceFabric.dll-Help.xml
  Module Name: Az.ServiceFabric
  online version: https://docs.microsoft.com/en-us/powershell/module/az.servicefabric/get-azservicefabricapplicationtypeversion
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/ServiceFabric/ServiceFabric/help/Get-AzServiceFabricApplicationTypeVersion.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/ServiceFabric/ServiceFabric/help/Get-AzServiceFabricApplicationTypeVersion.md
