### YamlMime:PowershellCmdlet
summary: |-
  Invoke an IoT Edge deployment metric query.
module: Az.IotHub
notes: ""
inputs:
- name: <xref href="Microsoft.Azure.Commands.Management.IotHub.Models.PSIotHub" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Management.IotHub.Models.PSConfigurationMetricsResult" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Invoke-AzIotHubDeploymentMetricsQuery [-ResourceGroupName] <String> [-IotHubName] <String> -Name <String>

   -MetricName <String> [-MetricType <PSConfigurationMetricType>] [-DefaultProfile <IAzureContextContainer>]

   [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Invoke-AzIotHubDeploymentMetricsQuery [-InputObject] <PSIotHub> -Name <String> -MetricName <String>

   [-MetricType <PSConfigurationMetricType>] [-DefaultProfile <IAzureContextContainer>] [-WhatIf] [-Confirm]

   [<CommonParameters>]
- >-
  Invoke-AzIotHubDeploymentMetricsQuery [-ResourceId] <String> -Name <String> -MetricName <String>

   [-MetricType <PSConfigurationMetricType>] [-DefaultProfile <IAzureContextContainer>] [-WhatIf] [-Confirm]

   [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    PS C:\> Invoke-AzIotHubDeploymentMetricsQuery -ResourceGroupName "myresourcegroup" -IotHubName "myiothub" -Name "myDeploy1" -MetricName "warningLimit"
  description: |-
    Evaluate the custom defined 'warningLimit' metric.
  summary: ""
- title: Example 2
  code: |-
    PS C:\> Invoke-AzIotHubDeployMetric -ResourceGroupName "myresourcegroup" -IotHubName "myiothub" -Name "myDeploy1" -MetricName "Reporting Success" -MetricType "system"
  description: |-
    Evaluate the system 'Reporting Success' metric.
  summary: ""
parameters:
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with Azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Management.IotHub.Models.PSIotHub" data-throw-if-not-resolved="False" />
  name: InputObject
  isRequired: true
  description: |+
    IotHub object

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: IotHubName
  isRequired: true
  description: |+
    Name of the Iot Hub

  defaultValue: None
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: MetricName
  isRequired: true
  description: |+
    Target metric for evaluation.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Management.IotHub.Models.PSConfigurationMetricType" data-throw-if-not-resolved="False" />
  name: MetricType
  description: |+
    Indicates which metric collection should be used to lookup a metric.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: Custom, System
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    Identifier for the deployment.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: ResourceGroupName
  isRequired: true
  description: |+
    Name of the Resource Group

  defaultValue: None
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: ResourceId
  isRequired: true
  description: |+
    IotHub Resource Id

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Az.IotHub.Invoke-AzIotHubDeploymentMetricsQuery
name: Invoke-AzIotHubDeploymentMetricsQuery
description: |-
  Evaluate a target custom or system metric defined in an IoT Edge deployment.
  There are pre-defined system metrics which are calculated by Iot Hub and cannot be customized.
  - "Targeted" shows the IoT Edge devices that match the deployment targeting condition.
  - "Applied" shows the targeted IoT Edge devices that are not targeted by another deployment of higher priority.
  - "Reporting Success" shows the IoT Edge devices that have reported that the modules have been deployed successfully.
  - "Reporting Failure" shows the IoT Edge devices that have reported that one or more modules haven't been deployed successfully. 
    To further investigate the error, connect remotely to those devices and view the log files.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.IotHub.dll-Help.xml
  Module Name: Az.IotHub
  online version: https://docs.microsoft.com/en-us/powershell/module/az.iothub/invoke-aziothubdeploymentmetricsquery
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/IotHub/IotHub/help/Invoke-AzIotHubDeploymentMetricsQuery.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/IotHub/IotHub/help/Invoke-AzIotHubDeploymentMetricsQuery.md
