### YamlMime:PowershellCmdlet
summary: |-
  Set Web App Slot Config names
module: Az.Websites
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  description: ""
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Azure.Commands.WebApps.Models.PSSite" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Management.WebSites.Models.SlotConfigNamesResource" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Set-AzWebAppSlotConfigName [[-AppSettingNames] <String[]>] [[-ConnectionStringNames] <String[]>]

   [-RemoveAllAppSettingNames] [-RemoveAllConnectionStringNames] [-ResourceGroupName] <String> [-Name] <String>

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
- >-
  Set-AzWebAppSlotConfigName [[-AppSettingNames] <String[]>] [[-ConnectionStringNames] <String[]>]

   [-RemoveAllAppSettingNames] [-RemoveAllConnectionStringNames] [-WebApp] <PSSite>

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
examples:
- title: '1:'
  code: |-
    PS C:\> Set-AzWebAppSlotConfigName -ResourceGroupName "Default-Web-WestUS" -Name "ContosoWebApp" -RemoveAllAppSettingNames -RemoveAllConnectionStringNames
  description: |-
    This command removes all app settings and connection strings for Web App ContosoWebApp associated with the resource group Default-Web-WestUS
  summary: ""
parameters:
- type: <xref href="System.String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: AppSettingNames
  description: |+
    App Settings Names String Array

  defaultValue: None
  pipelineInput: true
  position: "2"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: ConnectionStringNames
  description: |+
    Connection String Names String Array

  defaultValue: None
  pipelineInput: true
  position: "3"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    WebApp Name

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: RemoveAllAppSettingNames
  description: |+
    Remove All App Setting Names Option

  defaultValue: None
  position: "4"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: RemoveAllConnectionStringNames
  description: |+
    Remove All Connection String Names Option

  defaultValue: None
  position: "5"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: ResourceGroupName
  isRequired: true
  description: |+
    Resource Group Name

  defaultValue: None
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.WebApps.Models.PSSite" data-throw-if-not-resolved="False" />
  name: WebApp
  isRequired: true
  description: |+
    WebApp Object

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
uid: Az.Websites.Set-AzWebAppSlotConfigName
name: Set-AzWebAppSlotConfigName
description: |-
  The **Set-AzWebAppSlotConfigName** cmdlet marks App Settings and Connection Strings as slot settings
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Websites.dll-Help.xml
  Module Name: Az.Websites
  ms.assetid: 7DBF937E-2D01-4356-9A5F-C5A4CB6D1A10
  online version: https://docs.microsoft.com/en-us/powershell/module/az.websites/set-azwebappslotconfigname
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Websites/Websites/help/Set-AzWebAppSlotConfigName.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Websites/Websites/help/Set-AzWebAppSlotConfigName.md
