### YamlMime:PowershellCmdlet
summary: |-
  Get Public Maintenance Configuration record
module: Az.Maintenance
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Maintenance.Models.PSMaintenanceConfiguration" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Get-AzMaintenancePublicConfiguration [[-ResourceGroupName] <String>] [[-Name] <String>]

   [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    PS C:\> Get-AzMaintenancePublicConfiguration -ResourceGroupName smdtest -Name workervmscentralus


    Location            : centralus
    Tags                : {}
    NamespaceProperty   :
    ExtensionProperties : {"publicMaintenanceConfigurationId" : "workervmscentralus"}
    StartDateTime       : 2020-08-01 00:00
    ExpirationDateTime  : 2021-08-04 00:00
    TimeZone            : Pacific Standard Time
    RecurEvery          : Day
    Duration            : 05:00
    MaintenanceScope    : SQLDB
    Visibility          : Public
    Id                  : /subscriptions/42c974dd-2c03-4f1b-96ad-b07f050aaa74/resourcegroups/smdtest/providers/Microsoft.Maintenance/publicMaintenanceConfigurations/workervmscentralus
    Name                : workervmscentralus
    Type                : Microsoft.Maintenance/publicMaintenanceConfigurations
  description: |-
    Get Public Maintenance configuration record
  summary: ""
parameters:
- type: <xref href="IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with Azure.

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Name
  description: |+
    The public maintenance configuration Name.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ResourceGroupName
  description: |+
    The resource Group Name.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
uid: Az.Maintenance.Get-AzMaintenancePublicConfiguration
name: Get-AzMaintenancePublicConfiguration
description: |-
  Get Public Maintenance Configuration record
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Maintenance.dll-Help.xml
  Module Name: Az.Maintenance
  online version: https://docs.microsoft.com/en-us/powershell/module/az.maintenance/get-azmaintenancepublicconfiguration
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Maintenance/Maintenance/help/Get-AzMaintenancePublicConfiguration.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Maintenance/Maintenance/help/Get-AzMaintenancePublicConfiguration.md
