### YamlMime:PowershellCmdlet
summary: |-
  Create a storage account configuration for the media service cmdlets.
module: Az.Media
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Media.Models.PSStorageAccount" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  New-AzMediaServiceStorageConfig [-DefaultProfile <IAzureContextContainer>] [-StorageAccountId] <String>

   [-IsPrimary] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: 'Example 1: Create a storage account configuration for the media service cmdlets'
  code: |-
    PS C:\>
    $StorageAccount = New-AzStorageAccount -ResourceGroupName $ResourceGroupName -Name "Storage1" -Location "East US" -Type "Standard_GRS"

    PS C:\> New-AzMediaServiceStorageConfig -StorageAccountId $StorageAccount.Id -IsPrimary
  description: |-
    The first command creates a storage account object by using **the New-AzStorageAccount** cmdlet.
    The command names this storage account Storage1 and the type is named Standard_GRS and stores the result in the variable named $StorageAccount.
    The second command creates a storage configuration object as the primary storage account associated with the media service using the storage account ID information stored in the $StorageAccount variable.
  summary: ""
parameters:
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with azure

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: IsPrimary
  description: |+
    Indicates that the cmdlet creates the storage account as the primary storage for the media service.

  defaultValue: None
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: StorageAccountId
  isRequired: true
  description: |+
    Specifies the ID of the storage account.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Az.Media.New-AzMediaServiceStorageConfig
name: New-AzMediaServiceStorageConfig
description: |-
  The **New-AzMediaServiceStorageConfig** cmdlet creates a storage account configuration for the media service cmdlets.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Media.dll-Help.xml
  Module Name: Az.Media
  ms.assetid: 4D64CA4D-1066-4D3E-9317-60D37D9DE2BB
  online version: https://docs.microsoft.com/en-us/powershell/module/az.media/new-azmediaservicestorageconfig
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Media/Media/help/New-AzMediaServiceStorageConfig.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Media/Media/help/New-AzMediaServiceStorageConfig.md
