### YamlMime:PowershellCmdlet
summary: |-
  Gets information about a configuration of server.
module: Az.PostgreSql
notes: |-
  ALIASES

  COMPLEX PARAMETER PROPERTIES

  To create the parameters described below, construct a hash table containing the appropriate properties. For information on hash tables, run Get-Help about_Hash_Tables.


  INPUTOBJECT <IPostgreSqlIdentity>: Identity Parameter
    - `[ConfigurationName <String>]`: The name of the server configuration.
    - `[DatabaseName <String>]`: The name of the database.
    - `[FirewallRuleName <String>]`: The name of the server firewall rule.
    - `[Id <String>]`: Resource identity path
    - `[LocationName <String>]`: The name of the location.
    - `[ResourceGroupName <String>]`: The name of the resource group. The name is case insensitive.
    - `[SecurityAlertPolicyName <SecurityAlertPolicyName?>]`: The name of the security alert policy.
    - `[ServerName <String>]`: The name of the server.
    - `[SubscriptionId <String>]`: The ID of the target subscription.
    - `[VirtualNetworkRuleName <String>]`: The name of the virtual network rule.
inputs:
- name: <xref href="Microsoft.Azure.PowerShell.Cmdlets.PostgreSql.Models.IPostgreSqlIdentity" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.PowerShell.Cmdlets.PostgreSql.Models.Api20171201.IConfiguration" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Get-AzPostgreSqlConfiguration -ResourceGroupName <String> -ServerName <String> [-SubscriptionId <String[]>]

   [-DefaultProfile <PSObject>] [<CommonParameters>]
- >-
  Get-AzPostgreSqlConfiguration -Name <String> -ResourceGroupName <String> -ServerName <String>

   [-SubscriptionId <String[]>] [-DefaultProfile <PSObject>] [<CommonParameters>]
- >-
  Get-AzPostgreSqlConfiguration -InputObject <IPostgreSqlIdentity> [-DefaultProfile <PSObject>]

   [<CommonParameters>]
examples:
- title: 'Example 1: List all configurations in PostgreSql server'
  code: |-
    PS C:\> Get-AzPostgreSqlConfiguration -ResourceGroupName PostgreSqlTestRG -ServerName PostgreSqlTestServer

    Name                                  Value
    ----                                  -----
    array_nulls                           on
    backslash_quote                       safe_encoding
    bytea_output                          hex
    check_function_bodies                 on
    client_encoding                       sql_ascii
    ...
    azure.replication_support             REPLICA
    max_wal_senders                       10
    max_replication_slots                 10
    hot_standby_feedback                  off
    logging_collector                     on
  description: |-
    This cmdlet lists all configurations in specified PostgreSql server.
  summary: ""
- title: 'Example 2: Get specified PostgreSql configuration by name'
  code: |-
    PS C:\> Get-AzPostgreSqlConfiguration -Name timezone -ResourceGroupName PostgreSqlTestRG -ServerName PostgreSqlTestServer

    Name     Value
    ----     -----
    timezone UTC
  description: |-
    This cmdlet gets specified PostgreSql configuration by name.
  summary: ""
parameters:
- type: <xref href="System.Management.Automation.PSObject" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, account, tenant, and subscription used for communication with Azure.

  defaultValue: None
  position: Named
  aliases: AzureRMContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="Microsoft.Azure.PowerShell.Cmdlets.PostgreSql.Models.IPostgreSqlIdentity" data-throw-if-not-resolved="False" />
  name: InputObject
  isRequired: true
  description: |+
    Identity Parameter
    To construct, see NOTES section for INPUTOBJECT properties and create a hash table.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    The name of the server configuration.

  defaultValue: None
  position: Named
  aliases: ConfigurationName
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: ResourceGroupName
  isRequired: true
  description: |+
    The name of the resource group.
    The name is case insensitive.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: ServerName
  isRequired: true
  description: |+
    The name of the server.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: SubscriptionId
  description: |+
    The ID of the target subscription.

  defaultValue: (Get-AzContext).Subscription.Id
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Az.PostgreSql.Get-AzPostgreSqlConfiguration
name: Get-AzPostgreSqlConfiguration
description: |-
  Gets information about a configuration of server.
metadata:
  external help file: ""
  Module Name: Az.PostgreSql
  online version: https://docs.microsoft.com/en-us/powershell/module/az.postgresql/get-azpostgresqlconfiguration
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/PostgreSql/help/Get-AzPostgreSqlConfiguration.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/PostgreSql/help/Get-AzPostgreSqlConfiguration.md
